#!/usr/bin/env node
/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 *
 * PortAuth A2A Extension v1 - Proof of Concept
 *
 * Demonstrates that the PortAuth engine can authorize a Google A2A
 * SendMessage request with no engine changes by carrying the VC in
 * message.metadata under the extension URI. Exercises UC-03 (cross-boundary
 * customer-delegated bill payment) with one allow case and three deny cases.
 *
 * Wire format follows the A2A v1.0 specification: PascalCase JSON-RPC method
 * `SendMessage`, ROLE_USER role enum, required messageId on every Message,
 * member-name-discriminated Part, and the A2A-Extensions service-parameter
 * header (transmitted out-of-band by a real HTTP transport).
 *
 * Requires the standard compose stack:
 *   podman compose -f portauth-docker-compose.yml up -d
 *
 * Then:
 *   node extensions/a2a/poc/run.js
 */

const { randomUUID } = require("node:crypto");

const ISSUER_URL = process.env.ISSUER_URL || "http://localhost:3100";
const ENGINE_URL = process.env.ENGINE_URL || "http://localhost:3200";
const ISSUER_KEY = process.env.ISSUER_KEY || "dev-issuer-key-change-me";
const ENGINE_KEY = process.env.ENGINE_KEY || "dev-engine-key-change-me";
// The engine resolves trust by matching the credential's `iss` claim, which is
// the issuer's own self-view. In the compose network this is the container
// hostname, not the host-port URL the script uses to reach the issuer.
const ISSUER_ID_FOR_ENGINE = process.env.ISSUER_ID_FOR_ENGINE || "http://portauth-issuer:3100";
const EXT_URI = "https://kyndryl-open-source.github.io/aiagent-portable-authorization/a2a/v1";

const PRESENTER_ID = "agent:customer-finance-1";

async function http(method, url, body, bearer) {
  const headers = { "content-type": "application/json" };
  if (bearer) headers.authorization = `Bearer ${bearer}`;
  const res = await fetch(url, { method, headers, body: body ? JSON.stringify(body) : undefined });
  const text = await res.text();
  let parsed;
  try { parsed = JSON.parse(text); } catch { parsed = { raw: text }; }
  if (!res.ok && res.status !== 200) {
    return { ok: false, status: res.status, body: parsed };
  }
  return { ok: true, status: res.status, body: parsed };
}

async function registerIssuer() {
  const resp = await http("POST", `${ENGINE_URL}/admin/issuers`, {
    issuerId: ISSUER_ID_FOR_ENGINE,
    trustTier: 1,
    trustedForPermissions: ["payments:bill_pay"],
    label: "A2A PoC Issuer",
    jwksUri: `${ISSUER_ID_FOR_ENGINE}/.well-known/jwks.json`,
  }, ENGINE_KEY);
  if (resp.ok) return;
  // Already registered: union the existing permission list with ours via PUT.
  if (resp.status === 409) {
    const list = await http("GET", `${ENGINE_URL}/admin/issuers`, null, ENGINE_KEY);
    const existing = (list.body?.issuers || []).find((i) => i.issuer_id === ISSUER_ID_FOR_ENGINE);
    const merged = Array.from(new Set([...(existing?.trusted_for_permissions || []), "payments:bill_pay"]));
    const put = await http("PUT", `${ENGINE_URL}/admin/issuers/${encodeURIComponent(ISSUER_ID_FOR_ENGINE)}`,
      { trustedForPermissions: merged }, ENGINE_KEY);
    if (!put.ok) throw new Error(`PUT issuer perms failed: ${JSON.stringify(put.body)}`);
    return;
  }
  throw new Error(`registerIssuer failed: ${JSON.stringify(resp.body)}`);
}

async function issueVc() {
  const resp = await http("POST", `${ISSUER_URL}/credentials/issue`, {
    agentId: PRESENTER_ID,
    permissions: ["payments:bill_pay"],
    constraints: [
      { type: "NumericLimitConstraint", field: "core.amount", operator: "lte", value: 2500, currency: "USD" },
      { type: "EnumeratedListConstraint", field: "core.recipient_id", allowed: ["utilities", "telco", "mortgage"] },
      { type: "EnumeratedListConstraint", field: "core.geo_region", allowed: ["US"] },
    ],
  }, ISSUER_KEY);
  if (!resp.ok) throw new Error(`issueVc failed: ${JSON.stringify(resp.body)}`);
  return resp.body.credential;
}

// Build an A2A SendMessage JSON-RPC payload with the VC under metadata, per
// SPEC §2.3 and A2A spec §3.2.1 / §9.4.1. Field names follow A2A's wire
// contract: PascalCase JSON-RPC method, SCREAMING_SNAKE role enum, required
// messageId, member-name-discriminated Part.
function buildA2aMessage(vc, text, idempotencyKey) {
  return {
    jsonrpc: "2.0",
    id: 1,
    method: "SendMessage",
    params: {
      message: {
        messageId: randomUUID(),
        role: "ROLE_USER",
        parts: [{ text }],
        extensions: [EXT_URI],
        metadata: {
          [`${EXT_URI}/vc`]: vc,
          [`${EXT_URI}/vcFormat`]: "tier1-jwt",
          [`${EXT_URI}/presenterId`]: PRESENTER_ID,
          ...(idempotencyKey ? { [`${EXT_URI}/idempotencyKey`]: idempotencyKey } : {}),
        },
      },
    },
  };
}

// Simulated A2A receiver: extract VC and forwardable fields from metadata,
// translate into a PortAuth /evaluate body per SPEC §3.
async function a2aReceive(a2aMsg, requestContext) {
  const msg = a2aMsg.params.message;
  if (!msg.messageId) throw new Error("invalid_request: messageId is required (A2A §4.1.4)");
  if (msg.role !== "ROLE_USER" && msg.role !== "ROLE_AGENT") {
    throw new Error(`invalid_request: role must be ROLE_USER or ROLE_AGENT, got ${msg.role}`);
  }
  const md = msg.metadata || {};
  const credential = md[`${EXT_URI}/vc`];
  const presenterId = md[`${EXT_URI}/presenterId`];
  const vcFormat = md[`${EXT_URI}/vcFormat`];
  const idempotencyKey = md[`${EXT_URI}/idempotencyKey`];
  const proofOfPossession = md[`${EXT_URI}/proofOfPossession`];
  if (!credential || !presenterId) throw new Error("invalid_request: extension metadata missing");
  if (vcFormat && vcFormat !== "tier1-jwt" && vcFormat !== "tier2-x509-jwt" && vcFormat !== "tier3-vc-jose") {
    throw new Error(`invalid_request: unsupported vcFormat ${vcFormat}`);
  }
  const body = {
    credential, presenterId,
    requestContext: { ...requestContext, ...(idempotencyKey ? { idempotencyKey } : {}) },
    ...(proofOfPossession ? { proofOfPossession } : {}),
    ...(idempotencyKey ? { idempotencyKey } : {}),
  };
  return http("POST", `${ENGINE_URL}/evaluate`, body);
}

function assert(label, cond, detail) {
  if (cond) { console.log(`  PASS  ${label}`); return true; }
  console.log(`  FAIL  ${label}  ::  ${JSON.stringify(detail)}`); return false;
}

async function main() {
  console.log("=== PortAuth A2A Extension v1 PoC (UC-03 bill payment) ===\n");

  console.log("[setup] register trusted issuer with engine");
  await registerIssuer();
  console.log("[setup] issue UC-03 VC at the customer-side issuer");
  const vc = await issueVc();
  console.log(`[setup] VC issued (${vc.length} chars), wrapping in A2A metadata\n`);

  const scenarios = [
    { name: "S1 allow: within all bounds",
      text: "Pay my electric bill $2,400",
      ctx: { action: "payments:bill_pay", resource: "urn:bank:utilities/electric",
             claimAmount: 2400, currency: "USD", recipientId: "utilities", geoRegion: "US" },
      expect: { decision: "allow" } },
    { name: "S2 deny: amount over NumericLimit cap",
      text: "Pay my electric bill $3,000",
      ctx: { action: "payments:bill_pay", resource: "urn:bank:utilities/electric",
             claimAmount: 3000, currency: "USD", recipientId: "utilities", geoRegion: "US" },
      expect: { decision: "deny" } },
    { name: "S3 deny: recipient not in enumerated list",
      text: "Send $200 to a gambling site",
      ctx: { action: "payments:bill_pay", resource: "urn:bank:misc/x",
             claimAmount: 200, currency: "USD", recipientId: "gambling", geoRegion: "US" },
      expect: { decision: "deny" } },
    { name: "S4 deny: geo region outside US",
      text: "Pay an EU utility $100",
      ctx: { action: "payments:bill_pay", resource: "urn:bank:utilities/eu",
             claimAmount: 100, currency: "USD", recipientId: "utilities", geoRegion: "EU" },
      expect: { decision: "deny" } },
  ];

  let passed = 0;
  for (const s of scenarios) {
    console.log(`--- ${s.name} ---`);
    const idempotencyKey = `a2a-poc-${randomUUID()}`;
    const a2a = buildA2aMessage(vc, s.text, idempotencyKey);
    const resp = await a2aReceive(a2a, s.ctx);
    const got = resp.body?.decision;
    if (assert(`decision = ${s.expect.decision}`, got === s.expect.decision, { got, body: resp.body })) passed++;
    console.log(`  audit  ${resp.body?.auditRecordId || "(none)"}\n`);
  }

  console.log(`=== ${passed}/${scenarios.length} scenarios passed ===`);
  process.exit(passed === scenarios.length ? 0 : 1);
}

main().catch((err) => { console.error("ERROR:", err.message); process.exit(2); });
