#!/usr/bin/env bash
#
# Copyright contributors to the aiagent-portable-authorization project.
# SPDX-License-Identifier: MIT
# This code is generated by AI, edited by humans

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v podman >/dev/null 2>&1 && podman compose version >/dev/null 2>&1; then
  COMPOSE=(podman compose)
else
  echo "ERROR: neither docker compose nor podman compose is available." >&2
  exit 1
fi

echo "==> Starting PortAuth issuer and engine"
"${COMPOSE[@]}" -f portauth-docker-compose.yml up -d --build

echo "==> Waiting for issuer and engine"
for _ in $(seq 1 60); do
  if curl -sf http://localhost:3100/health >/dev/null 2>&1 \
     && curl -sf http://localhost:3200/health >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

echo "==> Starting A2A receiver"
cd "$SCRIPT_DIR"
npm install
PORT=3300 ENGINE_URL=http://localhost:3200 node reference-receiver/src/server.js &
RECEIVER_PID=$!
trap 'kill "$RECEIVER_PID" >/dev/null 2>&1 || true' EXIT

for _ in $(seq 1 30); do
  if curl -sf http://localhost:3300/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "==> Running A2A allow scenario"
node reference-presenter/src/send-bill-payment.js allow

echo "==> Running A2A deny scenario"
node reference-presenter/src/send-bill-payment.js deny-amount

echo "==> Running A2A conformance checks"
npm test
