// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { Router } from "express";
import * as jose from "jose";
import { getOrCreateEngineSigningKey, getEnginePublicKeys } from "../services/engineKeyStore.js";
import {
  loadTrustedIssuerSummary,
  loadMappingProfileSummary,
  currentGovernanceRevision,
} from "../services/governanceState.js";

const router = Router();

/** Cached signed manifest, its expiry, and the revision it was built from */
let cachedManifest = null;
let cachedJws = null;
let cacheExpiresAt = 0;
let cachedRevision = -1;

export function clearGovernanceManifestCache() {
  cachedManifest = null;
  cachedJws = null;
  cacheExpiresAt = 0;
  cachedRevision = -1;
}

/**
 * /.well-known/agent-governance
 *
 * Returns a signed governance manifest declaring supported credential profiles,
 * vocabulary versions, accepted trust anchors, required context fields, and freshness metadata.
 *
 * The manifest is signed as a JWS so receivers/senders can verify authenticity.
 */
router.get("/agent-governance", async (_req, res) => {
  try {
    const now = Date.now();
    const revision = currentGovernanceRevision();

    // Return cached signed manifest if still valid AND revision unchanged
    if (cachedJws && now < cacheExpiresAt && cachedRevision === revision) {
      res.setHeader("Cache-Control", "public, max-age=3600");
      return res.json(cachedManifest);
    }

    const validUntil = new Date(now + 86400_000).toISOString(); // 24 hours

    // Plan 3: derive issuer and mapping-profile sections from persistent state
    const [issuersByTier, dbMappingProfiles] = await Promise.all([
      loadTrustedIssuerSummary(),
      loadMappingProfileSummary(),
    ]);

    const manifest = {
      version: "0.1.0",
      profile: "portable-authorization-reference",
      description: "Portable Authorization governance manifest",

      credentialProfiles: [
        {
          id: "tier1-jwt",
          format: "jwt",
          algorithms: ["ES256", "ES384"],
          requiredClaims: ["iss", "sub", "permissions", "constraints", "exp"],
          optionalClaims: ["aud", "cnf"],
        },
        {
          id: "tier2-x509-jwt",
          format: "jwt",
          algorithms: ["ES256", "ES384", "RS256"],
          requiredClaims: ["iss", "sub", "permissions", "constraints", "exp"],
          requiredHeaderParameters: ["x5c"],
          optionalClaims: ["aud", "cnf"],
          trustMechanism: "X.509 certificate chain anchored in receiver registry",
          revocationMechanism: "local revoked-certificate registry with configurable soft/hard fail policy",
        },
        {
          id: "tier3-vc-jose",
          format: "vc+jwt",
          specification: "W3C Securing Verifiable Credentials using JOSE and COSE (2025)",
          algorithms: ["ES256", "ES384", "EdDSA"],
          requiredClaims: ["iss", "sub", "vc", "exp"],
          optionalClaims: ["aud", "cnf"],
          didMethods: ["did:web", "did:key"],
          statusMechanism: "BitstringStatusList",
        },
      ],

      constraintTypes: [
        "NumericLimitConstraint",
        "TemporalWindowConstraint",
        "EnumeratedListConstraint",
        "StringPatternConstraint",
        "CumulativeLimitConstraint",
        "UsageLimitConstraint",
      ],
      statefulConstraintTypes: [
        {
          type: "CumulativeLimitConstraint",
          semantics: "transactionally reserves numeric usage against a period-scoped counter",
          idempotency: "request idempotencyKey or Idempotency-Key header",
        },
        {
          type: "UsageLimitConstraint",
          semantics: "transactionally reserves one use against a period-scoped counter",
          idempotency: "request idempotencyKey or Idempotency-Key header",
        },
      ],

      vocabularyVersion: "mvv-0.1",
      recognizedFields: {
        // MUST stay in sync with defaultMappings() in services/semanticResolver.js.
        core: [
          // Request-context attributes
          "core.amount",
          "core.currency_code",
          "core.currency",
          "core.request_time",
          "core.timestamp",
          "core.resource_id",
          "core.resource_type",
          "core.action",
          "core.workflow_id",
          "core.workflow_role",
          "core.workflow_step_id",
          "core.recipient_id",
          "core.count",
          "core.quantity",
          "core.total_budget",
          "core.geo_region",
          // Credential-derived facts (enriched via contextEnricher)
          "core.issuer_id",
          "core.subject_id",
          "core.presenter_id",
          "core.audience_id",
          "core.permission",
          "core.valid_from",
          "core.valid_until",
          "core.delegator_id",
          // Request-envelope facts
          "core.request_id",
          "core.ip_address",
        ],
        insurance: [
          "insurance.claim_amount",
          "insurance.claim_type",
          "insurance.claim_id",
          "insurance.claimAmount",
          "insurance.claimType",
          "insurance.claimId",
        ],
      },

      requiredContextFields: ["action", "resource"],
      proofOfPossession: {
        confirmationClaim: "cnf.jwk",
        requestProof: "proofOfPossession.jws",
        proofPayload: ["credentialId", "presenterId", "requestHash", "iat"],
        requestHashAlgorithm: "sha256",
      },

      acceptedTrustAnchors: {
        tier1: {
          mechanism: "JWKS",
          discoveryPattern: "{issuerUrl}/.well-known/jwks.json",
          trustedIssuers: issuersByTier[1],
        },
        tier2: {
          mechanism: "X.509",
          registryFields: ["x509_san_uri", "x509_subject", "x509_trust_anchor_pem", "x509_trust_anchor_sha256"],
          revocationPolicy: ["soft-fail", "hard-fail"],
          trustedIssuers: issuersByTier[2],
        },
        tier3: {
          mechanism: "DID",
          supportedMethods: ["did:web", "did:key"],
          trustValidation: "portauth_trusted_issuers registry with governance standing check",
          statusMechanism: "BitstringStatusList",
          trustedIssuers: issuersByTier[3],
        },
      },

      validUntil,
      cacheControl: "public, max-age=3600",

      mappingProfiles: dbMappingProfiles.length > 0 ? dbMappingProfiles : [
        {
          id: "insurance-claims-v1",
          description: "Insurance claims processing vocabulary profile",
          status: "active",
          fields: {
            "insurance.claimAmount": { localField: "claimAmount", type: "number" },
            "insurance.claimType": { localField: "claimType", type: "string" },
            "insurance.claimId": { localField: "resource", type: "string" },
            "insurance.claim_amount": { localField: "claimAmount", type: "number" },
            "insurance.claim_type": { localField: "claimType", type: "string" },
            "insurance.claim_id": { localField: "resource", type: "string" },
          },
        },
      ],
    };

    // Sign the manifest
    const { privateKey, publicJwk, kid } = await getOrCreateEngineSigningKey("governance-manifest");
    const payload = JSON.stringify(manifest, Object.keys(manifest).sort());
    const signature = await new jose.CompactSign(new TextEncoder().encode(payload))
      .setProtectedHeader({ alg: "ES256", kid })
      .sign(privateKey);

    const signedResponse = {
      ...manifest,
      proof: {
        type: "JsonWebSignature2020",
        created: new Date().toISOString(),
        verificationMethod: kid,
        jws: signature,
      },
    };

    // Cache for 1 hour or until revision changes
    cachedManifest = signedResponse;
    cachedJws = signature;
    cacheExpiresAt = now + 3600_000;
    cachedRevision = revision;

    res.setHeader("Cache-Control", "public, max-age=3600");
    return res.json(signedResponse);
  } catch (err) {
    console.error("Governance manifest error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to generate governance manifest" });
  }
});

/**
 * /.well-known/agent-governance/signing-key
 *
 * Expose the manifest signing public key so senders can verify the manifest's signature.
 */
router.get("/agent-governance/signing-key", async (_req, res) => {
  try {
    const keys = await getEnginePublicKeys("governance-manifest");
    return res.json({ keys });
  } catch (err) {
    return res.status(500).json({ error: "internal_error", message: "Failed to retrieve signing key" });
  }
});

export default router;
