#!/usr/bin/env node
/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

// Runnable two-hop delegation demo (no external services required).
//
//   customer ──VC──▶ intermediate (authorizes, mints attenuated VC) ──▶ payments
//
// Run two side-by-side scenarios against the engine's real attenuation rules:
//   • narrow  — the intermediate tightens authority  → allowed
//   • widen   — the intermediate raises the cap       → rejected (delegation_widened)
//
// Usage:  node reference-intermediate/src/demo-two-hop.js
//         npm run two-hop        (from extensions/a2a)

import { fileURLToPath } from "node:url";

import {
  EXTENSION_URI,
  buildA2aSendMessageRequest,
  buildPortAuthMetadata,
} from "portauth-a2a";
import { createPortAuthReceiver } from "portauth-a2a-receiver";

import { createIntermediateAgent } from "./intermediate.js";
import {
  createAttenuationEngineOracle,
  createInMemoryDelegatedIssuer,
  customerRootCredential,
  downstreamAgentCard,
} from "./in-memory-delegation.js";

const requestContext = {
  action: "payments:bill_pay",
  resource: "urn:bank:utilities/electric",
  claimAmount: 2400,
  currency: "USD",
  recipientId: "utilities",
  geoRegion: "US",
};

const SCENARIOS = {
  narrow: {
    label: "Intermediate tightens the cap (2500 -> 2400) and recipient set",
    expect: "allow",
    narrow: () => ({
      permissions: ["payments:bill_pay"],
      constraints: [
        { type: "NumericLimitConstraint", field: "core.amount", operator: "lte", value: 2400, currency: "USD" },
        { type: "EnumeratedListConstraint", field: "core.recipient_id", allowed: ["utilities"] },
        { type: "EnumeratedListConstraint", field: "core.geo_region", allowed: ["US"] },
      ],
    }),
  },
  widen: {
    label: "Intermediate raises the cap (2500 -> 3000)",
    expect: "deny",
    narrow: () => ({
      permissions: ["payments:bill_pay"],
      constraints: [
        { type: "NumericLimitConstraint", field: "core.amount", operator: "lte", value: 3000, currency: "USD" },
        { type: "EnumeratedListConstraint", field: "core.recipient_id", allowed: ["utilities"] },
        { type: "EnumeratedListConstraint", field: "core.geo_region", allowed: ["US"] },
      ],
    }),
  },
};

const silentLogger = { info() {}, warn() {}, error() {} };

function inboundMessage() {
  const { token } = customerRootCredential();
  return buildA2aSendMessageRequest({
    text: "Please pay my electric bill $2,400.",
    data: requestContext,
    metadata: buildPortAuthMetadata({
      credential: token,
      vcFormat: "tier1-jwt",
      presenterId: "agent:customer-finance-1",
      idempotencyKey: `bill-${Date.now()}`,
    }),
  });
}

async function runScenario(name) {
  const scenario = SCENARIOS[name];
  const downstream = createPortAuthReceiver({
    engineUrl: "http://payments-engine.demo",
    fetchImpl: createAttenuationEngineOracle(),
    logger: silentLogger,
  });
  const router = async (url, options) => {
    if (String(url).endsWith("/message:send")) {
      const r = await downstream.handleSendMessage({ headers: options.headers, body: JSON.parse(options.body) });
      return { ok: r.status >= 200 && r.status < 300, status: r.status, json: async () => r.body, text: async () => JSON.stringify(r.body) };
    }
    return { ok: false, status: 404, json: async () => ({}), text: async () => "{}" };
  };
  const intermediate = createIntermediateAgent({
    receiver: createPortAuthReceiver({ engineUrl: "http://intake-engine.demo", fetchImpl: createAttenuationEngineOracle(), logger: silentLogger }),
    fetchImpl: router,
    downstreamAgentCard: downstreamAgentCard(),
    intermediatePresenterId: "agent:bank-intake",
    issueDelegatedCredential: createInMemoryDelegatedIssuer({ narrow: scenario.narrow }),
  });

  const result = await intermediate.handleSendMessage({
    headers: { "a2a-extensions": EXTENSION_URI },
    body: inboundMessage(),
  });

  const decision = result.status === 200 ? "allow" : "deny";
  const engineError = result.body?.error?.details?.[0]?.metadata?.engineError;
  return { name, label: scenario.label, expect: scenario.expect, status: result.status, decision, engineError };
}

async function main() {
  const results = [];
  for (const name of ["narrow", "widen"]) {
    const r = await runScenario(name);
    results.push(r);
    const ok = r.decision === r.expect;
    const detail = r.engineError ? ` (${r.engineError})` : "";
    console.log(`${ok ? "[PASS]" : "[FAIL]"} ${name.padEnd(7)} expect=${r.expect.padEnd(5)} got=${r.decision} [HTTP ${r.status}]${detail}`);
    console.log(`    ${r.label}`);
  }
  const allOk = results.every((r) => r.decision === r.expect);
  console.log(allOk ? "\nTwo-hop delegation enforced: widening is rejected, narrowing is allowed." : "\nUnexpected result.");
  process.exit(allOk ? 0 : 1);
}

const isCli = process.argv[1] === fileURLToPath(import.meta.url);
if (isCli) {
  await main();
}

export { runScenario, SCENARIOS };
