/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

// Reference A2A *intermediate* agent — the producer side of N-hop delegation.
//
// A leaf receiver only consumes a delegation chain. An intermediate does both:
// it is a receiver for the inbound hop, and a presenter for the outbound hop.
// On an allowed inbound request it mints an **attenuated** delegated credential
// (narrower than the one it was handed) and forwards the task downstream,
// carrying the upstream credential in `delegationChain`. The downstream engine
// re-verifies the whole chain and rejects any link that *widens* authority
// (`delegation_widened`), so a compromised or buggy intermediate cannot grant
// more than it received.
//
// Credential minting is injected (`issueDelegatedCredential`) so the same
// orchestration runs against a real issuer in deployment and against an
// in-memory signer in tests. `createHttpDelegatedIssuer` is the production
// default: it POSTs the attenuated claims to a PortAuth issuer.

import { randomUUID } from "node:crypto";

import { EXTENSION_URI, extractPortAuthMetadata, sendWithVc } from "portauth-a2a";
import { createPortAuthReceiver, defaultRequestContextMapper } from "portauth-a2a-receiver";

/**
 * Build the claim set for an attenuated child credential from the parent's
 * claims. Pure and side-effect free. Permissions default to the parent's
 * (callers narrow them); constraints default to the parent's (callers tighten
 * them). The child is issued *by* the intermediate (`issuerId`) *to* the
 * downstream agent (`agentId`) and references the parent via `delegatedFrom`,
 * which is exactly what the engine's chain verifier checks for continuity.
 */
export function buildAttenuatedClaims(parentClaims, {
  issuerId,
  audience,
  permissions,
  constraints,
  credentialId = `urn:vc:${randomUUID()}`,
} = {}) {
  if (!issuerId) throw new Error("buildAttenuatedClaims requires issuerId (the intermediate's identity)");
  if (!audience) throw new Error("buildAttenuatedClaims requires audience (the downstream agent)");
  return {
    credentialId,
    issuerId,
    agentId: audience,
    delegatedFrom: parentClaims.credentialId,
    permissions: permissions ?? [...parentClaims.permissions],
    constraints: constraints ?? parentClaims.constraints.map((c) => ({ ...c })),
  };
}

/**
 * Decode the JSON payload of a compact JWS without verifying its signature.
 * Used only to read non-sensitive routing claims (e.g. the parent credential
 * id for `delegatedFrom`); the engine performs the authoritative verification.
 */
export function decodeJwsPayload(token) {
  const segments = String(token).split(".");
  if (segments.length < 2) throw new Error("not a compact JWS");
  const json = Buffer.from(segments[1], "base64url").toString("utf8");
  return JSON.parse(json);
}

/**
 * Production default: mint the attenuated credential at a PortAuth issuer.
 * The intermediate decides the attenuation policy (`permissions`/`constraints`,
 * or a `narrow(parentClaims)` function); the issuer signs it.
 */
export function createHttpDelegatedIssuer({
  issuerUrl,
  issuerKey,
  audience,
  permissions,
  constraints,
  narrow,
  fetchImpl = globalThis.fetch,
} = {}) {
  if (!issuerUrl) throw new Error("createHttpDelegatedIssuer requires issuerUrl");
  return async ({ inboundVc }) => {
    const parentClaims = decodeJwsPayload(inboundVc);
    const attenuation = typeof narrow === "function"
      ? narrow(parentClaims)
      : { permissions, constraints };
    const body = {
      agentId: audience,
      permissions: attenuation.permissions ?? parentClaims.permissions,
      constraints: attenuation.constraints ?? parentClaims.constraints,
      delegatedFrom: parentClaims.credentialId ?? parentClaims.jti,
    };
    const resp = await fetchImpl(`${issuerUrl}/credentials/issue`, {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        ...(issuerKey ? { Authorization: `Bearer ${issuerKey}` } : {}),
      },
      body: JSON.stringify(body),
    });
    const text = await resp.text();
    const parsed = text ? JSON.parse(text) : null;
    if (!resp.ok) {
      throw new Error(`delegated issuance failed: ${resp.status} ${JSON.stringify(parsed)}`);
    }
    return { credential: parsed.credential };
  };
}

/**
 * Create an intermediate agent that authorizes inbound A2A requests, mints an
 * attenuated delegated credential, and forwards the task to a downstream
 * receiver.
 *
 * @param {object}   opts
 * @param {string}   opts.engineUrl                 PortAuth engine for the inbound authorization hop.
 * @param {function} opts.issueDelegatedCredential  async ({ inboundVc, inboundChain, presenterId, requestContext }) => { credential }.
 * @param {string}   [opts.downstreamUrl]           Downstream receiver base URL (used for Agent Card discovery).
 * @param {object}   [opts.downstreamAgentCard]     Pre-fetched downstream Agent Card (skips discovery).
 * @param {string}   opts.intermediatePresenterId   The intermediate's own agent id (presenter to downstream).
 * @param {string}   [opts.vcFormat]                Credential profile advertised downstream.
 * @param {string}   [opts.downstreamAuthorization] Bearer header for the downstream receiver, if any.
 * @param {function} [opts.mapRequestContext]       A2A message -> PortAuth requestContext mapper.
 * @param {object}   [opts.receiver]                Pre-built inbound receiver guard (DI seam for tests).
 */
export function createIntermediateAgent({
  engineUrl,
  issueDelegatedCredential,
  downstreamUrl,
  downstreamAgentCard,
  intermediatePresenterId,
  vcFormat = "tier1-jwt",
  downstreamAuthorization,
  mapRequestContext = defaultRequestContextMapper,
  fetchImpl = globalThis.fetch,
  logger = console,
  receiver,
} = {}) {
  if (typeof issueDelegatedCredential !== "function") {
    throw new Error("issueDelegatedCredential function is required");
  }
  if (!intermediatePresenterId) throw new Error("intermediatePresenterId is required");
  if (!downstreamUrl && !downstreamAgentCard) {
    throw new Error("downstreamUrl or downstreamAgentCard is required");
  }

  const inboundReceiver = receiver
    || createPortAuthReceiver({ engineUrl, mapRequestContext, fetchImpl, logger });

  async function handleSendMessage({ headers = {}, body } = {}) {
    // Hop 1 — authorize the inbound request just like any leaf receiver. A deny
    // here short-circuits: the intermediate never mints or forwards anything.
    const inbound = await inboundReceiver.handleSendMessage({ headers, body });
    if (inbound.status !== 200) {
      return inbound;
    }

    const message = body.message;
    const portauth = extractPortAuthMetadata(message);
    const requestContext = await mapRequestContext({ message, body, portauth });

    // Mint the attenuated child credential. The upstream credential becomes the
    // next link of the chain handed downstream (root-first, leaf last).
    const minted = await issueDelegatedCredential({
      inboundVc: portauth.credential,
      inboundChain: portauth.delegationChain,
      presenterId: portauth.presenterId,
      requestContext,
    });
    const downstreamChain = [...portauth.delegationChain, portauth.credential];

    // Hop 2 — present the attenuated credential to the downstream receiver.
    return sendWithVc({
      ...(downstreamAgentCard ? { agentCard: downstreamAgentCard } : { receiverUrl: downstreamUrl }),
      credential: minted.credential,
      vcFormat,
      presenterId: intermediatePresenterId,
      text: firstText(message),
      requestContext,
      delegationChain: downstreamChain,
      idempotencyKey: portauth.idempotencyKey,
      authorization: downstreamAuthorization,
      fetchImpl,
    });
  }

  return { handleSendMessage, receiver: inboundReceiver, extensionUri: EXTENSION_URI };
}

function firstText(message = {}) {
  return (message.parts || []).find((part) => part && typeof part.text === "string")?.text || "";
}
