#!/usr/bin/env bash
#
# Copyright contributors to the aiagent-portable-authorization project.
# SPDX-License-Identifier: MIT
# This code is generated by AI, edited by humans
#
# 2-step quickstart for the portable authorization reference implementation.
#
# Usage (after `git clone`):
#   ./quickstart.sh
#
# What this does:
#   1. Brings up the full stack with docker compose or podman compose
#      (PostgreSQL, issuer service, engine service, OPA sidecar).
#   2. Waits for issuer + engine to report healthy.
#   3. Runs the end-to-end smoke flow: register issuer, issue a Tier 1
#      credential, evaluate an allow path, evaluate a deny path, issue a
#      VC-JOSE (Tier 3) credential.
#   4. Prints a PASS/FAIL summary.
#
# Total time on a warm machine: about 2 to 4 minutes (mostly image pulls
# and the first build).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

COMPOSE_FILE="portauth-docker-compose.yml"
SMOKE_SCRIPT="portauth-engine/test/e2e-smoke.sh"

if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v podman >/dev/null 2>&1 && podman compose version >/dev/null 2>&1; then
  COMPOSE=(podman compose)
else
  echo "ERROR: neither 'docker compose' nor 'podman compose' is available." >&2
  echo "       Install Docker Desktop (https://docs.docker.com/get-docker/)" >&2
  echo "       or Podman 5+ (https://podman.io/getting-started/installation)" >&2
  exit 1
fi

echo "==> Using compose runtime: ${COMPOSE[*]}"
echo "==> Resetting any prior stack so the demo starts from a clean state..."
"${COMPOSE[@]}" -f "$COMPOSE_FILE" down -v >/dev/null 2>&1 || true

echo "==> Bringing up the stack (postgres, issuer, engine, opa)..."
"${COMPOSE[@]}" -f "$COMPOSE_FILE" up -d --build

echo "==> Waiting for services to report healthy..."
ready=0
for i in $(seq 1 60); do
  if curl -sf http://localhost:3100/health >/dev/null 2>&1 \
     && curl -sf http://localhost:3200/health >/dev/null 2>&1; then
    ready=1
    echo "    issuer + engine are up"
    break
  fi
  sleep 2
done

if [[ "$ready" -ne 1 ]]; then
  echo "ERROR: services did not become healthy within 120 seconds." >&2
  echo "       Dumping recent logs:" >&2
  "${COMPOSE[@]}" -f "$COMPOSE_FILE" logs --tail=200 >&2 || true
  exit 1
fi

echo
echo "==> Running end-to-end smoke flow..."
echo
ISSUER_URL=http://localhost:3100 \
ENGINE_URL=http://localhost:3200 \
ISSUER_ID_FOR_ENGINE=http://portauth-issuer:3100 \
ISSUER_JWKS_URI=http://portauth-issuer:3100/.well-known/jwks.json \
  bash "$SMOKE_SCRIPT"

echo
echo "==> Done. Services are still running. To stop them:"
echo "    ${COMPOSE[*]} -f $COMPOSE_FILE down -v"
