// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { Router } from "express";
import { issueCredential, revokeCredential, introspectCredential } from "../services/credentialIssuer.js";
import { issueVcCredential } from "../services/vcCredentialIssuer.js";
import { issueX509Credential } from "../services/x509CredentialIssuer.js";
import { requireAdminAuth } from "../middleware/auth.js";
import { validateBody } from "../middleware/validation.js";
import issueSchema from "../schemas/issue-request.json" with { type: "json" };

const router = Router();

// ── POST /credentials/issue ─────────────────────────────────────────
router.post("/issue", requireAdminAuth, validateBody(issueSchema), async (req, res) => {
  try {
    const result = await issueCredential(req.body);
    return res.status(201).json(result);
  } catch (err) {
    if (err.code === "ttl_exceeded") {
      return res.status(400).json({ error: "validation_error", message: err.message });
    }
    console.error("Issue credential error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to issue credential" });
  }
});

// ── POST /credentials/issue-vc ──────────────────────────────────────
// Issue a W3C Verifiable Credential secured with JOSE/JWS (vc+jwt)
// Same authorization payload, different container format
router.post("/issue-vc", requireAdminAuth, validateBody(issueSchema), async (req, res) => {
  try {
    const result = await issueVcCredential(req.body);
    return res.status(201).json(result);
  } catch (err) {
    if (err.code === "ttl_exceeded") {
      return res.status(400).json({ error: "validation_error", message: err.message });
    }
    if (err.code === "configuration_error") {
      return res.status(500).json({ error: "configuration_error", message: err.message });
    }
    console.error("Issue VC credential error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to issue VC credential" });
  }
});

// ── POST /credentials/issue-x509 ───────────────────────────────────
// Issue a Tier 2 JWT secured by an X.509 certificate chain in the x5c header.
router.post("/issue-x509", requireAdminAuth, validateBody(issueSchema), async (req, res) => {
  try {
    const result = await issueX509Credential(req.body);
    return res.status(201).json(result);
  } catch (err) {
    if (err.code === "ttl_exceeded") {
      return res.status(400).json({ error: "validation_error", message: err.message });
    }
    if (err.code === "configuration_error") {
      return res.status(500).json({ error: "configuration_error", message: err.message });
    }
    console.error("Issue X.509 credential error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to issue X.509 credential" });
  }
});

// ── POST /credentials/revoke ────────────────────────────────────────
router.post("/revoke", requireAdminAuth, async (req, res) => {
  const { credentialId, reason } = req.body || {};
  if (!credentialId) {
    return res.status(400).json({ error: "validation_error", message: "Missing required field: credentialId" });
  }
  try {
    await revokeCredential(credentialId, reason);
    return res.status(200).json({ credentialId, revoked: true });
  } catch (err) {
    if (err.code === "not_found") {
      return res.status(404).json({ error: "not_found", message: err.message });
    }
    console.error("Revoke credential error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to revoke credential" });
  }
});

// ── POST /credentials/introspect ────────────────────────────────────
// Token introspection (RFC 7662 inspired) for Tier 1 revocation checks
router.post("/introspect", async (req, res) => {
  const { credentialId } = req.body || {};
  if (!credentialId) {
    return res.status(400).json({ error: "validation_error", message: "Missing required field: credentialId" });
  }
  try {
    const result = await introspectCredential(credentialId);
    if (!result) {
      return res.status(200).json({ active: false });
    }
    return res.status(200).json(result);
  } catch (err) {
    console.error("Introspect error:", err);
    return res.status(500).json({ error: "internal_error", message: "Introspection failed" });
  }
});

export default router;
