// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { Router } from "express";
import { getPublicKeys } from "../services/keyManager.js";
import { buildStatusListCredential } from "../services/statusListPublisher.js";

const router = Router();

// ── GET /.well-known/jwks.json ──────────────────────────────────────
// Standard JWKS endpoint so receivers can fetch issuer's public keys
router.get("/jwks.json", async (_req, res) => {
  try {
    const keys = await getPublicKeys();
    res.setHeader("Cache-Control", "public, max-age=300");
    return res.json({ keys });
  } catch (err) {
    console.error("JWKS error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to retrieve keys" });
  }
});

// ── GET /.well-known/status-list/:purpose ────────────────────────────
// Publishes the issuer's current Bitstring Status List as a VC-shaped JSON document.
router.get("/status-list/:purpose", async (req, res) => {
  try {
    const credential = await buildStatusListCredential(req.params.purpose);
    res.setHeader("Cache-Control", "public, max-age=60");
    return res.json(credential);
  } catch (err) {
    if (err.code === "configuration_error") {
      return res.status(500).json({ error: "configuration_error", message: err.message });
    }
    console.error("Status list error:", err);
    return res.status(500).json({ error: "internal_error", message: "Failed to publish status list" });
  }
});

export default router;
