-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Portable Authorization — Issuer-side tables
-- All tables prefixed with portauth_ to avoid collision with existing policy-engine tables

BEGIN;

-- ── Signing keys ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portauth_signing_keys (
  kid         TEXT PRIMARY KEY,               -- key ID (URI-safe)
  algorithm   TEXT NOT NULL DEFAULT 'ES256',
  public_jwk  JSONB NOT NULL,                 -- JWK public key
  private_jwk JSONB NOT NULL,                 -- JWK private key (encrypted at rest via PG)
  active      BOOLEAN NOT NULL DEFAULT TRUE,  -- only active keys are used for signing
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rotated_at  TIMESTAMPTZ                     -- set when key is deactivated
);

CREATE INDEX IF NOT EXISTS idx_portauth_signing_keys_active ON portauth_signing_keys (active) WHERE active = TRUE;

-- ── Issued credentials ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portauth_issued_credentials (
  credential_id  TEXT PRIMARY KEY,            -- jti (urn:uuid:...)
  issuer_id      TEXT NOT NULL,               -- iss claim
  agent_id       TEXT NOT NULL,               -- sub claim
  audience       TEXT,                        -- aud claim
  permissions    JSONB NOT NULL,              -- ["domain:action", ...]
  constraints    JSONB NOT NULL,              -- array of typed constraint objects
  valid_from     TIMESTAMPTZ NOT NULL,
  valid_until    TIMESTAMPTZ NOT NULL,
  kid            TEXT NOT NULL REFERENCES portauth_signing_keys(kid),
  revoked        BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at     TIMESTAMPTZ,
  revoke_reason  TEXT,
  issued_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portauth_creds_agent   ON portauth_issued_credentials (agent_id);
CREATE INDEX IF NOT EXISTS idx_portauth_creds_issuer  ON portauth_issued_credentials (issuer_id);
CREATE INDEX IF NOT EXISTS idx_portauth_creds_revoked ON portauth_issued_credentials (revoked) WHERE revoked = TRUE;

COMMIT;
