-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Portable Authorization — Engine-side (receiver/enforcement) tables

BEGIN;

-- ── Trusted issuer registry ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portauth_trusted_issuers (
  id                      SERIAL PRIMARY KEY,
  issuer_id               TEXT NOT NULL UNIQUE,     -- JWKS URI, OIDC issuer URL, or DID
  trust_tier              INTEGER NOT NULL DEFAULT 1 CHECK (trust_tier IN (1, 2, 3)),
  trusted_for_permissions JSONB NOT NULL,            -- ["damage_assessment:read", ...]
  label                   TEXT,                      -- human-readable name
  jwks_uri                TEXT,                      -- explicit JWKS URI (Tier 1)
  active                  BOOLEAN NOT NULL DEFAULT TRUE,
  added_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portauth_issuers_issuer_id ON portauth_trusted_issuers (issuer_id);

-- ── Local policy (receiver-side constraints) ────────────────────────
CREATE TABLE IF NOT EXISTS portauth_local_policies (
  id                  SERIAL PRIMARY KEY,
  name                TEXT NOT NULL,
  description         TEXT,
  target_permissions  JSONB,                        -- null = applies to all permissions
  constraints         JSONB NOT NULL,               -- same typed constraint objects as credentials
  active              BOOLEAN NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Delegation configuration ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portauth_delegation_config (
  key    TEXT PRIMARY KEY,
  value  TEXT NOT NULL
);

INSERT INTO portauth_delegation_config (key, value) VALUES
  ('max_depth', '5'),
  ('require_attenuation_proof', 'true')
ON CONFLICT (key) DO NOTHING;

-- ── Audit records ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portauth_audit_records (
  id                   TEXT PRIMARY KEY,             -- uuid
  credential_id        TEXT,
  agent_id             TEXT,
  issuer_id            TEXT,
  trust_tier           INTEGER,
  action               TEXT,
  resource             TEXT,
  request_context      JSONB,                        -- full request context (redactable in future)
  verification_result  JSONB,                        -- {valid, reason, checks: {...}}
  permission_match     JSONB,                        -- {matched, requested, granted}
  constraint_results   JSONB,                        -- [{type, field, expected, actual, pass}]
  local_policy_applied BOOLEAN DEFAULT FALSE,
  local_policy_detail  JSONB,                        -- which local policy restricted
  delegation_depth     INTEGER DEFAULT 0,
  decision             TEXT NOT NULL CHECK (decision IN ('allow', 'deny')),
  error_code           TEXT,                         -- null on allow
  http_status          INTEGER NOT NULL,
  signature            TEXT,                         -- base64url signature over record
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portauth_audit_credential ON portauth_audit_records (credential_id);
CREATE INDEX IF NOT EXISTS idx_portauth_audit_agent      ON portauth_audit_records (agent_id);
CREATE INDEX IF NOT EXISTS idx_portauth_audit_decision   ON portauth_audit_records (decision);
CREATE INDEX IF NOT EXISTS idx_portauth_audit_created    ON portauth_audit_records (created_at);

COMMIT;
