-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Portable Authorization — Semantic mapping profiles (BR-9)

BEGIN;

CREATE TABLE IF NOT EXISTS portauth_mapping_profiles (
  id              SERIAL PRIMARY KEY,
  profile_id      TEXT NOT NULL,                -- e.g., "insurance-claims-v1"
  semantic_field  TEXT NOT NULL,                 -- e.g., "core.amount"
  local_field     TEXT NOT NULL,                 -- e.g., "claimAmount"
  field_type      TEXT NOT NULL DEFAULT 'string', -- "string", "number", "boolean"
  active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(profile_id, semantic_field)
);

-- Insert default MVV + insurance profile mappings
INSERT INTO portauth_mapping_profiles (profile_id, semantic_field, local_field, field_type) VALUES
  ('mvv-core', 'core.amount', 'claimAmount', 'number'),
  ('mvv-core', 'core.currency', 'currency', 'string'),
  ('mvv-core', 'core.timestamp', 'timestamp', 'string'),
  ('insurance-claims-v1', 'insurance.claimAmount', 'claimAmount', 'number'),
  ('insurance-claims-v1', 'insurance.claimType', 'claimType', 'string'),
  ('insurance-claims-v1', 'insurance.claimId', 'resource', 'string')
ON CONFLICT (profile_id, semantic_field) DO NOTHING;

COMMIT;
