-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Portable Authorization — VC/DID support (Tier 3 Phase 1: VC-JOSE with did:web and did:key)

BEGIN;

-- ── Extend trusted issuers with VC/DID metadata ────────────────────
ALTER TABLE portauth_trusted_issuers
  ADD COLUMN IF NOT EXISTS did_method        TEXT,           -- 'web', 'key', or NULL for Tier 1
  ADD COLUMN IF NOT EXISTS governance_domain TEXT,           -- e.g. 'insurance', 'aerospace'
  ADD COLUMN IF NOT EXISTS governance_status TEXT DEFAULT 'active'
    CHECK (governance_status IN ('active', 'suspended', 'revoked')),
  ADD COLUMN IF NOT EXISTS status_list_url   TEXT,           -- issuer's Bitstring Status List endpoint
  ADD COLUMN IF NOT EXISTS metadata          JSONB;          -- extensible issuer metadata

-- ── DID document cache ──────────────────────────────────────────────
-- Same pattern as JWKS cache but for resolved DID documents
CREATE TABLE IF NOT EXISTS portauth_did_cache (
  did             TEXT PRIMARY KEY,
  did_document    JSONB NOT NULL,
  resolved_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_portauth_did_cache_expires ON portauth_did_cache (expires_at);

-- ── Credential status tracking (Bitstring Status List) ──────────────
-- Tracks status list entries for VC credentials issued by this system
CREATE TABLE IF NOT EXISTS portauth_credential_status (
  credential_id       TEXT PRIMARY KEY REFERENCES portauth_issued_credentials(credential_id),
  status_list_url     TEXT NOT NULL,          -- URL of the status list credential
  status_list_index   INTEGER NOT NULL,       -- bit index within the status list
  status_purpose      TEXT NOT NULL DEFAULT 'revocation'
    CHECK (status_purpose IN ('revocation', 'suspension')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Status list cache (receiver-side) ───────────────────────────────
-- Cache fetched Bitstring Status Lists with TTL
CREATE TABLE IF NOT EXISTS portauth_status_list_cache (
  status_list_url  TEXT PRIMARY KEY,
  encoded_list     TEXT NOT NULL,              -- base64url-encoded bitstring
  valid_from       TIMESTAMPTZ,
  valid_until      TIMESTAMPTZ,
  fetched_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at       TIMESTAMPTZ NOT NULL        -- cache TTL
);

CREATE INDEX IF NOT EXISTS idx_portauth_status_list_expires ON portauth_status_list_cache (expires_at);

-- ── Extend issued credentials for VC format ─────────────────────────
ALTER TABLE portauth_issued_credentials
  ADD COLUMN IF NOT EXISTS format             TEXT NOT NULL DEFAULT 'jwt'
    CHECK (format IN ('jwt', 'vc-jose')),
  ADD COLUMN IF NOT EXISTS status_list_index  INTEGER,       -- bit index if VC with status list
  ADD COLUMN IF NOT EXISTS did_issuer_id      TEXT;           -- DID-based issuer identity (if different from iss URL)

COMMIT;
