-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Portable Authorization — Engine-side signing keys for audit and governance artifacts

BEGIN;

CREATE TABLE IF NOT EXISTS portauth_engine_signing_keys (
  kid         TEXT PRIMARY KEY,
  purpose     TEXT NOT NULL CHECK (purpose IN ('audit', 'governance-manifest')),
  algorithm   TEXT NOT NULL DEFAULT 'ES256',
  public_jwk  JSONB NOT NULL,
  private_jwk JSONB NOT NULL,
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rotated_at  TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portauth_engine_signing_keys_active_purpose
  ON portauth_engine_signing_keys (purpose)
  WHERE active = TRUE;

COMMIT;
