-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Portable Authorization — governed mapping-profile metadata and MVV aliases

BEGIN;

ALTER TABLE portauth_mapping_profiles
  ADD COLUMN IF NOT EXISTS trusted BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS valid_until TIMESTAMPTZ;

INSERT INTO portauth_mapping_profiles (profile_id, semantic_field, local_field, field_type) VALUES
  ('mvv-core', 'core.currency_code', 'currency', 'string'),
  ('mvv-core', 'core.request_time', 'timestamp', 'string'),
  ('mvv-core', 'core.resource_id', 'resource', 'string'),
  ('mvv-core', 'core.action', 'action', 'string'),
  ('mvv-core', 'core.workflow_id', 'workflowId', 'string'),
  ('mvv-core', 'core.recipient_id', 'recipientId', 'string'),
  ('mvv-core', 'core.count', 'count', 'number'),
  ('mvv-core', 'core.quantity', 'quantity', 'number'),
  ('insurance-claims-v1', 'insurance.claim_amount', 'claimAmount', 'number'),
  ('insurance-claims-v1', 'insurance.claim_type', 'claimType', 'string'),
  ('insurance-claims-v1', 'insurance.claim_id', 'resource', 'string')
ON CONFLICT (profile_id, semantic_field) DO NOTHING;

COMMIT;
