-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans

-- Plan 6: synchronous audit signing
-- Adds a signed_at column so we can distinguish "row exists but not yet signed"
-- from "row signed at time T".

BEGIN;

ALTER TABLE portauth_audit_records
  ADD COLUMN IF NOT EXISTS signed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_portauth_audit_unsigned
  ON portauth_audit_records (created_at)
  WHERE signature IS NULL;

COMMIT;
