-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans
--
-- Migration 009: Revocation hardening (Plan 1)
--   * Per-issuer revocation mechanism precedence
--   * Per-issuer revocation failure mode override
--   * OCSP and CRL response caches (table scaffolding; client impl is incremental)

ALTER TABLE portauth_trusted_issuers
  ADD COLUMN IF NOT EXISTS revocation_mechanism TEXT
    CHECK (revocation_mechanism IN ('none', 'introspection', 'statuslist', 'ocsp', 'crl'));

ALTER TABLE portauth_trusted_issuers
  ADD COLUMN IF NOT EXISTS revocation_failure_mode TEXT
    CHECK (revocation_failure_mode IN ('open', 'closed'));

ALTER TABLE portauth_trusted_issuers
  ADD COLUMN IF NOT EXISTS revocation_timeout_ms INTEGER;

ALTER TABLE portauth_trusted_issuers
  ADD COLUMN IF NOT EXISTS revocation_retries INTEGER;

CREATE TABLE IF NOT EXISTS portauth_x509_ocsp_cache (
  id                 BIGSERIAL PRIMARY KEY,
  fingerprint_sha256 TEXT NOT NULL,
  responder_url      TEXT NOT NULL,
  status             TEXT NOT NULL CHECK (status IN ('good', 'revoked', 'unknown')),
  reason             TEXT,
  this_update        TIMESTAMPTZ NOT NULL,
  next_update        TIMESTAMPTZ,
  fetched_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  raw_response_b64   TEXT,
  UNIQUE (fingerprint_sha256, responder_url)
);

CREATE INDEX IF NOT EXISTS idx_portauth_ocsp_fingerprint ON portauth_x509_ocsp_cache (fingerprint_sha256);
CREATE INDEX IF NOT EXISTS idx_portauth_ocsp_next_update ON portauth_x509_ocsp_cache (next_update);

CREATE TABLE IF NOT EXISTS portauth_x509_crl_cache (
  id                BIGSERIAL PRIMARY KEY,
  distribution_url  TEXT NOT NULL UNIQUE,
  this_update       TIMESTAMPTZ NOT NULL,
  next_update       TIMESTAMPTZ,
  fetched_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  raw_crl_b64       TEXT NOT NULL,
  issuer_dn         TEXT
);

CREATE TABLE IF NOT EXISTS portauth_x509_crl_entries (
  id                  BIGSERIAL PRIMARY KEY,
  crl_id              BIGINT NOT NULL REFERENCES portauth_x509_crl_cache(id) ON DELETE CASCADE,
  serial_number_hex   TEXT NOT NULL,
  revocation_date     TIMESTAMPTZ NOT NULL,
  reason              TEXT,
  UNIQUE (crl_id, serial_number_hex)
);

CREATE INDEX IF NOT EXISTS idx_portauth_crl_entries_serial ON portauth_x509_crl_entries (serial_number_hex);
