-- Copyright contributors to the aiagent-portable-authorization project.
-- SPDX-License-Identifier: MIT
-- This code is generated by AI, edited by humans
--
-- Migration 011: Multi-principal workflow composition (Plan 7)

CREATE TABLE IF NOT EXISTS portauth_workflow_policies (
  id              TEXT PRIMARY KEY,
  version         TEXT NOT NULL,
  combinator      TEXT NOT NULL CHECK (combinator IN ('requireAll', 'requireAny', 'threshold')),
  threshold_n     INTEGER,
  required_roles  JSONB NOT NULL,
  description     TEXT,
  active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portauth_workflow_policies_active
  ON portauth_workflow_policies (active);

ALTER TABLE portauth_audit_records
  ADD COLUMN IF NOT EXISTS workflow_policy_id TEXT;
ALTER TABLE portauth_audit_records
  ADD COLUMN IF NOT EXISTS workflow_sub_audit_ids JSONB;
