// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { v4 as uuidv4 } from "uuid";
import * as jose from "jose";
import { getPool } from "../db/pool.js";
import { getOrCreateEngineSigningKey, getEnginePublicKeys, getEngineSigningKeyByKid } from "./engineKeyStore.js";

/**
 * Deterministic JSON serialization with recursively sorted object keys.
 */
function stableStringify(value) {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`;
}

function buildCanonicalRecord(id, record) {
  return {
    id,
    credentialId: record.credentialId || null,
    agentId: record.agentId || null,
    issuerId: record.issuerId || null,
    trustTier: record.trustTier || null,
    action: record.action || null,
    resource: record.resource || null,
    requestContext: record.requestContext || null,
    verificationResult: record.verificationResult || null,
    permissionMatch: record.permissionMatch || null,
    constraintResults: record.constraintResults || null,
    localPolicyApplied: record.localPolicyApplied || false,
    localPolicyDetail: record.localPolicyDetail || null,
    delegationDepth: record.delegationDepth || 0,
    decision: record.decision,
    errorCode: record.errorCode || null,
    httpStatus: record.httpStatus,
    workflowPolicyId: record.workflowPolicyId || null,
    workflowSubAuditIds: record.workflowSubAuditIds || null,
  };
}

async function signCanonicalRecord(id, record) {
  const { privateKey, kid } = await getOrCreateEngineSigningKey("audit");
  const canonicalRecord = {
    ...buildCanonicalRecord(id, record),
    signedAt: new Date().toISOString(),
  };
  const payload = stableStringify(canonicalRecord);
  const jws = await new jose.CompactSign(new TextEncoder().encode(payload))
    .setProtectedHeader({ alg: "ES256", kid })
    .sign(privateKey);
  return { jws, signedAt: canonicalRecord.signedAt };
}

/**
 * Create, sign, and persist an audit record in a single transaction. The
 * signature is computed inline so every row written is verifiable from the
 * moment the response is returned (Plan 6).
 *
 * @param {object} record - audit record fields
 * @returns {string} auditRecordId
 */
export async function createAuditRecord(record) {
  const id = uuidv4();
  const pool = getPool();

  let signature = null;
  let signedAt = null;
  try {
    const signed = await signCanonicalRecord(id, record);
    signature = signed.jws;
    signedAt = signed.signedAt;
  } catch (err) {
    // Signing must succeed before the row is written. Callers translate this
    // into HTTP 500 audit_signing_failed.
    const wrapped = new Error(`audit_signing_failed: ${err.message}`);
    wrapped.cause = err;
    throw wrapped;
  }

  await pool.query(
    `INSERT INTO portauth_audit_records
       (id, credential_id, agent_id, issuer_id, trust_tier, action, resource,
        request_context, verification_result, permission_match, constraint_results,
        local_policy_applied, local_policy_detail, delegation_depth,
        decision, error_code, http_status, signature, signed_at,
        workflow_policy_id, workflow_sub_audit_ids, created_at)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,NOW())`,
    [
      id,
      record.credentialId || null,
      record.agentId || null,
      record.issuerId || null,
      record.trustTier || null,
      record.action || null,
      record.resource || null,
      JSON.stringify(record.requestContext || null),
      JSON.stringify(record.verificationResult || null),
      JSON.stringify(record.permissionMatch || null),
      JSON.stringify(record.constraintResults || null),
      record.localPolicyApplied || false,
      JSON.stringify(record.localPolicyDetail || null),
      record.delegationDepth || 0,
      record.decision,
      record.errorCode || null,
      record.httpStatus,
      signature,
      signedAt,
      record.workflowPolicyId || null,
      record.workflowSubAuditIds ? JSON.stringify(record.workflowSubAuditIds) : null,
    ]
  );

  return id;
}

/**
 * Sign any audit rows that are missing a signature. Intended to be called once
 * at engine startup so a crash window between insert and signature update on a
 * previous run is healed before the engine starts serving traffic.
 */
let lastResignSweepAt = null;
let lastResignSweepCount = 0;

export async function resignUnsignedAuditRecords(options = {}) {
  const maxRows = options.maxRows
    || parseInt(process.env.PORTAUTH_AUDIT_RESIGN_MAX_ROWS || "10000", 10);
  const pool = getPool();
  let resigned = 0;

  while (resigned < maxRows) {
    const batchSize = Math.min(100, maxRows - resigned);
    const { rows } = await pool.query(
      `SELECT id, credential_id, agent_id, issuer_id, trust_tier, action, resource,
              request_context, verification_result, permission_match, constraint_results,
              local_policy_applied, local_policy_detail, delegation_depth,
              decision, error_code, http_status,
              workflow_policy_id, workflow_sub_audit_ids
       FROM portauth_audit_records
       WHERE signature IS NULL
       ORDER BY created_at
       LIMIT $1`,
      [batchSize]
    );
    if (rows.length === 0) break;

    for (const row of rows) {
      const record = {
        credentialId: row.credential_id,
        agentId: row.agent_id,
        issuerId: row.issuer_id,
        trustTier: row.trust_tier,
        action: row.action,
        resource: row.resource,
        requestContext: row.request_context,
        verificationResult: row.verification_result,
        permissionMatch: row.permission_match,
        constraintResults: row.constraint_results,
        localPolicyApplied: row.local_policy_applied,
        localPolicyDetail: row.local_policy_detail,
        delegationDepth: row.delegation_depth,
        decision: row.decision,
        errorCode: row.error_code,
        httpStatus: row.http_status,
        workflowPolicyId: row.workflow_policy_id,
        workflowSubAuditIds: row.workflow_sub_audit_ids,
      };
      const { jws, signedAt } = await signCanonicalRecord(row.id, record);
      await pool.query(
        `UPDATE portauth_audit_records SET signature = $1, signed_at = $2 WHERE id = $3`,
        [jws, signedAt, row.id]
      );
      resigned += 1;
    }
  }

  lastResignSweepAt = new Date().toISOString();
  lastResignSweepCount = resigned;
  return { resigned };
}

export async function getAuditHealth() {
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT COUNT(*)::int AS n
     FROM portauth_audit_records
     WHERE signature IS NULL AND created_at < NOW() - INTERVAL '60 seconds'`
  );
  return {
    unsignedOlderThan60s: rows[0]?.n ?? 0,
    lastResignSweepAt,
    lastResignSweepCount,
  };
}

/**
 * Retrieve an audit record by ID.
 */
export async function getAuditRecord(id) {
  const pool = getPool();
  const { rows } = await pool.query(`SELECT * FROM portauth_audit_records WHERE id = $1`, [id]);
  return rows[0] || null;
}

/**
 * Verify an audit record's signature.
 */
export async function verifyAuditRecord(id) {
  const record = await getAuditRecord(id);
  if (!record) return { verified: false, error: "Audit record not found" };
  if (!record.signature) return { verified: false, error: "Audit record not yet signed" };

  try {
    const protectedHeader = jose.decodeProtectedHeader(record.signature);
    const keyRecord = await getEngineSigningKeyByKid(protectedHeader.kid);
    if (!keyRecord) {
      return { verified: false, error: `Unknown audit signing key: ${protectedHeader.kid}` };
    }

    const publicKey = await jose.importJWK(keyRecord.publicJwk, keyRecord.algorithm);
    const { payload } = await jose.compactVerify(record.signature, publicKey);
    const decoded = JSON.parse(new TextDecoder().decode(payload));

    const expectedRecord = buildCanonicalRecord(id, {
      credentialId: record.credential_id,
      agentId: record.agent_id,
      issuerId: record.issuer_id,
      trustTier: record.trust_tier,
      action: record.action,
      resource: record.resource,
      requestContext: record.request_context,
      verificationResult: record.verification_result,
      permissionMatch: record.permission_match,
      constraintResults: record.constraint_results,
      localPolicyApplied: record.local_policy_applied,
      localPolicyDetail: record.local_policy_detail,
      delegationDepth: record.delegation_depth,
      decision: record.decision,
      errorCode: record.error_code,
      httpStatus: record.http_status,
    });

    const { signedAt, ...signedRecordWithoutTimestamp } = decoded;
    const match = stableStringify(expectedRecord) === stableStringify(signedRecordWithoutTimestamp);
    if (!match) {
      return {
        verified: false,
        error: "Audit record content does not match signed payload",
        signedFields: decoded,
        signedAt,
      };
    }
    return {
      verified: true,
      signedFields: decoded,
      recordDecision: record.decision,
      signedAt,
      match: true,
    };
  } catch (err) {
    return { verified: false, error: `Signature verification failed: ${err.message}` };
  }
}

/**
 * Get the audit signing public key (for external verifiers).
 */
export async function getAuditPublicKey() {
  return getEnginePublicKeys("audit");
}
