// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

/**
 * Constraint Evaluation Engine
 *
 * Evaluates the four core constraint types against a request context.
 * All constraint types use fail-closed semantics:
 *   - Unknown type → constraint_unknown
 *   - Missing context field → context_field_missing
 *
 * Supports semantic field resolution (BR-9): constraint fields that use
 * semantic identifiers (e.g., "core.amount") are resolved to local context
 * fields via governed mapping profiles before evaluation.
 *
 * Each evaluator returns { pass: boolean, detail: object }
 */

import { resolveSemanticField } from "./semanticResolver.js";
import { isStatefulConstraint } from "./statefulAuthorizer.js";
import logger from "./logger.js";

const EVALUATORS = {
  NumericLimitConstraint: evaluateNumericLimit,
  TemporalWindowConstraint: evaluateTemporalWindow,
  EnumeratedListConstraint: evaluateEnumeratedList,
  StringPatternConstraint: evaluateStringPattern,
};

/**
 * Evaluate all constraints against a request context.
 *
 * @param {object[]} constraints - array of typed constraint objects from the credential
 * @param {object} context - the request context (action, resource, domain fields)
 * @returns {Promise<{ pass: boolean, results: object[], error?: string }>}
 */
export async function evaluateConstraints(constraints, context) {
  const results = [];
  logger.info({ msg: "⚙️ STORY STEP 3: Evaluation Engine (Layer 3)", constraintCount: constraints.length });

  for (const constraint of constraints) {
    const evaluator = EVALUATORS[constraint.type];

    if (!evaluator) {
      if (isStatefulConstraint(constraint)) {
        results.push({
          type: constraint.type,
          field: constraint.field,
          pass: true,
          deferred: true,
          detail: "Stateful constraint deferred to transactional authorization gate",
        });
        continue;
      }

      results.push({
        type: constraint.type,
        field: constraint.field,
        pass: false,
        error: "constraint_unknown",
        detail: `Unknown constraint type: ${constraint.type}`,
      });
      continue;
    }

    const result = await evaluator(constraint, context);
    logger.info({ 
      msg: `  🔍 Evaluating ${constraint.type}`, 
      field: constraint.field,
      pass: result.pass,
      expected: result.expected,
      actual: result.actual
    });
    results.push({
      type: constraint.type,
      field: constraint.field,
      ...result,
    });
  }

  const allPass = results.every(r => r.pass);
  const firstFailure = results.find(r => !r.pass);

  return {
    pass: allPass,
    results,
    error: firstFailure ? (firstFailure.error || "constraint_failed") : null,
  };
}

// ── NumericLimitConstraint ──────────────────────────────────────────

async function evaluateNumericLimit(constraint, context) {
  const { field, operator, value } = constraint;
  const resolved = await resolveField(field, context);

  if (resolved.value === undefined || resolved.value === null) {
    return { pass: false, error: resolved.errorCode || "context_field_missing", expected: value, actual: null, detail: resolved.error || `Field '${field}' not found in context` };
  }

  const numActual = Number(resolved.value);
  if (isNaN(numActual)) {
    return { pass: false, error: "constraint_failed", expected: value, actual: resolved.value, detail: `Field '${field}' is not numeric` };
  }

  const ops = {
    eq: (a, b) => a === b,
    lt: (a, b) => a < b,
    lte: (a, b) => a <= b,
    gt: (a, b) => a > b,
    gte: (a, b) => a >= b,
  };

  const opFn = ops[operator];
  if (!opFn) {
    return { pass: false, error: "constraint_failed", expected: value, actual: numActual, detail: `Unknown operator: ${operator}` };
  }

  const pass = opFn(numActual, value);
  return { pass, expected: `${operator} ${value}`, actual: numActual, detail: pass ? "Numeric limit satisfied" : `${numActual} does not satisfy ${operator} ${value}` };
}

// ── TemporalWindowConstraint ────────────────────────────────────────

async function evaluateTemporalWindow(constraint, context) {
  const { field, validFrom, validUntil, timezone, daysOfWeek } = constraint;

  // Get the timestamp to evaluate — from field or from context.timestamp
  let timestamp;
  if (field && field !== "timestamp") {
    const resolved = await resolveField(field, context);
    if (resolved.value === undefined || resolved.value === null) {
      return { pass: false, error: resolved.errorCode || "context_field_missing", actual: null, detail: resolved.error || `Field '${field}' not found in context` };
    }
    timestamp = new Date(resolved.value);
  } else {
    timestamp = context.timestamp ? new Date(context.timestamp) : new Date();
  }

  if (isNaN(timestamp.getTime())) {
    return { pass: false, error: "constraint_failed", actual: null, detail: "Invalid timestamp" };
  }

  // Convert to the specified timezone for time-of-day and day-of-week checks
  const tz = timezone || "UTC";
  let localParts;
  try {
    const formatter = new Intl.DateTimeFormat("en-US", {
      timeZone: tz,
      hour: "numeric", minute: "numeric", hour12: false,
      weekday: "short",
      year: "numeric", month: "2-digit", day: "2-digit",
    });
    const parts = Object.fromEntries(formatter.formatToParts(timestamp).map(p => [p.type, p.value]));
    localParts = parts;
  } catch (err) {
    return { pass: false, error: "constraint_failed", detail: `Invalid timezone: ${tz}` };
  }

  // Day of week check
  if (daysOfWeek && daysOfWeek.length > 0) {
    const dayMap = { Mon: "Mon", Tue: "Tue", Wed: "Wed", Thu: "Thu", Fri: "Fri", Sat: "Sat", Sun: "Sun" };
    // Intl returns full day name sometimes, map them
    const intlDayMap = { Monday: "Mon", Tuesday: "Tue", Wednesday: "Wed", Thursday: "Thu", Friday: "Fri", Saturday: "Sat", Sunday: "Sun" };
    const rawDay = localParts.weekday;
    const day = dayMap[rawDay] || intlDayMap[rawDay] || rawDay;

    if (!daysOfWeek.includes(day)) {
      return { pass: false, expected: daysOfWeek, actual: day, detail: `Day ${day} not in allowed days: ${daysOfWeek.join(", ")}` };
    }
  }

  // Time of day check
  if (validFrom || validUntil) {
    const hour = parseInt(localParts.hour, 10);
    const minute = parseInt(localParts.minute, 10);
    const currentMinutes = hour * 60 + minute;

    if (validFrom) {
      const [fh, fm] = validFrom.split(":").map(Number);
      const fromMinutes = fh * 60 + (fm || 0);
      if (currentMinutes < fromMinutes) {
        return { pass: false, expected: `>= ${validFrom}`, actual: `${hour}:${String(minute).padStart(2, "0")}`, detail: `Current time before window start` };
      }
    }
    if (validUntil) {
      const [uh, um] = validUntil.split(":").map(Number);
      const untilMinutes = uh * 60 + (um || 0);
      if (currentMinutes > untilMinutes) {
        return { pass: false, expected: `<= ${validUntil}`, actual: `${hour}:${String(minute).padStart(2, "0")}`, detail: `Current time after window end` };
      }
    }
  }

  return { pass: true, detail: "Temporal window satisfied" };
}

// ── EnumeratedListConstraint ────────────────────────────────────────

async function evaluateEnumeratedList(constraint, context) {
  const { field, allowed, denied } = constraint;
  const resolved = await resolveField(field, context);
  const actual = resolved.value;

  if (actual === undefined || actual === null) {
    return { pass: false, error: resolved.errorCode || "context_field_missing", expected: null, actual: null, detail: resolved.error || `Field '${field}' not found in context` };
  }

  // Deny takes precedence over allow
  if (denied && denied.includes(actual)) {
    return { pass: false, expected: `not in [${denied.join(", ")}]`, actual, detail: `Value '${actual}' is in denied list` };
  }

  if (allowed && !allowed.includes(actual)) {
    return { pass: false, expected: `in [${allowed.join(", ")}]`, actual, detail: `Value '${actual}' is not in allowed list` };
  }

  return { pass: true, expected: allowed ? `in [${allowed.join(", ")}]` : "not denied", actual, detail: "Enumerated list satisfied" };
}

// ── StringPatternConstraint ─────────────────────────────────────────

async function evaluateStringPattern(constraint, context) {
  const { field, pattern, matchType } = constraint;
  const resolved = await resolveField(field, context);
  const actual = resolved.value;

  if (actual === undefined || actual === null) {
    return { pass: false, error: resolved.errorCode || "context_field_missing", expected: pattern, actual: null, detail: resolved.error || `Field '${field}' not found in context` };
  }

  if (typeof actual !== "string") {
    return { pass: false, error: "constraint_failed", expected: pattern, actual, detail: `Field '${field}' is not a string` };
  }

  let pass = false;

  switch (matchType) {
    case "exact":
      pass = actual === pattern;
      break;
    case "prefix":
      pass = actual.startsWith(pattern);
      break;
    case "suffix":
      pass = actual.endsWith(pattern);
      break;
    case "restricted_glob": {
      // Restricted glob alphabet (Plan 5):
      //   `**` matches any sequence (including `/`)
      //   `*`  matches any sequence that does not include `/`
      //   any other character matches itself literally
      const escaped = pattern
        .replace(/[.+?^${}()|[\]\\]/g, "\\$&")
        .replace(/\*\*/g, "\u0000")   // placeholder for **
        .replace(/\*/g, "[^/]*")
        .replace(/\u0000/g, ".*");
      const re = new RegExp(`^${escaped}$`);
      pass = re.test(actual);
      break;
    }
    default:
      return { pass: false, error: "constraint_failed", expected: pattern, actual, detail: `Unknown matchType: ${matchType}` };
  }

  return { pass, expected: `${matchType}: ${pattern}`, actual, detail: pass ? "String pattern satisfied" : `'${actual}' does not match ${matchType} '${pattern}'` };
}

// ── Field resolution (semantic-aware) ───────────────────────────────

/**
 * Resolve a field from the context, trying semantic mapping first (BR-9).
 * Falls back to direct dotted-path resolution for backward compatibility.
 *
 * @param {string} fieldPath - field path (may be a semantic identifier or direct path)
 * @param {object} context - request context
 * @returns {Promise<{ value: any, error?: string, errorCode?: string }>}
 */
async function resolveField(fieldPath, context) {
  const result = await resolveSemanticField(fieldPath, context);
  if (result.resolved) {
    return { value: result.value };
  }
  return { value: undefined, error: result.error, errorCode: result.errorCode };
}
