// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { randomUUID } from "node:crypto";

/**
 * Plan 4: enrich the incoming request context with reserved namespaces so
 * that MVV identifiers (Section 7.12.2) can resolve against credential-derived
 * and request-time facts in addition to caller-supplied claim attributes.
 *
 * The reserved namespace is `__credential.*` for facts pulled from the
 * verified credential payload, and `__request.*` for facts pulled from the
 * HTTP request envelope. defaultMappings in semanticResolver.js points the
 * Required MVV identifiers at these paths.
 */
export function enrichRequestContext({ requestContext, payload, presenterId, req }) {
  const enriched = { ...(requestContext || {}) };

  enriched.__credential = {
    issuerId: payload?.issuerId ?? null,
    subjectId: payload?.agentId ?? null,
    presenterId: presenterId ?? null,
    audience: payload?.audience ?? null,
    validFrom: payload?.issuedAt ?? null,
    validUntil: payload?.expiresAt ?? null,
    delegatorId: payload?.delegatedFrom?.agentId ?? null,
    permission: requestContext?.action ?? null,
    credentialId: payload?.credentialId ?? null,
    trustTier: payload?.trustTier ?? null,
  };

  enriched.__request = {
    requestId: requestContext?.requestId
      ?? req?.headers?.["x-request-id"]
      ?? randomUUID(),
    ipAddress: requestContext?.ipAddress
      ?? (req?.headers?.["x-forwarded-for"] || "").split(",")[0].trim()
      ?? req?.ip
      ?? null,
  };

  return enriched;
}
