// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import * as jose from "jose";
import crypto from "node:crypto";
import { getPool } from "../db/pool.js";
import { resolveDID, extractVerificationKey } from "./didResolver.js";
import { checkBitstringStatus } from "./statusListChecker.js";
import {
  certificateFingerprintSha256,
  validateCertificateIdentity,
  verifyX509ChainFromHeader,
} from "./x509Verifier.js";
import { checkTier1Revocation, resolveRevocationConfig } from "./revocationClient.js";
import logger from "./logger.js";

/**
 * JWKS cache: { [issuerUrl]: { keys: JWKS, fetchedAt: number } }
 */
const jwksCache = new Map();

function cacheTtlMs() {
  return (parseInt(process.env.JWKS_CACHE_TTL_SECONDS || "300", 10)) * 1000;
}

/**
 * Fetch JWKS from an issuer's well-known endpoint.
 * Tries /.well-known/jwks.json directly, then OIDC discovery.
 */
async function fetchJWKS(issuerUrl, preferredJwksUri = null) {
  const cached = jwksCache.get(issuerUrl);
  if (cached && (Date.now() - cached.fetchedAt) < cacheTtlMs()) {
    return cached.keys;
  }

  let jwksUri = preferredJwksUri;

  // Try OIDC discovery first
  if (!jwksUri) {
    try {
      const discoveryUrl = issuerUrl.replace(/\/$/, "") + "/.well-known/openid-configuration";
      const discResp = await fetch(discoveryUrl);
      if (discResp.ok) {
        const config = await discResp.json();
        if (config.jwks_uri) jwksUri = config.jwks_uri;
      }
    } catch (_) {
      // Fall through
    }
  }

  // Fallback: direct JWKS endpoint
  if (!jwksUri) {
    jwksUri = issuerUrl.replace(/\/$/, "") + "/.well-known/jwks.json";
  }

  const resp = await fetch(jwksUri);
  if (!resp.ok) {
    throw Object.assign(new Error(`Failed to fetch JWKS from ${jwksUri}: ${resp.status}`), { code: "jwks_fetch_failed" });
  }

  const jwks = await resp.json();
  jwksCache.set(issuerUrl, { keys: jwks, fetchedAt: Date.now() });
  return jwks;
}

async function lookupTrustedIssuerMetadata(issuerId) {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      `SELECT jwks_uri
       FROM portauth_trusted_issuers
       WHERE issuer_id = $1 AND active = TRUE
       ORDER BY added_at DESC
       LIMIT 1`,
      [issuerId]
    );
    return rows[0] || null;
  } catch (_) {
    return null;
  }
}

function deriveDefaultIntrospectionUrl(issuerId) {
  if (!issuerId || issuerId.startsWith("did:")) {
    return null;
  }
  return `${issuerId.replace(/\/$/, "")}/credentials/introspect`;
}

function parseJsonb(value) {
  if (!value) return {};
  if (typeof value === "object") return value;
  try {
    return JSON.parse(value);
  } catch (_) {
    return {};
  }
}

function stableStringify(value) {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`;
}

export function hashRequestContext(requestContext) {
  return crypto
    .createHash("sha256")
    .update(stableStringify(requestContext || {}))
    .digest("base64url");
}

function listFromClaim(value) {
  if (value === undefined || value === null) return [];
  return Array.isArray(value) ? value : [value];
}

function getEvaluatorAudiences(options = {}) {
  const configured = options.evaluatorId
    || options.evaluatorAudience
    || process.env.PORTAUTH_EVALUATOR_ID
    || process.env.EVALUATOR_ID
    || process.env.PORTAUTH_ENGINE_AUDIENCE
    || process.env.ENGINE_AUDIENCE;

  if (!configured) return [];
  return Array.isArray(configured)
    ? configured
    : String(configured).split(",").map((item) => item.trim()).filter(Boolean);
}

export function validateAudience(audienceClaim, options = {}) {
  const audiences = listFromClaim(audienceClaim);
  if (audiences.length === 0) {
    return { pass: true, check: "skipped" };
  }

  const expected = getEvaluatorAudiences(options);
  if (expected.length === 0) {
    return {
      pass: false,
      error: "Credential includes audience but evaluator identity is not configured",
      errorCode: "audience_mismatch",
    };
  }

  const matched = audiences.some((audience) => expected.includes(audience));
  if (!matched) {
    return {
      pass: false,
      error: `Credential audience [${audiences.join(", ")}] does not include evaluator [${expected.join(", ")}]`,
      errorCode: "audience_mismatch",
    };
  }

  return { pass: true, check: "pass" };
}

function envFlag(name) {
  return String(process.env[name] || "").toLowerCase() === "true";
}

function extractConfirmationJwk(payload, vc = null) {
  return payload?.cnf?.jwk
    || payload?.confirmation?.jwk
    || payload?.proofKeyJwk
    || vc?.credentialSubject?.cnf?.jwk
    || vc?.credentialSubject?.proofKeyJwk
    || null;
}

export async function verifyProofOfPossession({
  payload,
  vc = null,
  presenterId,
  credentialId,
  requestContext,
  proofOfPossession,
  options = {},
}) {
  if (options.skipProofOfPossession) {
    return { pass: true, check: "skipped" };
  }

  const proofKeyJwk = extractConfirmationJwk(payload, vc);
  const proofRequired = Boolean(proofKeyJwk)
    || options.requireProofOfPossession === true
    || envFlag("PORTAUTH_REQUIRE_PROOF_OF_POSSESSION");

  if (!proofRequired) {
    return { pass: true, check: "skipped" };
  }

  if (!proofKeyJwk) {
    return {
      pass: false,
      error: "Credential does not include a confirmation JWK for proof of possession",
      errorCode: "proof_of_possession_failed",
    };
  }

  const proofJws = typeof proofOfPossession === "string"
    ? proofOfPossession
    : proofOfPossession?.jws;

  if (!proofJws) {
    return {
      pass: false,
      error: "Missing proof of possession JWS",
      errorCode: "proof_of_possession_failed",
    };
  }

  try {
    const key = await jose.importJWK(proofKeyJwk, proofKeyJwk.alg);
    const { payload: proofPayload } = await jose.jwtVerify(proofJws, key, {
      clockTolerance: "5 seconds",
    });

    const expectedHash = hashRequestContext(requestContext);
    if (proofPayload.credentialId !== credentialId) {
      throw new Error("Proof credentialId does not match presented credential");
    }
    if (proofPayload.presenterId !== presenterId) {
      throw new Error("Proof presenterId does not match presenter");
    }
    if (proofPayload.requestHash !== expectedHash) {
      throw new Error("Proof requestHash does not match request context");
    }
    if (!proofPayload.iat) {
      throw new Error("Proof is missing iat freshness claim");
    }

    const maxAgeSeconds = options.proofMaxAgeSeconds
      ?? parseInt(process.env.PORTAUTH_PROOF_MAX_AGE_SECONDS || "300", 10);
    const ageSeconds = Math.floor(Date.now() / 1000) - proofPayload.iat;
    if (ageSeconds > maxAgeSeconds) {
      throw new Error("Proof is outside the accepted freshness window");
    }

    return { pass: true, check: "pass" };
  } catch (err) {
    return {
      pass: false,
      error: `Proof of possession verification failed: ${err.message}`,
      errorCode: "proof_of_possession_failed",
    };
  }
}

/**
 * Verify a JWT credential and return a normalized authorization payload.
 *
 * Processing order per the spec:
 * 1. Decode JWT structure
 * 2. Extract issuer, resolve JWKS, verify signature
 * 3. Validate temporal claims (nbf, exp)
 * 4. Check issuer trust (against DB registry)
 * 5. Check audience and optional proof binding
 * 6. Check revocation
 * 7. Validate subject binding (presenterId matches sub)
 * 8. Normalize to common payload
 *
 * @param {string} credential - JWT compact serialization
 * @param {string} presenterId - the authenticated identity of the presenter
 * @param {object} [options]
 * @param {boolean} [options.skipRevocationCheck] - for testing
 * @param {string} [options.introspectionUrl] - issuer introspection endpoint
 * @param {string} [options.evaluatorId] - receiver identity used for audience binding
 * @param {object|string} [options.proofOfPossession] - compact JWS proof or {jws}
 * @param {object} [options.requestContext] - request context bound into proof JWS
 * @returns {object} { verified: true, payload: NormalizedPayload } or { verified: false, error, errorCode }
 */
export async function verifyCredential(credential, presenterId, options = {}) {
  // Step 1: Decode without verification to inspect claims
  let header, claims;
  try {
    const parts = credential.split(".");
    if (parts.length !== 3) throw new Error("Not a valid JWT");
    header = JSON.parse(Buffer.from(parts[0], "base64url").toString());
    claims = JSON.parse(Buffer.from(parts[1], "base64url").toString());
  } catch (err) {
    return { verified: false, error: "Malformed JWT", errorCode: "credential_incomplete" };
  }

  logger.info({ msg: "📦 STORY STEP 2a: Container Received (Layer 1)", header, claims });

  // Step 1b: Structural validation — all four authorization policy components
  if (!claims.iss) return { verified: false, error: "Missing iss claim", errorCode: "credential_incomplete" };
  if (!claims.sub) return { verified: false, error: "Missing sub claim", errorCode: "credential_incomplete" };

  // For VC-JOSE, permissions/constraints live inside vc.credentialSubject
  const vcSubject = claims.vc?.credentialSubject;
  const topPerms = claims.permissions || vcSubject?.permissions || vcSubject?.authorization?.permissions;
  const topConstraints = claims.constraints || claims.termsOfUse || vcSubject?.constraints || vcSubject?.authorization?.constraints;

  if (!topPerms || !Array.isArray(topPerms)) {
    return { verified: false, error: "Missing or invalid permissions claim", errorCode: "credential_incomplete" };
  }
  if (!topConstraints || !Array.isArray(topConstraints)) {
    return { verified: false, error: "Missing or invalid constraints/termsOfUse claim", errorCode: "credential_incomplete" };
  }

  // Step 2: Determine trust tier and credential profile
  //   - x5c header present → Tier 2 (X.509-backed JWT profile)
  //   - iss starting with "did:" → Tier 3 (VC-JOSE profile)
  //   - iss as URL → Tier 1 (plain JWT profile)
  const isDID = claims.iss.startsWith("did:");
  const hasX5c = Array.isArray(header.x5c) && header.x5c.length > 0;
  const hasVcClaim = claims.vc && typeof claims.vc === "object";
  const trustTier = hasX5c ? 2 : (isDID ? 3 : 1);
  const credentialProfile = hasX5c ? "tier2-x509-jwt" : ((isDID || hasVcClaim) ? "vc-jose" : "tier1-jwt");

  // Route to the appropriate verification path
  if (credentialProfile === "tier2-x509-jwt") {
    return verifyX509Jwt(credential, header, claims, presenterId, topPerms, topConstraints, options);
  }
  if (credentialProfile === "vc-jose") {
    return verifyVcJose(credential, header, claims, presenterId, options);
  }

  // ── Tier 1: Plain JWT verification ──────────────────────────────
  let verifiedPayload;
  try {
    const issuerMetadata = await lookupTrustedIssuerMetadata(claims.iss);
    const jwks = await fetchJWKS(claims.iss, issuerMetadata?.jwks_uri || null);
    const keySet = jose.createLocalJWKSet(jwks);
    const result = await jose.jwtVerify(credential, keySet, {
      issuer: claims.iss,
    });
    verifiedPayload = result.payload;
  } catch (err) {
    if (err.code === "ERR_JWKS_NO_MATCHING_KEY" || err.code === "ERR_JWS_SIGNATURE_VERIFICATION_FAILED") {
      return { verified: false, error: "Signature verification failed", errorCode: "signature_invalid" };
    }
    if (err.code === "jwks_fetch_failed") {
      return { verified: false, error: err.message, errorCode: "signature_invalid" };
    }
    if (err.code === "ERR_JWT_EXPIRED") {
      return { verified: false, error: "Credential expired", errorCode: "credential_expired" };
    }
    if (err.code === "ERR_JWT_CLAIM_VALIDATION_FAILED" && err.claim === "nbf") {
      return { verified: false, error: "Credential not yet valid", errorCode: "credential_expired" };
    }
    return { verified: false, error: `Verification failed: ${err.message}`, errorCode: "signature_invalid" };
  }

  // Step 3: Check issuer trust
  const pool = getPool();
  const { rows: issuerRows } = await pool.query(
    `SELECT trusted_for_permissions,
            revocation_mechanism,
            revocation_failure_mode,
            revocation_timeout_ms,
            revocation_retries
     FROM portauth_trusted_issuers
     WHERE issuer_id = $1 AND active = TRUE AND trust_tier = $2`,
    [claims.iss, trustTier]
  );

  if (issuerRows.length === 0) {
    return { verified: false, error: `Issuer ${claims.iss} is not trusted`, errorCode: "issuer_untrusted" };
  }

  // Check that the issuer is trusted for the credential's permissions
  const trustedPermissions = issuerRows[0].trusted_for_permissions;
  const untrustedPerms = claims.permissions.filter(p => !trustedPermissions.includes(p));
  if (untrustedPerms.length > 0) {
    return {
      verified: false,
      error: `Issuer not trusted for permissions: ${untrustedPerms.join(", ")}`,
      errorCode: "issuer_untrusted",
    };
  }

  // Step 4: Audience binding
  const audienceCheck = validateAudience(verifiedPayload.aud, options);
  if (!audienceCheck.pass) {
    return { verified: false, error: audienceCheck.error, errorCode: audienceCheck.errorCode };
  }

  // Step 5: Revocation check via introspection. Plan 1 hardening:
  // honor per-issuer overrides for timeout, retries, and failure mode;
  // surface a distinct error code when failure_mode is closed.
  const revocationMechanism = (issuerRows[0].revocation_mechanism || "introspection").toLowerCase();
  const revocationConfig = resolveRevocationConfig({
    issuerOverrides: issuerRows[0],
    callerOptions: {
      revocationTimeoutMs: options.revocationTimeoutMs,
      revocationRetries: options.revocationRetries,
      revocationFailureMode: options.revocationFailureMode,
    },
  });
  const introspectionUrl = options.introspectionUrl || deriveDefaultIntrospectionUrl(claims.iss);
  let revocationCheckResult = "skipped";
  if (!options.skipRevocationCheck && revocationMechanism === "introspection" && introspectionUrl) {
    const r = await checkTier1Revocation({
      introspectionUrl,
      credentialId: claims.jti,
      config: revocationConfig,
    });
    if (r.outcome === "revoked") {
      return { verified: false, error: "Credential has been revoked", errorCode: "credential_revoked" };
    }
    if (r.outcome === "unavailable" && revocationConfig.failureMode === "closed") {
      return {
        verified: false,
        error: `Tier 1 revocation check unavailable: ${r.error}`,
        errorCode: "tier1_revocation_unavailable",
      };
    }
    revocationCheckResult = r.outcome === "unavailable" ? "unavailable" : "pass";
  } else if (revocationMechanism === "none") {
    revocationCheckResult = "disabled";
  }

  // Step 6: Subject binding
  if (presenterId && claims.sub !== presenterId) {
    return {
      verified: false,
      error: `Subject binding mismatch: credential sub=${claims.sub}, presenter=${presenterId}`,
      errorCode: "subject_binding_mismatch",
    };
  }

  // Step 7: Proof of possession
  const proofCheck = await verifyProofOfPossession({
    payload: verifiedPayload,
    presenterId,
    credentialId: verifiedPayload.jti,
    requestContext: options.requestContext,
    proofOfPossession: options.proofOfPossession,
    options,
  });
  if (!proofCheck.pass) {
    return { verified: false, error: proofCheck.error, errorCode: proofCheck.errorCode };
  }

  // Step 8: Normalize to common payload
  const normalizedConstraints = normalizeConstraints(topConstraints);

  const normalized = {
    issuerId: claims.iss,
    agentId: claims.sub,
    credentialId: claims.jti,
    permissions: claims.permissions,
    constraints: normalizedConstraints,
    validFrom: claims.nbf ? new Date(claims.nbf * 1000).toISOString() : null,
    validUntil: claims.exp ? new Date(claims.exp * 1000).toISOString() : null,
    trustTier,
    credentialProfile: "tier1-jwt",
    delegatedFrom: claims.delegatedFrom || null,
    audience: claims.aud || null,
  };

  logger.info({ msg: "📑 STORY STEP 2b: Payload Extracted & Normalized (Layer 2)", payload: normalized });

  return {
    verified: true,
    payload: normalized,
    checks: {
      structure: "pass",
      signature: "pass",
      temporal: "pass",
      issuerTrust: "pass",
      audience: audienceCheck.check,
      revocation: options.skipRevocationCheck ? "skipped" : revocationCheckResult,
      subjectBinding: presenterId ? "pass" : "skipped",
      proofOfPossession: proofCheck.check,
    },
  };
}

/**
 * Clear the JWKS cache (for testing).
 */
export function clearJWKSCache() {
  jwksCache.clear();
}

// ═══════════════════════════════════════════════════════════════════════
// Tier 2 Profile Verification (X.509-backed JWT)
// ═══════════════════════════════════════════════════════════════════════

async function checkX509Revocation(leafFingerprint, trustedIssuer, options = {}) {
  if (options.skipRevocationCheck) {
    return { pass: true, check: "skipped" };
  }

  const policy = options.x509RevocationPolicy
    || trustedIssuer.x509_revocation_policy
    || process.env.PORTAUTH_X509_REVOCATION_POLICY
    || "soft-fail";

  try {
    const pool = getPool();
    const { rows } = await pool.query(
      `SELECT reason, revoked_at
       FROM portauth_x509_revoked_certificates
       WHERE fingerprint_sha256 = $1 AND active = TRUE
       LIMIT 1`,
      [leafFingerprint]
    );

    if (rows.length > 0) {
      return {
        pass: false,
        error: `X.509 signing certificate has been revoked: ${rows[0].reason || "no reason supplied"}`,
        errorCode: "credential_revoked",
      };
    }

    return { pass: true, check: "pass" };
  } catch (err) {
    if (policy === "hard-fail") {
      return {
        pass: false,
        error: `X.509 revocation status unavailable: ${err.message}`,
        errorCode: "x509_revocation_unavailable",
      };
    }
    return { pass: true, check: "skipped" };
  }
}

async function verifyX509Jwt(credential, header, claims, presenterId, permissions, rawConstraints, options = {}) {
  const pool = getPool();
  const { rows: issuerRows } = await pool.query(
    `SELECT trusted_for_permissions, x509_subject, x509_san_uri,
            x509_trust_anchor_pem, x509_trust_anchor_sha256,
            x509_revocation_policy, metadata
     FROM portauth_trusted_issuers
     WHERE issuer_id = $1 AND active = TRUE AND trust_tier = 2`,
    [claims.iss]
  );

  if (issuerRows.length === 0) {
    return { verified: false, error: `Issuer ${claims.iss} is not trusted for Tier 2`, errorCode: "issuer_untrusted" };
  }

  const trustedIssuer = {
    ...issuerRows[0],
    metadata: parseJsonb(issuerRows[0].metadata),
  };

  const chainCheck = verifyX509ChainFromHeader(header, {
    ...options,
    trustAnchorsPem: trustedIssuer.x509_trust_anchor_pem || options.trustAnchorsPem,
    trustAnchorSha256: trustedIssuer.x509_trust_anchor_sha256 || options.trustAnchorSha256,
  });
  if (!chainCheck.pass) {
    return { verified: false, error: chainCheck.error, errorCode: chainCheck.errorCode };
  }

  const identityCheck = validateCertificateIdentity(chainCheck.leafCertificate, claims.iss, trustedIssuer);
  if (!identityCheck.pass) {
    return { verified: false, error: identityCheck.error, errorCode: identityCheck.errorCode };
  }

  let verifiedPayload;
  try {
    const result = await jose.jwtVerify(credential, chainCheck.leafCertificate.publicKey, {
      issuer: claims.iss,
    });
    verifiedPayload = result.payload;
  } catch (err) {
    if (err.code === "ERR_JWS_SIGNATURE_VERIFICATION_FAILED") {
      return { verified: false, error: "Signature verification failed", errorCode: "signature_invalid" };
    }
    if (err.code === "ERR_JWT_EXPIRED") {
      return { verified: false, error: "Credential expired", errorCode: "credential_expired" };
    }
    if (err.code === "ERR_JWT_CLAIM_VALIDATION_FAILED" && err.claim === "nbf") {
      return { verified: false, error: "Credential not yet valid", errorCode: "credential_expired" };
    }
    return { verified: false, error: `X.509 JWT verification failed: ${err.message}`, errorCode: "signature_invalid" };
  }

  const verifiedPermissions = verifiedPayload.permissions || permissions;
  const verifiedConstraints = verifiedPayload.constraints || rawConstraints;

  const trustedPermissions = trustedIssuer.trusted_for_permissions;
  const untrustedPerms = verifiedPermissions.filter(p => !trustedPermissions.includes(p));
  if (untrustedPerms.length > 0) {
    return {
      verified: false,
      error: `Issuer not trusted for permissions: ${untrustedPerms.join(", ")}`,
      errorCode: "issuer_untrusted",
    };
  }

  const audienceCheck = validateAudience(verifiedPayload.aud, options);
  if (!audienceCheck.pass) {
    return { verified: false, error: audienceCheck.error, errorCode: audienceCheck.errorCode };
  }

  const leafFingerprint = certificateFingerprintSha256(chainCheck.leafCertificate);
  const revocationCheck = await checkX509Revocation(leafFingerprint, trustedIssuer, options);
  if (!revocationCheck.pass) {
    return { verified: false, error: revocationCheck.error, errorCode: revocationCheck.errorCode };
  }

  if (presenterId && verifiedPayload.sub !== presenterId) {
    return {
      verified: false,
      error: `Subject binding mismatch: credential sub=${verifiedPayload.sub}, presenter=${presenterId}`,
      errorCode: "subject_binding_mismatch",
    };
  }

  const proofCheck = await verifyProofOfPossession({
    payload: verifiedPayload,
    presenterId,
    credentialId: verifiedPayload.jti,
    requestContext: options.requestContext,
    proofOfPossession: options.proofOfPossession,
    options,
  });
  if (!proofCheck.pass) {
    return { verified: false, error: proofCheck.error, errorCode: proofCheck.errorCode };
  }

  const normalized = {
    issuerId: verifiedPayload.iss,
    agentId: verifiedPayload.sub,
    credentialId: verifiedPayload.jti,
    permissions: verifiedPermissions,
    constraints: normalizeConstraints(verifiedConstraints),
    validFrom: verifiedPayload.nbf ? new Date(verifiedPayload.nbf * 1000).toISOString() : null,
    validUntil: verifiedPayload.exp ? new Date(verifiedPayload.exp * 1000).toISOString() : null,
    trustTier: 2,
    credentialProfile: "tier2-x509-jwt",
    delegatedFrom: verifiedPayload.delegatedFrom || null,
    audience: verifiedPayload.aud || null,
    x509: {
      leafFingerprintSha256: leafFingerprint,
      trustAnchorFingerprintSha256: chainCheck.trustAnchorFingerprint,
      identityBinding: identityCheck.check,
    },
  };

  logger.info({ msg: "📑 STORY STEP 2b: Payload Extracted & Normalized (Layer 2)", payload: normalized });

  return {
    verified: true,
    payload: normalized,
    checks: {
      structure: "pass",
      signature: "pass",
      temporal: "pass",
      x509Chain: "pass",
      x509Identity: identityCheck.check,
      issuerTrust: "pass",
      audience: audienceCheck.check,
      revocation: revocationCheck.check,
      subjectBinding: presenterId ? "pass" : "skipped",
      proofOfPossession: proofCheck.check,
    },
  };
}

// ═══════════════════════════════════════════════════════════════════════
// VC-JOSE Profile Verification (Tier 3 Phase 1)
// W3C VC Data Model payload secured with JOSE/JWS
// Supported DID methods: did:web, did:key
// ═══════════════════════════════════════════════════════════════════════

/**
 * Verify a VC-JOSE credential.
 *
 * Processing order:
 * 1. Verify JWS signature using DID-resolved key
 * 2. Extract VC payload from the `vc` claim (W3C VC JOSE/COSE format)
 * 3. Validate VC structure (type, credentialSubject, etc.)
 * 4. Check issuer trust (DID in portauth_trusted_issuers with trust_tier=3)
 * 5. Check credential status via Bitstring Status List (fail-closed)
 * 6. Validate subject/presenter binding
 * 7. Normalize to the same canonical payload as Tier 1
 *
 * @param {string} credential - JWT compact serialization (VC-JOSE)
 * @param {object} header - decoded JWT header
 * @param {object} claims - decoded JWT payload
 * @param {string} presenterId - authenticated presenter identity
 * @param {object} options
 * @returns {object} { verified, payload?, error?, errorCode? }
 */
async function verifyVcJose(credential, header, claims, presenterId, options = {}) {
  const issuerDid = claims.iss;

  // ── Step 1: Resolve DID and verify JWS ──────────────────────────
  let verifiedPayload;
  try {
    const { didDocument } = await resolveDID(issuerDid);

    // Extract the signing key from the DID Document
    // Use kid from JWT header if present, otherwise first assertionMethod
    const kid = header.kid || null;
    const { publicKey } = await extractVerificationKey(didDocument, kid);

    // Verify the JWS with the DID-resolved key
    const result = await jose.jwtVerify(credential, publicKey, {
      issuer: issuerDid,
    });
    verifiedPayload = result.payload;
  } catch (err) {
    if (err.code === "unsupported_did_method") {
      return { verified: false, error: err.message, errorCode: "unsupported_did_method" };
    }
    if (err.code === "did_resolution_failed") {
      return { verified: false, error: err.message, errorCode: "did_resolution_failed" };
    }
    if (err.code === "did_no_verification_method" || err.code === "did_key_extraction_failed") {
      return { verified: false, error: err.message, errorCode: "signature_invalid" };
    }
    if (err.code === "ERR_JWS_SIGNATURE_VERIFICATION_FAILED") {
      return { verified: false, error: "Signature verification failed", errorCode: "signature_invalid" };
    }
    if (err.code === "ERR_JWT_EXPIRED") {
      return { verified: false, error: "Credential expired", errorCode: "credential_expired" };
    }
    if (err.code === "ERR_JWT_CLAIM_VALIDATION_FAILED" && err.claim === "nbf") {
      return { verified: false, error: "Credential not yet valid", errorCode: "credential_expired" };
    }
    return { verified: false, error: `VC-JOSE verification failed: ${err.message}`, errorCode: "signature_invalid" };
  }

  // ── Step 2: Extract VC payload ──────────────────────────────────
  // W3C VC JOSE/COSE: the JWT payload contains a `vc` claim with the VC Data Model
  const vc = verifiedPayload.vc;
  if (!vc || typeof vc !== "object") {
    return { verified: false, error: "Missing vc claim in JWT payload", errorCode: "credential_incomplete" };
  }

  // Validate VC type
  const vcTypes = vc.type || [];
  if (!vcTypes.includes("VerifiableCredential")) {
    return { verified: false, error: "VC missing required type 'VerifiableCredential'", errorCode: "credential_incomplete" };
  }

  // ── Step 3: Extract authorization payload components ────────────
  // The four mandatory components can appear in multiple places depending on the issuer's choice.
  // Priority: top-level JWT claims > vc.credentialSubject fields > termsOfUse

  // Component 1 — Agent Identity (sub)
  const agentId = verifiedPayload.sub
    || vc.credentialSubject?.id
    || (typeof vc.credentialSubject === "string" ? vc.credentialSubject : null);
  if (!agentId) {
    return { verified: false, error: "Missing agent identity (sub or credentialSubject.id)", errorCode: "credential_incomplete" };
  }

  // Component 3 — Permissions
  const permissions = verifiedPayload.permissions
    || vc.credentialSubject?.permissions
    || vc.credentialSubject?.authorization?.permissions;
  if (!permissions || !Array.isArray(permissions) || permissions.length === 0) {
    return { verified: false, error: "Missing or invalid permissions", errorCode: "credential_incomplete" };
  }

  // Component 4 — Constraints
  const rawConstraints = verifiedPayload.constraints
    || verifiedPayload.termsOfUse
    || vc.credentialSubject?.constraints
    || vc.credentialSubject?.authorization?.constraints
    || vc.termsOfUse;
  if (!rawConstraints || !Array.isArray(rawConstraints)) {
    return { verified: false, error: "Missing or invalid constraints", errorCode: "credential_incomplete" };
  }

  // Credential ID
  const credentialId = verifiedPayload.jti || vc.id || null;

  // Delegation reference
  const delegatedFrom = verifiedPayload.delegatedFrom
    || vc.credentialSubject?.delegatedFrom
    || null;

  // ── Step 4: Check issuer trust ──────────────────────────────────
  const pool = getPool();
  const { rows: issuerRows } = await pool.query(
    `SELECT trusted_for_permissions, governance_status FROM portauth_trusted_issuers
     WHERE issuer_id = $1 AND active = TRUE AND trust_tier = 3`,
    [issuerDid]
  );

  if (issuerRows.length === 0) {
    return { verified: false, error: `Issuer ${issuerDid} is not trusted`, errorCode: "issuer_untrusted" };
  }

  // Check governance standing
  if (issuerRows[0].governance_status !== "active") {
    return {
      verified: false,
      error: `Issuer ${issuerDid} governance status: ${issuerRows[0].governance_status}`,
      errorCode: "issuer_untrusted",
    };
  }

  // Check trusted permissions
  const trustedPermissions = issuerRows[0].trusted_for_permissions;
  const untrustedPerms = permissions.filter(p => !trustedPermissions.includes(p));
  if (untrustedPerms.length > 0) {
    return {
      verified: false,
      error: `Issuer not trusted for permissions: ${untrustedPerms.join(", ")}`,
      errorCode: "issuer_untrusted",
    };
  }

  // ── Step 5: Audience binding ───────────────────────────────────
  const audienceCheck = validateAudience(verifiedPayload.aud, options);
  if (!audienceCheck.pass) {
    return { verified: false, error: audienceCheck.error, errorCode: audienceCheck.errorCode };
  }

  // ── Step 6: Credential status (Bitstring Status List) ───────────
  // For VC-JOSE credentials, use Bitstring Status List instead of introspection
  if (!options.skipRevocationCheck) {
    const credentialStatus = vc.credentialStatus
      || verifiedPayload.credentialStatus;

    if (credentialStatus) {
      const statusResult = await checkBitstringStatus(credentialStatus);
      if (statusResult.revoked) {
        return { verified: false, error: "Credential has been revoked (status list)", errorCode: "credential_revoked" };
      }
      if (statusResult.suspended) {
        return { verified: false, error: "Credential has been suspended (status list)", errorCode: "credential_revoked" };
      }
    }
    // No credentialStatus field → no revocation mechanism; rely on exp claim
  }

  // ── Step 7: Subject/presenter binding ───────────────────────────
  if (presenterId && agentId !== presenterId) {
    return {
      verified: false,
      error: `Subject binding mismatch: credential subject=${agentId}, presenter=${presenterId}`,
      errorCode: "subject_binding_mismatch",
    };
  }

  // ── Step 8: Proof of possession ─────────────────────────────────
  const proofCheck = await verifyProofOfPossession({
    payload: verifiedPayload,
    vc,
    presenterId,
    credentialId,
    requestContext: options.requestContext,
    proofOfPossession: options.proofOfPossession,
    options,
  });
  if (!proofCheck.pass) {
    return { verified: false, error: proofCheck.error, errorCode: proofCheck.errorCode };
  }

  // ── Step 9: Normalize to common payload ─────────────────────────
  const normalizedConstraints = normalizeConstraints(rawConstraints);

  const normalized = {
    issuerId: issuerDid,
    agentId,
    credentialId,
    permissions,
    constraints: normalizedConstraints,
    validFrom: verifiedPayload.nbf ? new Date(verifiedPayload.nbf * 1000).toISOString() : null,
    validUntil: verifiedPayload.exp ? new Date(verifiedPayload.exp * 1000).toISOString() : null,
    trustTier: 3,
    credentialProfile: "vc-jose",
    delegatedFrom,
    audience: verifiedPayload.aud || null,
  };

  return {
    verified: true,
    payload: normalized,
    checks: {
      structure: "pass",
      signature: "pass",
      didResolution: "pass",
      temporal: "pass",
      issuerTrust: "pass",
      governanceStanding: "pass",
      audience: audienceCheck.check,
      revocation: options.skipRevocationCheck ? "skipped" : "pass",
      subjectBinding: presenterId ? "pass" : "skipped",
      proofOfPossession: proofCheck.check,
    },
  };
}

/**
 * Normalize constraints from various VC payload shapes to the canonical flat array.
 *
 * Handles:
 * - Direct typed constraint objects (current format)
 * - VC termsOfUse wrapping ({ type: "AgentPolicyConstraint", constraints: [...] })
 * - W3C termsOfUse with profile and nested constraints
 */
function normalizeConstraints(rawConstraints) {
  return rawConstraints.map(c => {
    // Unwrap AgentPolicyConstraint nesting
    if (c.type === "AgentPolicyConstraint" && Array.isArray(c.constraints)) {
      return c.constraints;
    }
    // Unwrap any termsOfUse entry with a nested constraints array
    if (c.obligation && Array.isArray(c.obligation)) {
      return c.obligation;
    }
    return c;
  }).flat();
}
