// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

/**
 * DID Resolver Service
 *
 * Resolves did:web and did:key identifiers to DID Documents,
 * with a DB-backed cache (same pattern as JWKS cache).
 *
 * Phase 1 VC profile supports only did:web and did:key.
 * Unknown DID methods fail closed.
 */

import { Resolver } from "did-resolver";
import { getResolver as getWebResolver } from "web-did-resolver";
import { driver as didKeyDriver } from "@digitalbazaar/did-method-key";
import * as jose from "jose";
import { getPool } from "../db/pool.js";

/** Cache TTL for resolved DID documents (seconds). */
function cacheTtlSeconds() {
  return parseInt(process.env.DID_CACHE_TTL_SECONDS || "300", 10);
}

/**
 * did:key resolver adapter — wraps @digitalbazaar/did-method-key into
 * the did-resolver interface ({ resolve(did) → { didDocument } }).
 */
function getKeyResolver() {
  const keyDriver = didKeyDriver();
  return {
    key: async (did) => {
      try {
        const { didDocument } = await keyDriver.get({ did });
        return { didDocument, didDocumentMetadata: {}, didResolutionMetadata: {} };
      } catch (err) {
        return {
          didDocument: null,
          didDocumentMetadata: {},
          didResolutionMetadata: { error: "notFound", message: err.message },
        };
      }
    },
  };
}

/** Singleton resolver instance. */
let resolverInstance = null;

function getResolver() {
  if (!resolverInstance) {
    resolverInstance = new Resolver({
      ...getWebResolver(),
      ...getKeyResolver(),
    });
  }
  return resolverInstance;
}

/**
 * Resolve a DID to its DID Document.
 *
 * 1. Check DB cache (with TTL)
 * 2. If miss, resolve via network
 * 3. Cache the result
 *
 * @param {string} did - The DID to resolve (did:web:... or did:key:...)
 * @returns {{ didDocument: object, cached: boolean }} or throws
 */
export async function resolveDID(did) {
  // Validate method — fail-closed on unsupported methods
  const method = did.split(":")[1];
  if (!method || !["web", "key"].includes(method)) {
    throw Object.assign(
      new Error(`Unsupported DID method: ${method || "unknown"}. Only did:web and did:key are supported.`),
      { code: "unsupported_did_method" }
    );
  }

  // Check DB cache
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT did_document, expires_at FROM portauth_did_cache
     WHERE did = $1 AND expires_at > NOW()`,
    [did]
  );

  if (rows.length > 0) {
    return { didDocument: rows[0].did_document, cached: true };
  }

  // Resolve via network
  const resolver = getResolver();
  const result = await resolver.resolve(did);

  if (result.didResolutionMetadata?.error || !result.didDocument) {
    throw Object.assign(
      new Error(`DID resolution failed for ${did}: ${result.didResolutionMetadata?.error || "no document"}`),
      { code: "did_resolution_failed" }
    );
  }

  // Cache to DB
  const ttl = cacheTtlSeconds();
  const expiresAt = new Date(Date.now() + ttl * 1000);
  await pool.query(
    `INSERT INTO portauth_did_cache (did, did_document, resolved_at, expires_at)
     VALUES ($1, $2, NOW(), $3)
     ON CONFLICT (did) DO UPDATE SET
       did_document = EXCLUDED.did_document,
       resolved_at = NOW(),
       expires_at = EXCLUDED.expires_at`,
    [did, JSON.stringify(result.didDocument), expiresAt]
  );

  return { didDocument: result.didDocument, cached: false };
}

/**
 * Extract a JWK public key from a DID Document by verification method reference.
 *
 * Supports:
 * - verificationMethod entries with `publicKeyJwk`
 * - verificationMethod entries with `publicKeyMultibase` (Ed25519 → converted to JWK)
 *
 * @param {object} didDocument - Resolved DID Document
 * @param {string} [kid] - Optional kid (verification method id) to match. If null, uses first assertionMethod or first verificationMethod.
 * @returns {{ publicKey: CryptoKey | KeyLike, jwk: object, verificationMethodId: string }}
 */
export async function extractVerificationKey(didDocument, kid) {
  const allMethods = didDocument.verificationMethod || [];

  // Determine which method to use
  let method = null;
  if (kid) {
    // Match by id or fragment
    method = allMethods.find(m => m.id === kid || m.id === `${didDocument.id}#${kid}` || m.id.endsWith(`#${kid}`));
  }
  if (!method) {
    // Prefer assertionMethod, fall back to first verificationMethod
    const assertionRefs = didDocument.assertionMethod || [];
    for (const ref of assertionRefs) {
      const refId = typeof ref === "string" ? ref : ref.id;
      method = allMethods.find(m => m.id === refId);
      if (method) break;
    }
  }
  if (!method && allMethods.length > 0) {
    method = allMethods[0];
  }
  if (!method) {
    throw Object.assign(
      new Error("No verification method found in DID Document"),
      { code: "did_no_verification_method" }
    );
  }

  // Extract JWK
  let jwk;
  if (method.publicKeyJwk) {
    jwk = method.publicKeyJwk;
  } else if (method.publicKeyMultibase) {
    // For did:key, the multibase key needs to be converted.
    // Re-resolve through the driver to get JWK form.
    // did:key documents from @digitalbazaar/did-method-key include publicKeyMultibase
    // but not publicKeyJwk by default. We handle Ed25519 and P-256.
    jwk = await multibaseToJwk(method.publicKeyMultibase, method.type);
  } else {
    throw Object.assign(
      new Error(`Verification method ${method.id} has no publicKeyJwk or publicKeyMultibase`),
      { code: "did_key_extraction_failed" }
    );
  }

  // Determine algorithm from key type
  if (!jwk.alg) {
    if (jwk.kty === "EC" && jwk.crv === "P-256") jwk.alg = "ES256";
    else if (jwk.kty === "EC" && jwk.crv === "P-384") jwk.alg = "ES384";
    else if (jwk.kty === "OKP" && jwk.crv === "Ed25519") jwk.alg = "EdDSA";
  }

  const publicKey = await jose.importJWK(jwk, jwk.alg);
  return { publicKey, jwk, verificationMethodId: method.id };
}

/**
 * Convert a multibase-encoded public key to JWK.
 * Handles Ed25519VerificationKey2020 and Multikey types.
 */
async function multibaseToJwk(multibase, type) {
  // multibase starts with 'z' (base58btc) for most DID methods
  if (!multibase.startsWith("z")) {
    throw Object.assign(
      new Error(`Unsupported multibase encoding: ${multibase[0]}`),
      { code: "did_key_extraction_failed" }
    );
  }

  // For Ed25519 keys encoded as multibase, the first two bytes after decoding
  // are the multicodec prefix 0xed01. The remaining 32 bytes are the raw key.
  // We use base58btc decoding.
  const { base58btc } = await import("multiformats/bases/base58");
  const decoded = base58btc.decode(multibase);

  // Check multicodec prefix
  if (decoded[0] === 0xed && decoded[1] === 0x01) {
    // Ed25519 public key
    const rawKey = decoded.slice(2);
    return {
      kty: "OKP",
      crv: "Ed25519",
      x: Buffer.from(rawKey).toString("base64url"),
      alg: "EdDSA",
    };
  } else if (decoded[0] === 0x80 && decoded[1] === 0x24) {
    // P-256 public key (compressed)
    // For Phase 1, we only need Ed25519 and raw P-256 JWK keys
    throw Object.assign(
      new Error("Compressed P-256 multibase keys not yet supported; use publicKeyJwk"),
      { code: "did_key_extraction_failed" }
    );
  }

  throw Object.assign(
    new Error(`Unknown multicodec prefix in multibase key`),
    { code: "did_key_extraction_failed" }
  );
}

/**
 * Clear the DID cache (for testing).
 */
export async function clearDIDCache() {
  const pool = getPool();
  await pool.query(`DELETE FROM portauth_did_cache`);
}
