import * as jose from "jose";
import { v4 as uuidv4 } from "uuid";
// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { getPool } from "../db/pool.js";

function normalizePurpose(purpose) {
  if (!["audit", "governance-manifest"].includes(purpose)) {
    throw new Error(`Unsupported engine signing key purpose: ${purpose}`);
  }
  return purpose;
}

function buildKid(purpose) {
  return `engine:${purpose}:${uuidv4().slice(0, 12)}`;
}

async function importStoredPrivateKey(row) {
  const privateJwk = typeof row.private_jwk === "string" ? JSON.parse(row.private_jwk) : row.private_jwk;
  return jose.importJWK(privateJwk, row.algorithm);
}

// Module-scope cache so we do not re-import the JWK on every signing call.
const purposeKeyCache = new Map();
const kidKeyCache = new Map();

export function clearEngineKeyCache() {
  purposeKeyCache.clear();
  kidKeyCache.clear();
}

export async function getOrCreateEngineSigningKey(purpose) {
  const normalizedPurpose = normalizePurpose(purpose);
  if (purposeKeyCache.has(normalizedPurpose)) {
    return purposeKeyCache.get(normalizedPurpose);
  }
  const pool = getPool();

  const { rows } = await pool.query(
    `SELECT kid, algorithm, public_jwk, private_jwk
     FROM portauth_engine_signing_keys
     WHERE purpose = $1 AND active = TRUE
     ORDER BY created_at DESC
     LIMIT 1`,
    [normalizedPurpose]
  );

  if (rows.length > 0) {
    const row = rows[0];
    const entry = {
      kid: row.kid,
      algorithm: row.algorithm,
      publicJwk: row.public_jwk,
      privateKey: await importStoredPrivateKey(row),
    };
    purposeKeyCache.set(normalizedPurpose, entry);
    kidKeyCache.set(entry.kid, { ...entry, purpose: normalizedPurpose, active: true });
    return entry;
  }

  const created = await createEngineSigningKey(normalizedPurpose);
  purposeKeyCache.set(normalizedPurpose, created);
  kidKeyCache.set(created.kid, { ...created, purpose: normalizedPurpose, active: true });
  return created;
}

export async function createEngineSigningKey(purpose) {
  const normalizedPurpose = normalizePurpose(purpose);
  const algorithm = "ES256";
  const { publicKey, privateKey } = await jose.generateKeyPair(algorithm, { extractable: true });
  const publicJwk = await jose.exportJWK(publicKey);
  const privateJwk = await jose.exportJWK(privateKey);
  const kid = buildKid(normalizedPurpose);

  publicJwk.kid = kid;
  publicJwk.alg = algorithm;
  publicJwk.use = "sig";
  privateJwk.kid = kid;
  privateJwk.alg = algorithm;

  const pool = getPool();
  await pool.query(
    `INSERT INTO portauth_engine_signing_keys (kid, purpose, algorithm, public_jwk, private_jwk)
     VALUES ($1, $2, $3, $4, $5)`,
    [kid, normalizedPurpose, algorithm, JSON.stringify(publicJwk), JSON.stringify(privateJwk)]
  );

  return { kid, algorithm, publicJwk, privateKey };
}

export async function getEngineSigningKeyByKid(kid) {
  if (kidKeyCache.has(kid)) {
    return kidKeyCache.get(kid);
  }
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT kid, purpose, algorithm, public_jwk, private_jwk, active
     FROM portauth_engine_signing_keys
     WHERE kid = $1
     LIMIT 1`,
    [kid]
  );

  if (rows.length === 0) {
    return null;
  }

  const row = rows[0];
  const entry = {
    kid: row.kid,
    purpose: row.purpose,
    algorithm: row.algorithm,
    publicJwk: row.public_jwk,
    privateKey: await importStoredPrivateKey(row),
    active: row.active,
  };
  kidKeyCache.set(kid, entry);
  return entry;
}

export async function getEnginePublicKeys(purpose) {
  const normalizedPurpose = normalizePurpose(purpose);
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT public_jwk
     FROM portauth_engine_signing_keys
     WHERE purpose = $1
     ORDER BY created_at DESC`,
    [normalizedPurpose]
  );
  return rows.map((row) => row.public_jwk);
}
