// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { getPool } from "../db/pool.js";

/**
 * Plan 3: derive the governance manifest content from persistent state
 * (portauth_trusted_issuers and portauth_mapping_profiles) instead of from a
 * hardcoded literal. Falls back to empty state when DB is unavailable so
 * callers can still produce a structurally-valid manifest in dev/test.
 */

export async function loadTrustedIssuerSummary() {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      `SELECT issuer_id, trust_tier, trusted_for_permissions,
              COALESCE(revocation_mechanism, 'introspection') AS revocation_mechanism
       FROM portauth_trusted_issuers
       WHERE active = TRUE
       ORDER BY trust_tier, issuer_id`,
    );
    const byTier = { 1: [], 2: [], 3: [] };
    for (const row of rows) {
      const t = Number(row.trust_tier);
      if (!byTier[t]) continue;
      byTier[t].push({
        issuerId: row.issuer_id,
        permissions: row.trusted_for_permissions,
        revocationMechanism: row.revocation_mechanism,
      });
    }
    return byTier;
  } catch (_) {
    return { 1: [], 2: [], 3: [] };
  }
}

export async function loadMappingProfileSummary() {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      `SELECT profile_id, semantic_field, local_field, field_type, trusted, valid_until
       FROM portauth_mapping_profiles
       WHERE active = TRUE
       ORDER BY profile_id, semantic_field`,
    );
    const profiles = new Map();
    for (const row of rows) {
      if (!profiles.has(row.profile_id)) {
        profiles.set(row.profile_id, {
          id: row.profile_id,
          status: "active",
          fields: {},
        });
      }
      profiles.get(row.profile_id).fields[row.semantic_field] = {
        localField: row.local_field,
        type: row.field_type,
        trusted: row.trusted !== false,
        validUntil: row.valid_until || null,
      };
    }
    return [...profiles.values()];
  } catch (_) {
    return [];
  }
}

let manifestRevision = 0;
export function bumpGovernanceRevision() {
  manifestRevision += 1;
  return manifestRevision;
}
export function currentGovernanceRevision() {
  return manifestRevision;
}
