// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { evaluateConstraints } from "./constraintEvaluator.js";
import { getPool } from "../db/pool.js";

/**
 * Apply the most-restrictive-wins merge between credential constraints and
 * receiver-local policy constraints.
 *
 * Local policies are expressed using the same core constraint objects as
 * the credential. No separate rule language is introduced.
 *
 * The effective authorization is the intersection:
 * - Credential defines the ceiling
 * - Local policy can only lower the ceiling
 *
 * @param {object} credentialPayload - normalized credential payload
 * @param {object} requestContext - the evaluation request context
 * @returns {{ localPolicyApplied: boolean, localPolicyDetail: object | null, denied: boolean, error?: string, constraintResults?: object[] }}
 */
export async function applyLocalPolicyMerge(credentialPayload, requestContext) {
  const pool = getPool();
  const requestedAction = requestContext?.action || null;

  // Fetch active local policies
  const { rows: policies } = await pool.query(
    `SELECT id, name, target_permissions, constraints
     FROM portauth_local_policies
     WHERE active = TRUE`
  );

  if (policies.length === 0) {
    return { localPolicyApplied: false, localPolicyDetail: null, denied: false };
  }

  // Filter to policies that apply to the credential's permissions
  const applicablePolicies = policies.filter(policy => {
    if (!policy.target_permissions || policy.target_permissions.length === 0) {
      return true; // applies to all permissions
    }
    if (requestedAction) {
      return policy.target_permissions.includes(requestedAction);
    }
    return credentialPayload.permissions.some((permission) => policy.target_permissions.includes(permission));
  });

  if (applicablePolicies.length === 0) {
    return { localPolicyApplied: false, localPolicyDetail: null, denied: false };
  }

  // Collect all local constraints, then evaluate them against the request context
  const allLocalConstraints = applicablePolicies.flatMap(p =>
    (Array.isArray(p.constraints) ? p.constraints : []).map(c => ({ ...c, _policyName: p.name, _policyId: p.id }))
  );

  const evaluation = await evaluateConstraints(
    allLocalConstraints.map(({ _policyName, _policyId, ...c }) => c),
    requestContext
  );

  if (!evaluation.pass) {
    // Local policy caused denial
    const failedResult = evaluation.results.find(r => !r.pass);
    const failedConstraint = allLocalConstraints[evaluation.results.indexOf(failedResult)];

    return {
      localPolicyApplied: true,
      localPolicyDetail: {
        policyId: failedConstraint?._policyId,
        policyName: failedConstraint?._policyName,
        failedConstraint: failedResult,
      },
      denied: true,
      error: "local_policy_denied",
      constraintResults: evaluation.results,
    };
  }

  return {
    localPolicyApplied: true,
    localPolicyDetail: { policiesEvaluated: applicablePolicies.map(p => p.name) },
    denied: false,
    constraintResults: evaluation.results,
  };
}
