// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

/**
 * Plan 1: hardened revocation introspection client for Tier 1 plain JWT.
 *
 * Honors per-issuer overrides for timeout, retry count, and failure mode,
 * with env-var defaults:
 *   PORTAUTH_TIER1_REVOCATION_TIMEOUT_MS  (default 20)
 *   PORTAUTH_TIER1_REVOCATION_RETRIES     (default 0)
 *   PORTAUTH_TIER1_REVOCATION_FAILURE_MODE (open|closed, default open)
 *
 * Outcomes (returned as { outcome, errorCode? }):
 *   - "active"      credential is active (not revoked)
 *   - "revoked"     credential explicitly revoked
 *   - "unavailable" introspection endpoint failed after retries
 *   - "skipped"     no endpoint configured or revocation check disabled
 *
 * When outcome is "unavailable" and failureMode is "closed", the caller
 * MUST deny the request with errorCode tier1_revocation_unavailable.
 */

function envInt(name, defaultValue) {
  const raw = process.env[name];
  if (raw === undefined || raw === null || raw === "") return defaultValue;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) ? n : defaultValue;
}

function envFailureMode() {
  const raw = (process.env.PORTAUTH_TIER1_REVOCATION_FAILURE_MODE || "open").toLowerCase();
  return raw === "closed" ? "closed" : "open";
}

export function resolveRevocationConfig({ issuerOverrides = {}, callerOptions = {} } = {}) {
  return {
    timeoutMs:
      callerOptions.revocationTimeoutMs
      ?? issuerOverrides.revocation_timeout_ms
      ?? envInt("PORTAUTH_TIER1_REVOCATION_TIMEOUT_MS", 20),
    retries:
      callerOptions.revocationRetries
      ?? issuerOverrides.revocation_retries
      ?? envInt("PORTAUTH_TIER1_REVOCATION_RETRIES", 0),
    failureMode:
      callerOptions.revocationFailureMode
      ?? issuerOverrides.revocation_failure_mode
      ?? envFailureMode(),
  };
}

export async function checkTier1Revocation({
  introspectionUrl,
  credentialId,
  config,
  fetchImpl = globalThis.fetch,
}) {
  if (!introspectionUrl) {
    return { outcome: "skipped" };
  }

  const attempts = Math.max(0, config.retries) + 1;
  let lastErrorMessage = null;

  for (let attempt = 0; attempt < attempts; attempt++) {
    try {
      const resp = await fetchImpl(introspectionUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ credentialId }),
        signal: AbortSignal.timeout(config.timeoutMs),
      });
      if (!resp.ok) {
        lastErrorMessage = `introspection responded ${resp.status}`;
        continue;
      }
      const body = await resp.json();
      if (body.active === false || body.revoked === true) {
        return { outcome: "revoked" };
      }
      return { outcome: "active" };
    } catch (err) {
      lastErrorMessage = err?.message || String(err);
    }
  }

  return {
    outcome: "unavailable",
    error: lastErrorMessage || "introspection unavailable",
  };
}
