// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { closePool, getPool } from "../db/pool.js";

/**
 * Semantic Resolution Layer (BR-9)
 *
 * Translates semantic identifiers from signed credentials (e.g., "core.amount")
 * to receiver-local request-context field paths (e.g., "claimAmount") using
 * governed mapping profiles.
 *
 * Fail-closed semantics:
 *   - Unknown semantic identifier → semantic_identifier_unknown
 *   - Missing mapping alias → semantic_alias_missing
 *   - Type mismatch → semantic_type_mismatch
 *   - Invalid/stale profile → mapping_profile_invalid
 */

/**
 * In-memory mapping profile cache.
 * Loaded from DB on first use and on explicit reload.
 * Structure: { [semanticField]: { localField, type, profileId } }
 */
let mappingCache = null;
let cacheLoadedAt = 0;
const CACHE_TTL_MS = 60_000; // 1 minute
const SEMANTIC_PREFIXES = ["core.", "insurance.", "aerospace.", "supply_chain."];

export function buildMappingCacheFromRows(rows, now = new Date()) {
  const mappings = new Map();

  for (const row of rows) {
    const current = mappings.get(row.semantic_field);
    const validUntil = row.valid_until ? new Date(row.valid_until) : null;
    const invalid = row.trusted === false || (validUntil && validUntil <= now);

    const next = {
      localField: row.local_field,
      type: row.field_type,
      profileId: row.profile_id,
      trusted: row.trusted !== false,
      validUntil: row.valid_until || null,
      errorCode: invalid ? "mapping_profile_invalid" : null,
    };

    if (current && (
      current.localField !== next.localField
      || current.type !== next.type
      || current.profileId !== next.profileId
    )) {
      mappings.set(row.semantic_field, {
        ...next,
        errorCode: "semantic_alias_conflict",
      });
      continue;
    }

    mappings.set(row.semantic_field, next);
  }

  return mappings;
}

function defaultMappings() {
  return new Map([
    // Core MVV — request-context attributes
    ["core.amount", { localField: "claimAmount", type: "number", profileId: "mvv-core" }],
    ["core.currency_code", { localField: "currency", type: "string", profileId: "mvv-core" }],
    ["core.currency", { localField: "currency", type: "string", profileId: "mvv-core" }],
    ["core.request_time", { localField: "timestamp", type: "string", profileId: "mvv-core" }],
    ["core.timestamp", { localField: "timestamp", type: "string", profileId: "mvv-core" }],
    ["core.resource_id", { localField: "resource", type: "string", profileId: "mvv-core" }],
    ["core.resource_type", { localField: "resourceType", type: "string", profileId: "mvv-core" }],
    ["core.action", { localField: "action", type: "string", profileId: "mvv-core" }],
    ["core.workflow_id", { localField: "workflowId", type: "string", profileId: "mvv-core" }],
    ["core.workflow_role", { localField: "workflowRole", type: "string", profileId: "mvv-core" }],
    ["core.workflow_step_id", { localField: "workflowStepId", type: "string", profileId: "mvv-core" }],
    ["core.recipient_id", { localField: "recipientId", type: "string", profileId: "mvv-core" }],
    ["core.count", { localField: "count", type: "number", profileId: "mvv-core" }],
    ["core.quantity", { localField: "quantity", type: "number", profileId: "mvv-core" }],
    ["core.total_budget", { localField: "totalBudget", type: "number", profileId: "mvv-core" }],
    ["core.geo_region", { localField: "geoRegion", type: "string", profileId: "mvv-core" }],
    // Core MVV — credential-derived facts (enriched via contextEnricher)
    ["core.issuer_id", { localField: "__credential.issuerId", type: "string", profileId: "mvv-core" }],
    ["core.subject_id", { localField: "__credential.subjectId", type: "string", profileId: "mvv-core" }],
    ["core.presenter_id", { localField: "__credential.presenterId", type: "string", profileId: "mvv-core" }],
    ["core.audience_id", { localField: "__credential.audience", type: "string", profileId: "mvv-core" }],
    ["core.permission", { localField: "__credential.permission", type: "string", profileId: "mvv-core" }],
    ["core.valid_from", { localField: "__credential.validFrom", type: "string", profileId: "mvv-core" }],
    ["core.valid_until", { localField: "__credential.validUntil", type: "string", profileId: "mvv-core" }],
    ["core.delegator_id", { localField: "__credential.delegatorId", type: "string", profileId: "mvv-core" }],
    // Core MVV — request-envelope facts (enriched via contextEnricher)
    ["core.request_id", { localField: "__request.requestId", type: "string", profileId: "mvv-core" }],
    ["core.ip_address", { localField: "__request.ipAddress", type: "string", profileId: "mvv-core" }],
    // Insurance profile
    ["insurance.claimAmount", { localField: "claimAmount", type: "number", profileId: "insurance-claims-v1" }],
    ["insurance.claim_amount", { localField: "claimAmount", type: "number", profileId: "insurance-claims-v1" }],
    ["insurance.claimType", { localField: "claimType", type: "string", profileId: "insurance-claims-v1" }],
    ["insurance.claim_type", { localField: "claimType", type: "string", profileId: "insurance-claims-v1" }],
    ["insurance.claimId", { localField: "resource", type: "string", profileId: "insurance-claims-v1" }],
    ["insurance.claim_id", { localField: "resource", type: "string", profileId: "insurance-claims-v1" }],
  ]);
}

function isReservedSemanticIdentifier(fieldPath) {
  return SEMANTIC_PREFIXES.some((prefix) => fieldPath.startsWith(prefix));
}

/**
 * Load mapping profiles from the portauth_mapping_profiles table.
 * Falls back to default MVV mappings if no profiles exist.
 */
async function loadMappings() {
  const now = Date.now();
  if (mappingCache && (now - cacheLoadedAt) < CACHE_TTL_MS) {
    return mappingCache;
  }

  // Check if the mapping profiles table exists (graceful fallback)
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      `SELECT id, profile_id, semantic_field, local_field, field_type, active, trusted, valid_until
       FROM portauth_mapping_profiles WHERE active = TRUE`
    );

    if (rows.length > 0) {
      mappingCache = buildMappingCacheFromRows(rows);
      cacheLoadedAt = now;
      return mappingCache;
    }
  } catch (_) {
    // Table doesn't exist yet or the local test DB is unavailable — use defaults
    await closePool();
  }

  // Default MVV + insurance profile mappings (built-in)
  mappingCache = defaultMappings();
  cacheLoadedAt = now;
  return mappingCache;
}

/**
 * Resolve a semantic field identifier to a local context field path.
 *
 * If the field is already a direct path in the context (not a semantic identifier),
 * it is returned as-is. Semantic identifiers are recognized by matching against
 * the loaded mapping profiles.
 *
 * @param {string} semanticField - field path from the credential constraint
 * @param {object} context - the request context
 * @returns {{ resolved: true, localField: string, value: any } | { resolved: false, error: string, errorCode: string }}
 */
export async function resolveSemanticField(semanticField, context) {
  const mappings = await loadMappings();
  const mapping = mappings.get(semanticField);

  if (mapping?.errorCode) {
    return {
      resolved: false,
      error: `Semantic mapping for '${semanticField}' is invalid: ${mapping.errorCode}`,
      errorCode: mapping.errorCode,
    };
  }

  if (mapping) {
    if (!mapping.localField) {
      return {
        resolved: false,
        error: `Semantic identifier '${semanticField}' has no local alias`,
        errorCode: "semantic_alias_missing",
      };
    }

    // Resolve the mapped local field in context
    const localValue = resolveDirectPath(mapping.localField, context);

    if (localValue === undefined) {
      return {
        resolved: false,
        error: `Semantic field '${semanticField}' maps to '${mapping.localField}' but that field is missing from context`,
        errorCode: "context_field_missing",
      };
    }

    // Type check
    if (mapping.type) {
      const actualType = typeof localValue;
      if (mapping.type === "number" && actualType !== "number") {
        return {
          resolved: false,
          error: `Semantic field '${semanticField}' expects type '${mapping.type}' but got '${actualType}'`,
          errorCode: "semantic_type_mismatch",
        };
      }
      if (mapping.type === "string" && actualType !== "string") {
        return {
          resolved: false,
          error: `Semantic field '${semanticField}' expects type '${mapping.type}' but got '${actualType}'`,
          errorCode: "semantic_type_mismatch",
        };
      }
      if (mapping.type === "boolean" && actualType !== "boolean") {
        return {
          resolved: false,
          error: `Semantic field '${semanticField}' expects type '${mapping.type}' but got '${actualType}'`,
          errorCode: "semantic_type_mismatch",
        };
      }
    }

    return { resolved: true, localField: mapping.localField, value: localValue };
  }

  if (isReservedSemanticIdentifier(semanticField)) {
    return {
      resolved: false,
      error: `Semantic identifier '${semanticField}' has no mapping to a local context field`,
      errorCode: "semantic_identifier_unknown",
    };
  }

  const directValue = resolveDirectPath(semanticField, context);
  if (directValue !== undefined) {
    return { resolved: true, localField: semanticField, value: directValue };
  }

  return {
    resolved: false,
    error: `Field '${semanticField}' not found in context`,
    errorCode: "context_field_missing",
  };
}

/**
 * Resolve a dotted field path directly from the context object.
 */
function resolveDirectPath(fieldPath, context) {
  const parts = fieldPath.split(".");
  let current = context;
  for (const part of parts) {
    if (current === null || current === undefined || typeof current !== "object") return undefined;
    current = current[part];
  }
  return current;
}

/**
 * Clear the mapping cache (for testing).
 */
export function clearMappingCache() {
  mappingCache = null;
  cacheLoadedAt = 0;
}
