// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import * as jose from "jose";
import { getPool } from "../db/pool.js";

/**
 * Plan 2: State Authority protocol client.
 *
 * Fetches a signed proof of the current counter value from an external
 * authority that maintains shared mutable state across multiple receivers,
 * and verifies the proof signature against the authority's JWKS.
 *
 * Proof JWS payload schema (canonical):
 *   {
 *     "iss": "<authority_id>",
 *     "counterKey": "<key>",
 *     "metric": "amount" | "count",
 *     "windowStart": "<iso-8601>",
 *     "value": <number>,
 *     "iat": <unix-seconds>
 *   }
 *
 * Outcomes:
 *   - { ok: true, value, proof }      proof accepted
 *   - { ok: false, errorCode, error } proof rejected or authority unreachable
 *
 * Error codes:
 *   - state_authority_untrusted    no record in portauth_state_authorities
 *   - state_authority_unreachable  HTTP fetch failed
 *   - state_authority_proof_invalid signature, schema, or freshness check failed
 */

async function loadAuthority(authorityId) {
  try {
    const pool = getPool();
    const { rows } = await pool.query(
      `SELECT authority_id, base_url, jwks_uri
       FROM portauth_state_authorities
       WHERE authority_id = $1 AND active = TRUE`,
      [authorityId],
    );
    if (rows.length === 0) return null;
    return rows[0];
  } catch (_) {
    return null;
  }
}

async function fetchProof({ baseUrl, authorityId, counterKey, windowStart, fetchImpl }) {
  const url = `${baseUrl.replace(/\/$/, "")}/proofs`
    + `?authorityId=${encodeURIComponent(authorityId)}`
    + `&counterKey=${encodeURIComponent(counterKey)}`
    + `&windowStart=${encodeURIComponent(windowStart)}`;
  const resp = await fetchImpl(url, {
    method: "GET",
    headers: { "Accept": "application/jose" },
  });
  if (!resp.ok) {
    throw new Error(`state authority responded ${resp.status}`);
  }
  return await resp.text();
}

async function verifyProofJws(jws, jwksUri, fetchImpl) {
  const resp = await fetchImpl(jwksUri, { method: "GET" });
  if (!resp.ok) throw new Error(`jwks fetch failed: ${resp.status}`);
  const jwks = await resp.json();
  const keySet = jose.createLocalJWKSet(jwks);
  const { payload } = await jose.compactVerify(jws, keySet);
  return JSON.parse(new TextDecoder().decode(payload));
}

export async function fetchCurrentValueFromAuthority({
  authorityId,
  counterKey,
  windowStart,
  maxAgeMs = 30_000,
  fetchImpl = globalThis.fetch,
  authorityRecord = null,
}) {
  const authority = authorityRecord || await loadAuthority(authorityId);
  if (!authority) {
    return { ok: false, errorCode: "state_authority_untrusted", error: `unknown authority ${authorityId}` };
  }
  if (!authority.jwks_uri) {
    return { ok: false, errorCode: "state_authority_untrusted", error: `authority ${authorityId} has no jwks_uri` };
  }

  let jws;
  try {
    jws = await fetchProof({
      baseUrl: authority.base_url,
      authorityId,
      counterKey,
      windowStart,
      fetchImpl,
    });
  } catch (err) {
    return { ok: false, errorCode: "state_authority_unreachable", error: err.message };
  }

  let proof;
  try {
    proof = await verifyProofJws(jws, authority.jwks_uri, fetchImpl);
  } catch (err) {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: `signature verification failed: ${err.message}` };
  }

  if (proof.iss !== authorityId) {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: `proof iss mismatch: ${proof.iss} != ${authorityId}` };
  }
  if (proof.counterKey !== counterKey) {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: "proof counterKey mismatch" };
  }
  if (proof.windowStart !== windowStart) {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: "proof windowStart mismatch" };
  }
  if (typeof proof.value !== "number" || !Number.isFinite(proof.value)) {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: "proof value not numeric" };
  }
  if (typeof proof.iat !== "number") {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: "proof missing iat" };
  }
  const ageMs = Date.now() - proof.iat * 1000;
  if (ageMs > maxAgeMs) {
    return { ok: false, errorCode: "state_authority_proof_invalid", error: `proof too old (${ageMs}ms > ${maxAgeMs}ms)` };
  }

  return { ok: true, value: proof.value, proof, jws };
}

export async function recordConsumedProof({ authorityId, counterKey, windowStart, metric, value, jws, iat, requestId }) {
  try {
    const pool = getPool();
    await pool.query(
      `INSERT INTO portauth_state_proofs
         (authority_id, counter_key, window_start, metric, reported_value, proof_jws, proof_issued_at, request_id)
       VALUES ($1, $2, $3, $4, $5, $6, to_timestamp($7), $8)
       ON CONFLICT DO NOTHING`,
      [authorityId, counterKey, windowStart, metric, value, jws, iat, requestId || null],
    );
  } catch (_) {
    // best-effort durability; errors are non-fatal for the authorization decision
  }
}
