// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

/**
 * Plan 7: workflow policy evaluation.
 *
 * A workflow policy declares (1) the required principal roles and the
 * permission each principal must hold, and (2) a combinator that turns a
 * vector of per-credential sub-decisions into a single workflow decision.
 *
 * Supported combinators:
 *   - requireAll: every sub-decision must be allow
 *   - requireAny: at least one sub-decision must be allow
 *   - threshold:  at least N sub-decisions must be allow
 */

export function validateRoleCoverage(policy, presentedRoles) {
  const required = (policy.required_roles || []).map((r) => r.role);
  const presented = new Set(presentedRoles);
  const missing = required.filter((r) => !presented.has(r));
  if (missing.length > 0) {
    return { ok: false, errorCode: "workflow_role_mismatch", detail: `Missing required roles: ${missing.join(", ")}` };
  }
  const allowed = new Set(required);
  const extra = presentedRoles.filter((r) => !allowed.has(r));
  if (extra.length > 0) {
    return { ok: false, errorCode: "workflow_role_mismatch", detail: `Unexpected roles: ${extra.join(", ")}` };
  }
  return { ok: true };
}

export function combineSubDecisions(policy, subDecisions) {
  const allows = subDecisions.filter((d) => d.decision === "allow").length;
  const total = subDecisions.length;

  switch (policy.combinator) {
    case "requireAll":
      return { decision: allows === total ? "allow" : "deny", reason: `requireAll: ${allows}/${total} allow` };
    case "requireAny":
      return { decision: allows >= 1 ? "allow" : "deny", reason: `requireAny: ${allows}/${total} allow` };
    case "threshold": {
      const n = Number(policy.threshold_n || 0);
      return { decision: allows >= n ? "allow" : "deny", reason: `threshold(${n}): ${allows}/${total} allow` };
    }
    default:
      return { decision: "deny", reason: `unknown combinator: ${policy.combinator}` };
  }
}
