// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { X509Certificate } from "node:crypto";

function normalizePemText(value) {
  return String(value || "").replace(/\\n/g, "\n").trim();
}

export function pemCertificatesToX5c(pemText) {
  const matches = normalizePemText(pemText).match(/-----BEGIN CERTIFICATE-----[\s\S]+?-----END CERTIFICATE-----/g) || [];
  return matches.map((pem) => pem
    .replace(/-----BEGIN CERTIFICATE-----/g, "")
    .replace(/-----END CERTIFICATE-----/g, "")
    .replace(/\s+/g, ""));
}

export function x5cToPem(x5cEntry) {
  const wrapped = String(x5cEntry).match(/.{1,64}/g)?.join("\n") || "";
  return `-----BEGIN CERTIFICATE-----\n${wrapped}\n-----END CERTIFICATE-----`;
}

export function parseX5cChain(x5c = []) {
  if (!Array.isArray(x5c) || x5c.length === 0) {
    throw Object.assign(new Error("JWT header missing x5c certificate chain"), { code: "x509_chain_missing" });
  }

  return x5c.map((entry) => new X509Certificate(x5cToPem(entry)));
}

export function certificateFingerprintSha256(cert) {
  return cert.fingerprint256.replace(/:/g, "").toLowerCase();
}

function parseTrustAnchors(options = {}) {
  const anchors = [];
  const pemSources = [
    options.trustAnchorsPem,
    options.trustAnchorPem,
    process.env.PORTAUTH_X509_TRUST_ANCHORS_PEM,
    process.env.PORTAUTH_X509_TRUST_ANCHOR_PEM,
  ].filter(Boolean);

  for (const pemSource of pemSources) {
    for (const x5c of pemCertificatesToX5c(pemSource)) {
      anchors.push(new X509Certificate(x5cToPem(x5c)));
    }
  }

  const fingerprintSources = [
    options.trustAnchorSha256,
    options.trustAnchorFingerprint,
    process.env.PORTAUTH_X509_TRUST_ANCHOR_SHA256,
    process.env.PORTAUTH_X509_TRUST_ANCHOR_FINGERPRINT,
  ].filter(Boolean);

  const fingerprints = fingerprintSources
    .flatMap((source) => String(source).split(","))
    .map((item) => item.replace(/:/g, "").trim().toLowerCase())
    .filter(Boolean);

  return { anchors, fingerprints };
}

function validateCertificateTime(cert, now) {
  const from = new Date(cert.validFrom);
  const to = new Date(cert.validTo);
  if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime())) {
    return { pass: false, error: "Certificate validity period is not parseable", errorCode: "x509_certificate_invalid" };
  }
  if (now < from) {
    return { pass: false, error: "Certificate is not yet valid", errorCode: "x509_certificate_expired" };
  }
  if (now > to) {
    return { pass: false, error: "Certificate has expired", errorCode: "x509_certificate_expired" };
  }
  return { pass: true };
}

function validateKeyUsage(cert, options = {}) {
  if (options.enforceKeyUsage === false) {
    return { pass: true };
  }

  const usages = cert.keyUsage || [];
  if (usages.length === 0) {
    return { pass: true };
  }

  const acceptable = usages.some((usage) => {
    const value = String(usage).toLowerCase();
    return value.includes("digitalsignature")
      || value.includes("digital signature")
      || value.includes("code signing")
      || value.includes("client authentication")
      || value.includes("1.3.6.1.5.5.7.3.2")
      || value.includes("1.3.6.1.5.5.7.3.3");
  });

  if (!acceptable) {
    return {
      pass: false,
      error: `Certificate key usage does not permit digital signatures: ${usages.join(", ")}`,
      errorCode: "x509_key_usage_invalid",
    };
  }

  return { pass: true };
}

function verifyChainSignatures(chain) {
  for (let i = 0; i < chain.length - 1; i++) {
    if (!chain[i].verify(chain[i + 1].publicKey)) {
      return {
        pass: false,
        error: `Certificate chain signature failed at depth ${i}`,
        errorCode: "x509_chain_invalid",
      };
    }
  }
  return { pass: true };
}

function findMatchingAnchor(chain, anchors, fingerprints) {
  const chainTail = chain[chain.length - 1];
  const tailFingerprint = certificateFingerprintSha256(chainTail);

  if (fingerprints.includes(tailFingerprint)) {
    return { anchor: chainTail, fingerprint: tailFingerprint, check: "fingerprint" };
  }

  for (const anchor of anchors) {
    const anchorFingerprint = certificateFingerprintSha256(anchor);
    if (fingerprints.includes(anchorFingerprint)) {
      if (tailFingerprint === anchorFingerprint || chainTail.verify(anchor.publicKey)) {
        return { anchor, fingerprint: anchorFingerprint, check: "configured-anchor" };
      }
    }

    if (tailFingerprint === anchorFingerprint || chainTail.verify(anchor.publicKey)) {
      return { anchor, fingerprint: anchorFingerprint, check: "configured-anchor" };
    }
  }

  return null;
}

export function certificateHasUriSan(cert, uri) {
  if (!uri || !cert.subjectAltName) return false;
  return cert.subjectAltName
    .split(/,\s*/)
    .some((entry) => entry === `URI:${uri}`);
}

export function validateCertificateIdentity(cert, issuerId, trustedIssuer = {}) {
  const configuredSan = trustedIssuer.x509_san_uri || trustedIssuer.metadata?.x509SanUri;
  if (configuredSan) {
    return certificateHasUriSan(cert, configuredSan)
      ? { pass: true, check: "configured-san-uri" }
      : {
          pass: false,
          error: `Certificate SAN does not include configured URI ${configuredSan}`,
          errorCode: "x509_subject_mismatch",
        };
  }

  if (issuerId?.startsWith("http://") || issuerId?.startsWith("https://")) {
    const host = new URL(issuerId).hostname;
    if (cert.checkHost(host)) {
      return { pass: true, check: "issuer-host-san" };
    }
  }

  if (issuerId && certificateHasUriSan(cert, issuerId)) {
    return { pass: true, check: "issuer-uri-san" };
  }

  if (trustedIssuer.x509_subject && cert.subject.includes(trustedIssuer.x509_subject)) {
    return { pass: true, check: "configured-subject" };
  }

  return {
    pass: false,
    error: "Certificate identity is not bound to the trusted issuer record",
    errorCode: "x509_subject_mismatch",
  };
}

export function verifyX509ChainFromHeader(header, options = {}) {
  try {
    const chain = parseX5cChain(header?.x5c);
    const now = options.now || new Date();

    for (const cert of chain) {
      const timeCheck = validateCertificateTime(cert, now);
      if (!timeCheck.pass) return timeCheck;
    }

    const usageCheck = validateKeyUsage(chain[0], options);
    if (!usageCheck.pass) return usageCheck;

    const signatureCheck = verifyChainSignatures(chain);
    if (!signatureCheck.pass) return signatureCheck;

    const { anchors, fingerprints } = parseTrustAnchors(options);
    if (anchors.length === 0 && fingerprints.length === 0) {
      return {
        pass: false,
        error: "No X.509 trust anchor configured",
        errorCode: "x509_trust_anchor_missing",
      };
    }

    const anchorMatch = findMatchingAnchor(chain, anchors, fingerprints);
    if (!anchorMatch) {
      return {
        pass: false,
        error: "Certificate chain does not terminate at a configured trust anchor",
        errorCode: "x509_chain_untrusted",
      };
    }

    return {
      pass: true,
      leafCertificate: chain[0],
      chain,
      trustAnchorFingerprint: anchorMatch.fingerprint,
      trustAnchorCheck: anchorMatch.check,
    };
  } catch (err) {
    return {
      pass: false,
      error: err.message,
      errorCode: err.code || "x509_chain_invalid",
    };
  }
}
