# Copyright contributors to the aiagent-portable-authorization project.
# SPDX-License-Identifier: MIT
# This code is generated by AI, edited by humans

import os
import time
import pytest
import httpx
import re

def get_admin_key(env_var="ADMIN_API_KEY"):
    return os.getenv(env_var, "dev-engine-key-change-me")

# Configuration - Defaults to local dev stack
BASE_URL = os.getenv("PORTAUTH_URL", "http://localhost:3200")
ISSUER_URL = os.getenv("PORTAUTH_ISSUER_URL", "http://localhost:3100")
ENGINE_URL = os.getenv("PORTAUTH_ENGINE_URL", BASE_URL)
ENGINE_ADMIN_TOKEN = get_admin_key("ADMIN_API_KEY")
ISSUER_ADMIN_TOKEN = os.getenv("ISSUER_ADMIN_API_KEY", "dev-issuer-key-change-me")
ADMIN_TOKEN = ENGINE_ADMIN_TOKEN  # Backwards compatibility for the fixture

# Test State - Persistent across test functions
test_state = {
    "vc": None,
    "vc_id": None,
    "policy_id": None
}

@pytest.fixture
def client():
    # Use a longer timeout for cloud cold-starts
    with httpx.Client(timeout=15.0, verify=True) as c:
        yield c

@pytest.fixture
def admin_headers():
    return {"Authorization": f"Bearer {ADMIN_TOKEN}"}

# ══════════════════════════════════════════════════════════════════════
# A. Administration
# ══════════════════════════════════════════════════════════════════════

def test_bb_01_register_issuer(client, admin_headers):
    """BB-01: Register primary trusted issuer."""
    internal_issuer = "http://portauth-issuer:3100"
    payload = {
        "issuerId": internal_issuer,
        "trustTier": 1,
        "trustedForPermissions": ["damage_assessment:read", "damage_assessment:write"],
        "label": "Local Dev Issuer",
        "jwksUri": f"{internal_issuer}/.well-known/jwks.json"
    }
    # Clean up first (ignore 404)
    import urllib.parse
    encoded_id = urllib.parse.quote(internal_issuer, safe='')
    client.delete(f"{ENGINE_URL}/admin/issuers/{encoded_id}", headers=admin_headers)
    
    r = client.post(f"{ENGINE_URL}/admin/issuers", json=payload, headers=admin_headers)
    assert r.status_code in [201, 409], f"Failed: {r.text}"

def test_bb_05_create_local_policy(client, admin_headers):
    """BB-05: Create local policy."""
    payload = {
        "name": "Limit High Claims",
        "constraints": [
            {"type": "NumericLimitConstraint", "field": "claimAmount", "operator": "lte", "value": 4500}
        ],
        "targetPermissions": ["damage_assessment:read"]
    }
    r = client.post(f"{ENGINE_URL}/admin/local-policy", json=payload, headers=admin_headers)
    assert r.status_code == 201
    test_state["policy_id"] = r.json()["id"]

# ══════════════════════════════════════════════════════════════════════
# B. Issuance
# ══════════════════════════════════════════════════════════════════════

def test_bb_10_issue_credential(client):
    """BB-10: Issue JWT credential."""
    payload = {
        "agentId": "agent-123",
        "permissions": ["damage_assessment:read"],
        "constraints": [
            {"type": "NumericLimitConstraint", "field": "claimAmount", "operator": "lte", "value": 5000},
            {"type": "EnumeratedListConstraint", "field": "claimType", "allowed": ["rear_end", "collision"]},
            {"type": "StringPatternConstraint", "field": "resource", "pattern": "/claims/CLM-2026-", "matchType": "prefix"}
        ]
    }
    # Note: Use the issuer admin token for issuance
    headers = {"Authorization": f"Bearer {ISSUER_ADMIN_TOKEN}"}
    r = client.post(f"{ISSUER_URL}/credentials/issue", json=payload, headers=headers)
    assert r.status_code == 201, f"Failed to issue: {r.text}"
    data = r.json()
    test_state["vc"] = data["credential"]
    test_state["vc_id"] = data["credentialId"]

# ══════════════════════════════════════════════════════════════════════
# C. Evaluation
# ══════════════════════════════════════════════════════════════════════

def test_bb_20_happy_path(client):
    """BB-20: Happy-path authorization."""
    assert test_state["vc"] is not None, "Credential missing from previous step"
    payload = {
        "credential": test_state["vc"],
        "presenterId": "agent-123",
        "requestContext": {
            "action": "damage_assessment:read",
            "resource": "/claims/CLM-2026-0001",
            "claimAmount": 4200,
            "claimType": "rear_end"
        }
    }
    r = client.post(f"{ENGINE_URL}/evaluate", json=payload)
    assert r.status_code == 200, f"Evaluation failed: {r.text}"
    assert r.json()["decision"] == "allow"

def test_bb_22_numeric_limit_denied(client):
    """BB-22: Numeric limit exceeded (local policy 4500 vs request 4700)."""
    assert test_state["vc"] is not None
    payload = {
        "credential": test_state["vc"],
        "presenterId": "agent-123",
        "requestContext": {
            "action": "damage_assessment:read",
            "resource": "/claims/CLM-2026-0001",
            "claimAmount": 4700, # Fails local policy (4500)
            "claimType": "rear_end"
        }
    }
    r = client.post(f"{ENGINE_URL}/evaluate", json=payload)
    assert r.status_code == 200
    assert r.json()["decision"] == "deny"
    assert r.json()["error"] == "local_policy_denied"

# ══════════════════════════════════════════════════════════════════════
# D. Audit
# ══════════════════════════════════════════════════════════════════════

def test_bb_40_audit(client, admin_headers):
    """BB-40: Retrieve audit record."""
    assert test_state["vc"] is not None
    payload = {
        "credential": test_state["vc"],
        "presenterId": "agent-123",
        "requestContext": {
            "action": "damage_assessment:read",
            "resource": "/claims/CLM-2026-0001",
            "claimAmount": 4200,
            "claimType": "rear_end"
        }
    }
    r = client.post(f"{ENGINE_URL}/evaluate", json=payload)
    audit_id = r.json()["auditRecordId"]
    
    # Wait a moment for background signing
    time.sleep(2)
    
    r_audit = client.get(f"{ENGINE_URL}/audit/records/{audit_id}", headers=admin_headers)
    assert r_audit.status_code == 200
    assert r_audit.json()["decision"] == "allow"
