// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { gunzipSync } from "node:zlib";
import { buildEncodedStatusListFromEntries, deriveStatusListUrl } from "../src/services/statusListPublisher.js";

function restoreEnv(name, value) {
  if (value === undefined) {
    delete process.env[name];
    return;
  }
  process.env[name] = value;
}

function readBit(encodedList, index) {
  const bitstring = gunzipSync(Buffer.from(encodedList, "base64url"));
  const byteIndex = Math.floor(index / 8);
  const bitIndex = 7 - (index % 8);
  return (bitstring[byteIndex] >> bitIndex) & 1;
}

describe("Status List Publisher", () => {
  it("sets revoked bits at the expected indexes", () => {
    const encodedList = buildEncodedStatusListFromEntries([
      { status_list_index: 0, revoked: true },
      { status_list_index: 3, revoked: true },
      { status_list_index: 9, revoked: true },
    ]);

    assert.equal(readBit(encodedList, 0), 1);
    assert.equal(readBit(encodedList, 3), 1);
    assert.equal(readBit(encodedList, 9), 1);
    assert.equal(readBit(encodedList, 1), 0);
  });

  it("builds an all-zero list when there are no revoked entries", () => {
    const encodedList = buildEncodedStatusListFromEntries([]);
    assert.equal(readBit(encodedList, 0), 0);
  });

  it("derives a default status list URL from ISSUER_ID when available", () => {
    const originalIssuerId = process.env.ISSUER_ID;
    const originalStatusListUrl = process.env.VC_STATUS_LIST_URL;
    const originalIssuerPublicUrl = process.env.ISSUER_PUBLIC_URL;

    process.env.ISSUER_ID = "https://issuer.example.com";
    delete process.env.VC_STATUS_LIST_URL;
    delete process.env.ISSUER_PUBLIC_URL;

    try {
      assert.equal(
        deriveStatusListUrl("revocation"),
        "https://issuer.example.com/.well-known/status-list/revocation"
      );
    } finally {
      restoreEnv("ISSUER_ID", originalIssuerId);
      restoreEnv("VC_STATUS_LIST_URL", originalStatusListUrl);
      restoreEnv("ISSUER_PUBLIC_URL", originalIssuerPublicUrl);
    }
  });
});
