/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

import { randomUUID } from "node:crypto";

export const A2A_VERSION = "1.0";
export const A2A_MEDIA_TYPE = "application/a2a+json";
export const EXTENSION_URI = "https://kyndryl-open-source.github.io/aiagent-portable-authorization/a2a/v1";

export const VC_FORMATS = Object.freeze([
  "tier1-jwt",
  "tier2-x509-jwt",
  "tier3-vc-jose",
]);

export const metadataKeys = Object.freeze({
  vc: `${EXTENSION_URI}/vc`,
  vcFormat: `${EXTENSION_URI}/vcFormat`,
  presenterId: `${EXTENSION_URI}/presenterId`,
  proofOfPossession: `${EXTENSION_URI}/proofOfPossession`,
  idempotencyKey: `${EXTENSION_URI}/idempotencyKey`,
  delegationChain: `${EXTENSION_URI}/delegationChain`,
});

const grpcCodeByHttpStatus = new Map([
  [400, "INVALID_ARGUMENT"],
  [401, "UNAUTHENTICATED"],
  [403, "PERMISSION_DENIED"],
  [404, "NOT_FOUND"],
  [409, "ALREADY_EXISTS"],
  [412, "FAILED_PRECONDITION"],
  [422, "INVALID_ARGUMENT"],
  [500, "INTERNAL"],
  [503, "UNAVAILABLE"],
]);

const engineErrorMap = new Map([
  ["authorization_denied", { httpStatus: 403, reason: "PORTAUTH_AUTHORIZATION_DENIED" }],
  ["validation_error", { httpStatus: 400, reason: "PORTAUTH_INVALID_REQUEST" }],
  ["credential_incomplete", { httpStatus: 422, reason: "PORTAUTH_CREDENTIAL_INCOMPLETE" }],
  ["signature_invalid", { httpStatus: 401, reason: "PORTAUTH_SIGNATURE_INVALID" }],
  ["credential_expired", { httpStatus: 401, reason: "PORTAUTH_CREDENTIAL_EXPIRED" }],
  ["issuer_untrusted", { httpStatus: 401, reason: "PORTAUTH_ISSUER_UNTRUSTED" }],
  ["audience_mismatch", { httpStatus: 401, reason: "PORTAUTH_AUDIENCE_MISMATCH" }],
  ["proof_of_possession_failed", { httpStatus: 401, reason: "PORTAUTH_PROOF_OF_POSSESSION_FAILED" }],
  ["subject_binding_mismatch", { httpStatus: 401, reason: "PORTAUTH_SUBJECT_BINDING_MISMATCH" }],
  ["credential_revoked", { httpStatus: 401, reason: "PORTAUTH_CREDENTIAL_REVOKED" }],
  ["tier1_revocation_unavailable", { httpStatus: 503, reason: "PORTAUTH_REVOCATION_UNAVAILABLE" }],
  ["x509_revocation_unavailable", { httpStatus: 503, reason: "PORTAUTH_REVOCATION_UNAVAILABLE" }],
  ["permission_denied", { httpStatus: 403, reason: "PORTAUTH_PERMISSION_DENIED" }],
  ["constraint_failed", { httpStatus: 403, reason: "PORTAUTH_CONSTRAINT_FAILED" }],
  ["context_field_missing", { httpStatus: 400, reason: "PORTAUTH_CONTEXT_FIELD_MISSING" }],
  ["numeric_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_NUMERIC_LIMIT_EXCEEDED" }],
  ["semantic_identifier_unknown", { httpStatus: 403, reason: "PORTAUTH_SEMANTIC_IDENTIFIER_UNKNOWN" }],
  ["temporal_window_violated", { httpStatus: 403, reason: "PORTAUTH_TEMPORAL_WINDOW_VIOLATED" }],
  ["enumerated_list_violated", { httpStatus: 403, reason: "PORTAUTH_ENUMERATED_LIST_VIOLATED" }],
  ["pattern_violated", { httpStatus: 403, reason: "PORTAUTH_PATTERN_VIOLATED" }],
  ["cumulative_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_CUMULATIVE_LIMIT_EXCEEDED" }],
  ["usage_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_USAGE_LIMIT_EXCEEDED" }],
  ["stateful_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_STATEFUL_LIMIT_EXCEEDED" }],
  ["local_policy_denied", { httpStatus: 403, reason: "PORTAUTH_LOCAL_POLICY_DENIED" }],
  ["delegation_widened", { httpStatus: 403, reason: "PORTAUTH_DELEGATION_WIDENED" }],
  ["delegation_chain_broken", { httpStatus: 401, reason: "PORTAUTH_DELEGATION_CHAIN_BROKEN" }],
  ["delegation_depth_exceeded", { httpStatus: 403, reason: "PORTAUTH_DELEGATION_DEPTH_EXCEEDED" }],
  ["audit_signing_failed", { httpStatus: 500, reason: "PORTAUTH_AUDIT_SIGNING_FAILED" }],
]);

export function metadataKey(name) {
  if (!Object.hasOwn(metadataKeys, name)) {
    throw new Error(`unknown PortAuth A2A metadata key: ${name}`);
  }
  return metadataKeys[name];
}

export function parseExtensionHeader(value) {
  if (!value) return [];
  return String(value)
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

export function extensionHeaderIncludes(value, uri = EXTENSION_URI) {
  // Exact membership in the parsed header list (the value is split on "," first),
  // not a substring/URL check — extension URIs are matched verbatim per A2A.
  return parseExtensionHeader(value).some((item) => item === uri);
}

export function buildPortAuthMetadata({
  credential,
  vc,
  vcFormat = "tier1-jwt",
  presenterId,
  proofOfPossession,
  idempotencyKey,
  delegationChain,
} = {}) {
  const token = credential || vc;
  if (typeof token !== "string" || token.length === 0) {
    throw new Error("credential or vc must be a non-empty compact JWS string");
  }
  if (!VC_FORMATS.includes(vcFormat)) {
    throw new Error(`vcFormat must be one of ${VC_FORMATS.join(", ")}`);
  }
  if (typeof presenterId !== "string" || presenterId.length === 0) {
    throw new Error("presenterId must be a non-empty string");
  }
  const metadata = {
    [metadataKeys.vc]: token,
    [metadataKeys.vcFormat]: vcFormat,
    [metadataKeys.presenterId]: presenterId,
  };
  if (proofOfPossession !== undefined) metadata[metadataKeys.proofOfPossession] = proofOfPossession;
  if (idempotencyKey !== undefined) metadata[metadataKeys.idempotencyKey] = idempotencyKey;
  if (delegationChain !== undefined) metadata[metadataKeys.delegationChain] = delegationChain;
  return metadata;
}

export function validatePortAuthMetadata(metadata = {}) {
  const errors = [];
  const credential = metadata[metadataKeys.vc];
  const vcFormat = metadata[metadataKeys.vcFormat];
  const presenterId = metadata[metadataKeys.presenterId];
  const delegationChain = metadata[metadataKeys.delegationChain];

  if (typeof credential !== "string" || credential.length === 0) {
    errors.push({ field: metadataKeys.vc, message: "must be a non-empty compact JWS string" });
  }
  if (!VC_FORMATS.includes(vcFormat)) {
    errors.push({ field: metadataKeys.vcFormat, message: `must be one of ${VC_FORMATS.join(", ")}` });
  }
  if (typeof presenterId !== "string" || presenterId.length === 0) {
    errors.push({ field: metadataKeys.presenterId, message: "must be a non-empty presenter identifier" });
  }
  if (delegationChain !== undefined) {
    if (!Array.isArray(delegationChain) || !delegationChain.every((item) => typeof item === "string" && item.length > 0)) {
      errors.push({ field: metadataKeys.delegationChain, message: "must be an array of compact JWS strings" });
    }
  }
  return { ok: errors.length === 0, errors };
}

export function extractPortAuthMetadata(message = {}) {
  const metadata = message.metadata || {};
  const validation = validatePortAuthMetadata(metadata);
  if (!validation.ok) {
    const detail = validation.errors.map((err) => `${err.field}: ${err.message}`).join("; ");
    throw Object.assign(new Error(`invalid PortAuth A2A metadata: ${detail}`), {
      code: "portauth_metadata_invalid",
      validation,
    });
  }
  return {
    credential: metadata[metadataKeys.vc],
    vcFormat: metadata[metadataKeys.vcFormat],
    presenterId: metadata[metadataKeys.presenterId],
    proofOfPossession: metadata[metadataKeys.proofOfPossession],
    idempotencyKey: metadata[metadataKeys.idempotencyKey],
    delegationChain: metadata[metadataKeys.delegationChain] || [],
  };
}

export function validateA2aSendMessageRequest(body = {}) {
  const errors = [];
  const message = body.message;
  if (!message || typeof message !== "object") {
    errors.push({ field: "message", message: "is required" });
    return { ok: false, errors };
  }
  if (typeof message.messageId !== "string" || message.messageId.length === 0) {
    errors.push({ field: "message.messageId", message: "must be a non-empty string" });
  }
  if (message.role !== "ROLE_USER" && message.role !== "ROLE_AGENT") {
    errors.push({ field: "message.role", message: "must be ROLE_USER or ROLE_AGENT" });
  }
  if (!Array.isArray(message.parts) || message.parts.length === 0) {
    errors.push({ field: "message.parts", message: "must contain at least one part" });
  } else {
    message.parts.forEach((part, index) => {
      const members = ["text", "raw", "url", "data"].filter((key) => part?.[key] !== undefined);
      if (members.length !== 1) {
        errors.push({ field: `message.parts[${index}]`, message: "must contain exactly one of text, raw, url, or data" });
      }
    });
  }
  return { ok: errors.length === 0, errors };
}

export function buildA2aSendMessageRequest({
  text,
  data,
  metadata,
  messageId = randomUUID(),
  contextId,
  taskId,
  role = "ROLE_USER",
  extensions = [EXTENSION_URI],
  configuration = { acceptedOutputModes: ["text/plain", "application/json"] },
} = {}) {
  const parts = [];
  if (text !== undefined) parts.push({ text: String(text) });
  if (data !== undefined) parts.push({ data, mediaType: "application/json" });
  if (parts.length === 0) throw new Error("text or data is required to build an A2A message");

  const message = {
    messageId,
    role,
    parts,
    extensions,
    metadata: metadata || {},
  };
  if (contextId) message.contextId = contextId;
  if (taskId) message.taskId = taskId;
  return { message, configuration };
}

export function getPortAuthExtension(agentCard = {}, uri = EXTENSION_URI) {
  return (agentCard.capabilities?.extensions || []).find((extension) => extension.uri === uri) || null;
}

export function selectHttpJsonInterface(agentCard = {}) {
  return (agentCard.supportedInterfaces || []).find((entry) => {
    return String(entry.protocolBinding || "").toUpperCase() === "HTTP+JSON";
  }) || null;
}

export async function fetchAgentCard(agentBaseUrl, { fetchImpl = globalThis.fetch } = {}) {
  const url = new URL("/.well-known/agent-card.json", ensureTrailingSlash(agentBaseUrl));
  const resp = await fetchImpl(url, { headers: { Accept: "application/json" } });
  if (!resp.ok) throw new Error(`Agent Card fetch failed: ${resp.status}`);
  return await resp.json();
}

export async function sendWithVc({
  agentCardUrl,
  receiverUrl,
  agentCard,
  credential,
  vcFormat = "tier1-jwt",
  presenterId,
  text,
  requestContext,
  proofOfPossession,
  idempotencyKey,
  delegationChain,
  authorization,
  headers = {},
  fetchImpl = globalThis.fetch,
} = {}) {
  let card = agentCard;
  if (!card) {
    const base = agentCardUrl || receiverUrl;
    if (!base) throw new Error("agentCard, agentCardUrl, or receiverUrl is required");
    card = await fetchAgentCard(base, { fetchImpl });
  }

  const extension = getPortAuthExtension(card);
  if (!extension) throw new Error(`receiver does not advertise ${EXTENSION_URI}`);

  const endpoint = selectHttpJsonInterface(card)?.url || receiverUrl;
  if (!endpoint) throw new Error("receiver Agent Card does not expose an HTTP+JSON interface");

  const metadata = buildPortAuthMetadata({
    credential,
    vcFormat,
    presenterId,
    proofOfPossession,
    idempotencyKey,
    delegationChain,
  });
  const body = buildA2aSendMessageRequest({ text, data: requestContext, metadata });
  const url = new URL("/message:send", ensureTrailingSlash(endpoint));
  const resp = await fetchImpl(url, {
    method: "POST",
    headers: {
      ...headers,
      Accept: A2A_MEDIA_TYPE,
      "Content-Type": A2A_MEDIA_TYPE,
      "A2A-Version": A2A_VERSION,
      "A2A-Extensions": EXTENSION_URI,
      ...(authorization ? { Authorization: authorization } : {}),
    },
    body: JSON.stringify(body),
  });
  const payload = await readJsonResponse(resp);
  return { ok: resp.ok, status: resp.status, body: payload, agentCard: card };
}

// ---------------------------------------------------------------------------
// Governance-manifest preflight (self-contained; no cross-package import)
//
// A published `portauth-a2a` tarball must run on its own. This function used to
// dynamically import a sibling preflight package that only exists inside the
// monorepo, so once installed from npm `preflight()` threw ERR_MODULE_NOT_FOUND.
// The compatibility rules and manifest-signature verification are inlined below
// so the packed package works by itself.
//
// Signature verification uses Node's built-in WebCrypto (`crypto.subtle`) for
// the standard asymmetric JWS algorithms, keeping the package dependency-free.
// For an algorithm WebCrypto cannot check (e.g. ES256K / secp256k1) it fails
// HARD instead of silently passing -- preflight() must never look like it
// verified a signed manifest when it actually did not.
// ---------------------------------------------------------------------------

const SEMANTIC_PREFIXES = ["core.", "insurance.", "aerospace.", "supply_chain."];

// JWS `alg` -> WebCrypto import + verify parameters. Only algorithms Node's
// WebCrypto verifies natively appear here; anything else is a hard error.
// JWS ECDSA signatures are raw r||s (IEEE P1363), which is exactly the format
// WebCrypto's ECDSA verify expects -- no DER conversion required.
const WEBCRYPTO_JWS_ALGS = new Map([
  ["ES256", { imp: { name: "ECDSA", namedCurve: "P-256" }, ver: { name: "ECDSA", hash: "SHA-256" } }],
  ["ES384", { imp: { name: "ECDSA", namedCurve: "P-384" }, ver: { name: "ECDSA", hash: "SHA-384" } }],
  ["ES512", { imp: { name: "ECDSA", namedCurve: "P-521" }, ver: { name: "ECDSA", hash: "SHA-512" } }],
  ["RS256", { imp: { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, ver: { name: "RSASSA-PKCS1-v1_5" } }],
  ["RS384", { imp: { name: "RSASSA-PKCS1-v1_5", hash: "SHA-384" }, ver: { name: "RSASSA-PKCS1-v1_5" } }],
  ["RS512", { imp: { name: "RSASSA-PKCS1-v1_5", hash: "SHA-512" }, ver: { name: "RSASSA-PKCS1-v1_5" } }],
  ["PS256", { imp: { name: "RSA-PSS", hash: "SHA-256" }, ver: { name: "RSA-PSS", saltLength: 32 } }],
  ["PS384", { imp: { name: "RSA-PSS", hash: "SHA-384" }, ver: { name: "RSA-PSS", saltLength: 48 } }],
  ["PS512", { imp: { name: "RSA-PSS", hash: "SHA-512" }, ver: { name: "RSA-PSS", saltLength: 64 } }],
  ["EdDSA", { imp: { name: "Ed25519" }, ver: { name: "Ed25519" } }],
]);

/**
 * Raised when manifest verification was REQUESTED but cannot be performed at
 * all (no signing key, an algorithm WebCrypto cannot check, or WebCrypto
 * unavailable). It is deliberately a thrown error -- not a soft "incompatible"
 * result -- so a caller that asked for a verified manifest can never mistake an
 * un-performed check for a passing one.
 */
export class ManifestVerificationUnavailableError extends Error {
  constructor(message) {
    super(message);
    this.name = "ManifestVerificationUnavailableError";
  }
}

function b64uToBytes(value) {
  return new Uint8Array(Buffer.from(value, "base64url"));
}

function b64uToText(value) {
  return new TextDecoder("utf-8", { fatal: true }).decode(b64uToBytes(value));
}

function stripProof(manifest = {}) {
  const { proof, ...unsignedManifest } = manifest;
  return unsignedManifest;
}

function canonicalJson(value) {
  if (value === null) return "null";
  if (value === undefined) return undefined;
  if (typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map((item) => canonicalJson(item) ?? "null").join(",")}]`;

  return `{${Object.keys(value)
    .filter((key) => value[key] !== undefined)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`)
    .join(",")}}`;
}

function governanceManifestSigningPayload(manifest) {
  return canonicalJson(stripProof(manifest));
}

async function verifyCompactJwsWithJwks(jws, jwks) {
  const parts = String(jws).split(".");
  if (parts.length !== 3) {
    return { ok: false, error: "manifest proof.jws is not a compact JWS" };
  }
  const [protectedB64, payloadB64, sigB64] = parts;
  let header;
  try {
    header = JSON.parse(Buffer.from(protectedB64, "base64url").toString("utf8"));
  } catch {
    return { ok: false, error: "manifest proof.jws protected header is not valid JSON" };
  }
  if (header.b64 === false) {
    throw new ManifestVerificationUnavailableError(
      "manifest proof.jws uses b64:false, which this verifier does not support",
    );
  }
  const spec = WEBCRYPTO_JWS_ALGS.get(header.alg);
  if (!spec) {
    // Cannot verify this algorithm -> hard error, never a silent pass.
    throw new ManifestVerificationUnavailableError(
      `manifest is signed with '${header.alg || "unknown"}', which this verifier cannot check via WebCrypto`,
    );
  }
  const candidates = (jwks.keys || []).filter((k) => (header.kid && k.kid ? k.kid === header.kid : true));
  if (candidates.length === 0) {
    return { ok: false, error: "no key in the signer JWKS matches the manifest proof header" };
  }
  const data = new TextEncoder().encode(`${protectedB64}.${payloadB64}`);
  const signature = b64uToBytes(sigB64);
  for (const jwk of candidates) {
    try {
      const key = await globalThis.crypto.subtle.importKey("jwk", jwk, spec.imp, false, ["verify"]);
      if (await globalThis.crypto.subtle.verify(spec.ver, key, signature, data)) {
        return { ok: true, alg: header.alg, kid: jwk.kid, payload: b64uToText(payloadB64) };
      }
    } catch {
      // Key didn't import or didn't match this signature; try the next one.
    }
  }
  return { ok: false, error: "manifest signature did not verify against any signer key" };
}

/**
 * Verify a signed governance manifest.
 *
 * Throws `ManifestVerificationUnavailableError` when verification cannot even be
 * attempted (no signingKeyUrl, no WebCrypto, unsupported alg). Returns
 * `{ ok:false, error }` when it WAS attempted and the signature is
 * missing/invalid. Returns `{ ok:true }` only on a real cryptographic pass.
 */
async function verifyGovernanceManifest(manifest, { fetchImpl, signingKeyUrl }) {
  if (!signingKeyUrl) {
    throw new ManifestVerificationUnavailableError(
      "verifyManifest is true but no signingKeyUrl was provided to fetch the manifest signer's JWKS",
    );
  }
  if (!globalThis.crypto?.subtle) {
    throw new ManifestVerificationUnavailableError(
      "WebCrypto (globalThis.crypto.subtle) is unavailable; cannot verify the manifest signature",
    );
  }
  if (!manifest?.proof?.jws) {
    return { ok: false, error: "manifest has no proof.jws to verify" };
  }
  const resp = await fetchImpl(signingKeyUrl, { headers: { Accept: "application/json" } });
  if (!resp.ok) return { ok: false, error: `signer JWKS fetch failed: ${resp.status}` };
  const jwks = await resp.json();
  if (!jwks?.keys?.length) return { ok: false, error: "signer JWKS contains no keys" };
  const verification = await verifyCompactJwsWithJwks(manifest.proof.jws, jwks);
  if (!verification.ok) return verification;

  const expectedPayload = governanceManifestSigningPayload(manifest);
  if (verification.payload !== expectedPayload) {
    return { ok: false, error: "manifest proof payload does not match the fetched manifest" };
  }
  return verification;
}

function decodeCredential(credential) {
  const parts = String(credential).split(".");
  if (parts.length !== 3) throw new Error("credential is not a compact JWS");
  const header = JSON.parse(Buffer.from(parts[0], "base64url").toString("utf8"));
  const payload = JSON.parse(Buffer.from(parts[1], "base64url").toString("utf8"));
  return { header, payload };
}

function detectProfile(header, payload) {
  if (Array.isArray(header.x5c) && header.x5c.length > 0) return "tier2-x509-jwt";
  if (typeof payload.iss === "string" && payload.iss.startsWith("did:")) return "tier3-vc-jose";
  if (payload.vc && typeof payload.vc === "object") return "tier3-vc-jose";
  return "tier1-jwt";
}

function collectConstraintTypes(payload) {
  const constraints = payload.constraints || payload.termsOfUse || [];
  return [...new Set(constraints.map((c) => c.type).filter(Boolean))];
}

function collectVocabularyFields(payload) {
  const constraints = payload.constraints || payload.termsOfUse || [];
  const fields = new Set();
  for (const c of constraints) {
    if (typeof c.field === "string" && SEMANTIC_PREFIXES.some((p) => c.field.startsWith(p))) {
      fields.add(c.field);
    }
  }
  return [...fields];
}

function checkProfile(profile, manifest) {
  const supported = (manifest.credentialProfiles || []).map((p) => p.id);
  if (!supported.includes(profile)) {
    return { rule: "profileMatch", severity: "error", detail: `credential profile ${profile} not in manifest.credentialProfiles` };
  }
  return null;
}

function checkConstraintTypes(types, manifest) {
  const supported = new Set(manifest.constraintTypes || []);
  const missing = types.filter((t) => !supported.has(t));
  if (missing.length > 0) {
    return { rule: "constraintTypes", severity: "error", detail: `unsupported constraint types: ${missing.join(", ")}` };
  }
  return null;
}

function checkVocabulary(fields, manifest) {
  const all = new Set();
  const recognized = manifest.recognizedFields || {};
  for (const key of Object.keys(recognized)) {
    for (const f of recognized[key] || []) all.add(f);
  }
  for (const profile of manifest.mappingProfiles || []) {
    for (const f of Object.keys(profile.fields || {})) all.add(f);
  }
  const missing = fields.filter((f) => !all.has(f));
  if (missing.length > 0) {
    return { rule: "vocabulary", severity: "error", detail: `unrecognized vocabulary fields: ${missing.join(", ")}` };
  }
  return null;
}

function checkTrustAnchors(profile, issuer, manifest) {
  const anchors = manifest.acceptedTrustAnchors || {};
  const tierKey = profile === "tier1-jwt" ? "tier1" : profile === "tier3-vc-jose" ? "tier3" : null;
  if (tierKey) {
    const known = (anchors[tierKey]?.trustedIssuers || []).map((t) => t.issuerId);
    if (known.length > 0 && !known.includes(issuer)) {
      return { rule: "trustAnchors", severity: "warning", detail: `issuer ${issuer} not pre-registered as ${tierKey} trust anchor` };
    }
  }
  return null;
}

function checkRequiredContextFields(required, supplied) {
  const missing = (required || []).filter((f) => !supplied || !(f in supplied));
  if (missing.length > 0) {
    return { rule: "requiredContextFields", severity: "error", detail: `requestContext missing required fields: ${missing.join(", ")}` };
  }
  return null;
}

async function fetchManifest(manifestUrl, { fetchImpl = globalThis.fetch } = {}) {
  const resp = await fetchImpl(manifestUrl, { headers: { Accept: "application/json" } });
  if (!resp.ok) throw new Error(`manifest fetch failed: ${resp.status}`);
  return await resp.json();
}

// The five compatibility rules. Signature verification is handled separately by
// preflight() so that "is this credential compatible" and "is the manifest
// authentic" stay distinguishable in the result.
function runCompatibilityRules({ manifest, credential, requestContext }) {
  const { header, payload } = decodeCredential(credential);
  const profile = detectProfile(header, payload);
  const incompatibilities = [
    checkProfile(profile, manifest),
    checkConstraintTypes(collectConstraintTypes(payload), manifest),
    checkVocabulary(collectVocabularyFields(payload), manifest),
    checkTrustAnchors(profile, payload.iss, manifest),
    checkRequiredContextFields(manifest.requiredContextFields, requestContext),
  ].filter(Boolean);
  const errorCount = incompatibilities.filter((i) => i.severity === "error").length;
  return { compatible: errorCount === 0, incompatibilities, profile };
}

/**
 * Preflight a PortAuth A2A receiver before sending a credential.
 *
 * Fetches the receiver's Agent Card, confirms it advertises the PortAuth
 * extension and a governance manifest, optionally verifies the manifest's
 * signature, then runs the credential past the manifest's compatibility rules.
 *
 * @param {string} agentCardUrl    receiver base URL (or pass options.agentCard)
 * @param {string} vc              the credential (compact JWS) to be sent
 * @param {object} intendedAction  request context, or `{ requestContext }`
 * @param {object} [options]
 * @param {boolean} [options.verifyManifest=true]  when true the manifest MUST be
 *   cryptographically verified; if it cannot be (no signingKeyUrl, unsupported
 *   alg, no WebCrypto) this THROWS rather than returning an unverified pass.
 *   Pass `false` to explicitly run an UNSIGNED, compatibility-only preflight.
 * @param {string} [options.signingKeyUrl]  JWKS URL of the manifest signer.
 * @param {function} [options.fetchImpl=globalThis.fetch]
 * @param {object} [options.agentCard]  pre-fetched Agent Card (skips the fetch).
 * @param {object} [options.manifest]   pre-fetched manifest (skips the fetch).
 * @returns {Promise<object>} `{ compatible, manifestVerified, incompatibilities,
 *   agentCard, extension, manifestUrl }`. `manifestVerified` is true only when
 *   the signature was actually checked and passed.
 * @throws {ManifestVerificationUnavailableError} when `verifyManifest` is true
 *   but verification cannot be performed.
 */
export async function preflight(agentCardUrl, vc, intendedAction = {}, options = {}) {
  const {
    agentCard,
    fetchImpl = globalThis.fetch,
    signingKeyUrl,
    verifyManifest = true,
    manifest: providedManifest,
  } = options;

  const card = agentCard || await fetchAgentCard(agentCardUrl, { fetchImpl });
  const extension = getPortAuthExtension(card);
  if (!extension) {
    return {
      compatible: false,
      manifestVerified: false,
      agentCard: card,
      extension: null,
      incompatibilities: [{ rule: "a2aExtension", severity: "error", detail: `receiver does not advertise ${EXTENSION_URI}` }],
    };
  }
  if (extension.required && (typeof vc !== "string" || vc.length === 0)) {
    return {
      compatible: false,
      manifestVerified: false,
      agentCard: card,
      extension,
      incompatibilities: [{ rule: "credentialRequired", severity: "error", detail: "receiver requires the PortAuth A2A extension but no credential was supplied" }],
    };
  }

  const manifestUrl = extension.params?.governanceManifestUrl;
  if (!manifestUrl && !providedManifest) {
    return {
      compatible: false,
      manifestVerified: false,
      agentCard: card,
      extension,
      incompatibilities: [{ rule: "governanceManifest", severity: "error", detail: "PortAuth Agent Card extension is missing params.governanceManifestUrl" }],
    };
  }

  const manifest = providedManifest || await fetchManifest(manifestUrl, { fetchImpl });

  // Manifest signature. verifyManifest:true is fail-closed: if verification
  // cannot be performed, verifyGovernanceManifest throws and the caller gets a
  // hard error -- never a result that looks verified but isn't.
  let manifestVerified = false;
  if (verifyManifest) {
    const verification = await verifyGovernanceManifest(manifest, { fetchImpl, signingKeyUrl });
    if (!verification.ok) {
      return {
        compatible: false,
        manifestVerified: false,
        agentCard: card,
        extension,
        manifestUrl,
        incompatibilities: [{ rule: "manifestSignature", severity: "error", detail: verification.error }],
      };
    }
    manifestVerified = true;
  }

  const requestContext = intendedAction.requestContext || intendedAction;
  const { compatible, incompatibilities } = runCompatibilityRules({ manifest, credential: vc, requestContext });

  return {
    compatible,
    manifestVerified,
    incompatibilities,
    agentCard: card,
    extension,
    manifestUrl,
  };
}

export function buildGoogleRpcStatus({
  httpStatus = 400,
  reason = "PORTAUTH_INVALID_REQUEST",
  message = "Request rejected",
  engineError,
  auditRecordId,
  metadata = {},
} = {}) {
  const code = grpcCodeByHttpStatus.get(httpStatus) || "UNKNOWN";
  return {
    error: {
      code,
      message,
      details: [
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          reason,
          domain: "aiagent-portable-authorization",
          metadata: {
            ...(engineError ? { engineError } : {}),
            ...(auditRecordId ? { auditRecordId } : {}),
            ...metadata,
          },
        },
      ],
    },
  };
}

export function mapEngineDecisionToA2aError(engineBody = {}, fallbackStatus = 403) {
  const engineError = engineBody.error || "authorization_denied";
  const mapped = engineErrorMap.get(engineError) || {
    httpStatus: fallbackStatus,
    reason: "PORTAUTH_AUTHORIZATION_DENIED",
  };
  return {
    httpStatus: mapped.httpStatus,
    body: buildGoogleRpcStatus({
      httpStatus: mapped.httpStatus,
      reason: mapped.reason,
      message: engineBody.message || `PortAuth denied request: ${engineError}`,
      engineError,
      auditRecordId: engineBody.auditRecordId,
    }),
  };
}

export function buildCompletedTask({
  message,
  auditRecordId,
  decision = "allow",
  text = "PortAuth authorization succeeded.",
  metadata = {},
} = {}) {
  const taskId = message?.taskId || `task-${randomUUID()}`;
  const contextId = message?.contextId || `context-${randomUUID()}`;
  return {
    id: taskId,
    contextId,
    status: {
      state: "TASK_STATE_COMPLETED",
      message: {
        messageId: randomUUID(),
        contextId,
        taskId,
        role: "ROLE_AGENT",
        parts: [{ text }],
        extensions: [EXTENSION_URI],
        metadata: {
          portauthDecision: decision,
          ...(auditRecordId ? { auditRecordId } : {}),
        },
      },
    },
    metadata: {
      portauthDecision: decision,
      ...(auditRecordId ? { auditRecordId } : {}),
      ...metadata,
    },
  };
}

export function buildPortAuthAgentCard({
  name = "PortAuth A2A Reference Receiver",
  description = "A2A receiver that authorizes sensitive requests with PortAuth before task execution.",
  version = "0.1.0",
  url,
  provider = {
    organization: "aiagent-portable-authorization contributors",
    url: "https://github.com/kyndryl-open-source/aiagent-portable-authorization",
  },
  governanceManifestUrl,
  acceptedProfiles = VC_FORMATS,
  acceptedAudiences = [],
  required = true,
  skills,
  securitySchemes,
  securityRequirements,
} = {}) {
  if (!url) throw new Error("Agent Card interface url is required");
  return {
    name,
    description,
    provider,
    version,
    documentationUrl: "https://kyndryl-open-source.github.io/aiagent-portable-authorization/a2a/v1",
    supportedInterfaces: [
      {
        url,
        protocolBinding: "HTTP+JSON",
        protocolVersion: A2A_VERSION,
      },
    ],
    capabilities: {
      streaming: false,
      pushNotifications: false,
      extendedAgentCard: false,
      extensions: [
        {
          uri: EXTENSION_URI,
          description: "PortAuth authorization. Callers attach a signed authorization credential in message.metadata.",
          required,
          params: {
            governanceManifestUrl,
            acceptedProfiles,
            acceptedAudiences,
          },
        },
      ],
    },
    ...(securitySchemes ? { securitySchemes } : {}),
    ...(securityRequirements ? { securityRequirements } : {}),
    defaultInputModes: ["text/plain", "application/json"],
    defaultOutputModes: ["text/plain", "application/json"],
    skills: skills || [
      {
        id: "payments.billPay",
        name: "Authorized bill payment",
        description: "Accepts a bill-payment task only when a PortAuth credential authorizes the requested payment.",
        tags: ["payments", "authorization", "PortAuth"],
        examples: ["Pay my electric bill for 2400 USD."],
        inputModes: ["text/plain", "application/json"],
        outputModes: ["text/plain", "application/json"],
      },
    ],
  };
}

async function readJsonResponse(resp) {
  const text = await resp.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch (_) {
    return { raw: text };
  }
}

function ensureTrailingSlash(value) {
  const text = String(value);
  return text.endsWith("/") ? text : `${text}/`;
}
