/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

import { randomUUID } from "node:crypto";

export const A2A_VERSION = "1.0";
export const A2A_MEDIA_TYPE = "application/a2a+json";
export const EXTENSION_URI = "https://kyndryl-open-source.github.io/aiagent-portable-authorization/a2a/v1";

export const VC_FORMATS = Object.freeze([
  "tier1-jwt",
  "tier2-x509-jwt",
  "tier3-vc-jose",
]);

export const metadataKeys = Object.freeze({
  vc: `${EXTENSION_URI}/vc`,
  vcFormat: `${EXTENSION_URI}/vcFormat`,
  presenterId: `${EXTENSION_URI}/presenterId`,
  proofOfPossession: `${EXTENSION_URI}/proofOfPossession`,
  idempotencyKey: `${EXTENSION_URI}/idempotencyKey`,
  delegationChain: `${EXTENSION_URI}/delegationChain`,
});

const grpcCodeByHttpStatus = new Map([
  [400, "INVALID_ARGUMENT"],
  [401, "UNAUTHENTICATED"],
  [403, "PERMISSION_DENIED"],
  [404, "NOT_FOUND"],
  [409, "ALREADY_EXISTS"],
  [412, "FAILED_PRECONDITION"],
  [422, "INVALID_ARGUMENT"],
  [500, "INTERNAL"],
  [503, "UNAVAILABLE"],
]);

const engineErrorMap = new Map([
  ["authorization_denied", { httpStatus: 403, reason: "PORTAUTH_AUTHORIZATION_DENIED" }],
  ["validation_error", { httpStatus: 400, reason: "PORTAUTH_INVALID_REQUEST" }],
  ["credential_incomplete", { httpStatus: 422, reason: "PORTAUTH_CREDENTIAL_INCOMPLETE" }],
  ["signature_invalid", { httpStatus: 401, reason: "PORTAUTH_SIGNATURE_INVALID" }],
  ["credential_expired", { httpStatus: 401, reason: "PORTAUTH_CREDENTIAL_EXPIRED" }],
  ["issuer_untrusted", { httpStatus: 401, reason: "PORTAUTH_ISSUER_UNTRUSTED" }],
  ["audience_mismatch", { httpStatus: 401, reason: "PORTAUTH_AUDIENCE_MISMATCH" }],
  ["proof_of_possession_failed", { httpStatus: 401, reason: "PORTAUTH_PROOF_OF_POSSESSION_FAILED" }],
  ["subject_binding_mismatch", { httpStatus: 401, reason: "PORTAUTH_SUBJECT_BINDING_MISMATCH" }],
  ["credential_revoked", { httpStatus: 401, reason: "PORTAUTH_CREDENTIAL_REVOKED" }],
  ["tier1_revocation_unavailable", { httpStatus: 503, reason: "PORTAUTH_REVOCATION_UNAVAILABLE" }],
  ["x509_revocation_unavailable", { httpStatus: 503, reason: "PORTAUTH_REVOCATION_UNAVAILABLE" }],
  ["permission_denied", { httpStatus: 403, reason: "PORTAUTH_PERMISSION_DENIED" }],
  ["constraint_failed", { httpStatus: 403, reason: "PORTAUTH_CONSTRAINT_FAILED" }],
  ["context_field_missing", { httpStatus: 400, reason: "PORTAUTH_CONTEXT_FIELD_MISSING" }],
  ["numeric_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_NUMERIC_LIMIT_EXCEEDED" }],
  ["semantic_identifier_unknown", { httpStatus: 403, reason: "PORTAUTH_SEMANTIC_IDENTIFIER_UNKNOWN" }],
  ["temporal_window_violated", { httpStatus: 403, reason: "PORTAUTH_TEMPORAL_WINDOW_VIOLATED" }],
  ["enumerated_list_violated", { httpStatus: 403, reason: "PORTAUTH_ENUMERATED_LIST_VIOLATED" }],
  ["pattern_violated", { httpStatus: 403, reason: "PORTAUTH_PATTERN_VIOLATED" }],
  ["cumulative_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_CUMULATIVE_LIMIT_EXCEEDED" }],
  ["usage_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_USAGE_LIMIT_EXCEEDED" }],
  ["stateful_limit_exceeded", { httpStatus: 403, reason: "PORTAUTH_STATEFUL_LIMIT_EXCEEDED" }],
  ["local_policy_denied", { httpStatus: 403, reason: "PORTAUTH_LOCAL_POLICY_DENIED" }],
  ["delegation_widened", { httpStatus: 403, reason: "PORTAUTH_DELEGATION_WIDENED" }],
  ["delegation_chain_broken", { httpStatus: 401, reason: "PORTAUTH_DELEGATION_CHAIN_BROKEN" }],
  ["delegation_depth_exceeded", { httpStatus: 403, reason: "PORTAUTH_DELEGATION_DEPTH_EXCEEDED" }],
  ["audit_signing_failed", { httpStatus: 500, reason: "PORTAUTH_AUDIT_SIGNING_FAILED" }],
]);

export function metadataKey(name) {
  if (!Object.hasOwn(metadataKeys, name)) {
    throw new Error(`unknown PortAuth A2A metadata key: ${name}`);
  }
  return metadataKeys[name];
}

export function parseExtensionHeader(value) {
  if (!value) return [];
  return String(value)
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

export function extensionHeaderIncludes(value, uri = EXTENSION_URI) {
  // Exact membership in the parsed header list (the value is split on "," first),
  // not a substring/URL check — extension URIs are matched verbatim per A2A.
  return parseExtensionHeader(value).some((item) => item === uri);
}

export function buildPortAuthMetadata({
  credential,
  vc,
  vcFormat = "tier1-jwt",
  presenterId,
  proofOfPossession,
  idempotencyKey,
  delegationChain,
} = {}) {
  const token = credential || vc;
  if (typeof token !== "string" || token.length === 0) {
    throw new Error("credential or vc must be a non-empty compact JWS string");
  }
  if (!VC_FORMATS.includes(vcFormat)) {
    throw new Error(`vcFormat must be one of ${VC_FORMATS.join(", ")}`);
  }
  if (typeof presenterId !== "string" || presenterId.length === 0) {
    throw new Error("presenterId must be a non-empty string");
  }
  const metadata = {
    [metadataKeys.vc]: token,
    [metadataKeys.vcFormat]: vcFormat,
    [metadataKeys.presenterId]: presenterId,
  };
  if (proofOfPossession !== undefined) metadata[metadataKeys.proofOfPossession] = proofOfPossession;
  if (idempotencyKey !== undefined) metadata[metadataKeys.idempotencyKey] = idempotencyKey;
  if (delegationChain !== undefined) metadata[metadataKeys.delegationChain] = delegationChain;
  return metadata;
}

export function validatePortAuthMetadata(metadata = {}) {
  const errors = [];
  const credential = metadata[metadataKeys.vc];
  const vcFormat = metadata[metadataKeys.vcFormat];
  const presenterId = metadata[metadataKeys.presenterId];
  const delegationChain = metadata[metadataKeys.delegationChain];

  if (typeof credential !== "string" || credential.length === 0) {
    errors.push({ field: metadataKeys.vc, message: "must be a non-empty compact JWS string" });
  }
  if (!VC_FORMATS.includes(vcFormat)) {
    errors.push({ field: metadataKeys.vcFormat, message: `must be one of ${VC_FORMATS.join(", ")}` });
  }
  if (typeof presenterId !== "string" || presenterId.length === 0) {
    errors.push({ field: metadataKeys.presenterId, message: "must be a non-empty presenter identifier" });
  }
  if (delegationChain !== undefined) {
    if (!Array.isArray(delegationChain) || !delegationChain.every((item) => typeof item === "string" && item.length > 0)) {
      errors.push({ field: metadataKeys.delegationChain, message: "must be an array of compact JWS strings" });
    }
  }
  return { ok: errors.length === 0, errors };
}

export function extractPortAuthMetadata(message = {}) {
  const metadata = message.metadata || {};
  const validation = validatePortAuthMetadata(metadata);
  if (!validation.ok) {
    const detail = validation.errors.map((err) => `${err.field}: ${err.message}`).join("; ");
    throw Object.assign(new Error(`invalid PortAuth A2A metadata: ${detail}`), {
      code: "portauth_metadata_invalid",
      validation,
    });
  }
  return {
    credential: metadata[metadataKeys.vc],
    vcFormat: metadata[metadataKeys.vcFormat],
    presenterId: metadata[metadataKeys.presenterId],
    proofOfPossession: metadata[metadataKeys.proofOfPossession],
    idempotencyKey: metadata[metadataKeys.idempotencyKey],
    delegationChain: metadata[metadataKeys.delegationChain] || [],
  };
}

export function validateA2aSendMessageRequest(body = {}) {
  const errors = [];
  const message = body.message;
  if (!message || typeof message !== "object") {
    errors.push({ field: "message", message: "is required" });
    return { ok: false, errors };
  }
  if (typeof message.messageId !== "string" || message.messageId.length === 0) {
    errors.push({ field: "message.messageId", message: "must be a non-empty string" });
  }
  if (message.role !== "ROLE_USER" && message.role !== "ROLE_AGENT") {
    errors.push({ field: "message.role", message: "must be ROLE_USER or ROLE_AGENT" });
  }
  if (!Array.isArray(message.parts) || message.parts.length === 0) {
    errors.push({ field: "message.parts", message: "must contain at least one part" });
  } else {
    message.parts.forEach((part, index) => {
      const members = ["text", "raw", "url", "data"].filter((key) => part?.[key] !== undefined);
      if (members.length !== 1) {
        errors.push({ field: `message.parts[${index}]`, message: "must contain exactly one of text, raw, url, or data" });
      }
    });
  }
  return { ok: errors.length === 0, errors };
}

export function buildA2aSendMessageRequest({
  text,
  data,
  metadata,
  messageId = randomUUID(),
  contextId,
  taskId,
  role = "ROLE_USER",
  extensions = [EXTENSION_URI],
  configuration = { acceptedOutputModes: ["text/plain", "application/json"] },
} = {}) {
  const parts = [];
  if (text !== undefined) parts.push({ text: String(text) });
  if (data !== undefined) parts.push({ data, mediaType: "application/json" });
  if (parts.length === 0) throw new Error("text or data is required to build an A2A message");

  const message = {
    messageId,
    role,
    parts,
    extensions,
    metadata: metadata || {},
  };
  if (contextId) message.contextId = contextId;
  if (taskId) message.taskId = taskId;
  return { message, configuration };
}

export function getPortAuthExtension(agentCard = {}, uri = EXTENSION_URI) {
  return (agentCard.capabilities?.extensions || []).find((extension) => extension.uri === uri) || null;
}

export function selectHttpJsonInterface(agentCard = {}) {
  return (agentCard.supportedInterfaces || []).find((entry) => {
    return String(entry.protocolBinding || "").toUpperCase() === "HTTP+JSON";
  }) || null;
}

export async function fetchAgentCard(agentBaseUrl, { fetchImpl = globalThis.fetch } = {}) {
  const url = new URL("/.well-known/agent-card.json", ensureTrailingSlash(agentBaseUrl));
  const resp = await fetchImpl(url, { headers: { Accept: "application/json" } });
  if (!resp.ok) throw new Error(`Agent Card fetch failed: ${resp.status}`);
  return await resp.json();
}

export async function sendWithVc({
  agentCardUrl,
  receiverUrl,
  agentCard,
  credential,
  vcFormat = "tier1-jwt",
  presenterId,
  text,
  requestContext,
  proofOfPossession,
  idempotencyKey,
  delegationChain,
  authorization,
  headers = {},
  fetchImpl = globalThis.fetch,
} = {}) {
  let card = agentCard;
  if (!card) {
    const base = agentCardUrl || receiverUrl;
    if (!base) throw new Error("agentCard, agentCardUrl, or receiverUrl is required");
    card = await fetchAgentCard(base, { fetchImpl });
  }

  const extension = getPortAuthExtension(card);
  if (!extension) throw new Error(`receiver does not advertise ${EXTENSION_URI}`);

  const endpoint = selectHttpJsonInterface(card)?.url || receiverUrl;
  if (!endpoint) throw new Error("receiver Agent Card does not expose an HTTP+JSON interface");

  const metadata = buildPortAuthMetadata({
    credential,
    vcFormat,
    presenterId,
    proofOfPossession,
    idempotencyKey,
    delegationChain,
  });
  const body = buildA2aSendMessageRequest({ text, data: requestContext, metadata });
  const url = new URL("/message:send", ensureTrailingSlash(endpoint));
  const resp = await fetchImpl(url, {
    method: "POST",
    headers: {
      ...headers,
      Accept: A2A_MEDIA_TYPE,
      "Content-Type": A2A_MEDIA_TYPE,
      "A2A-Version": A2A_VERSION,
      "A2A-Extensions": EXTENSION_URI,
      ...(authorization ? { Authorization: authorization } : {}),
    },
    body: JSON.stringify(body),
  });
  const payload = await readJsonResponse(resp);
  return { ok: resp.ok, status: resp.status, body: payload, agentCard: card };
}

export async function preflight(agentCardUrl, vc, intendedAction = {}, options = {}) {
  const {
    agentCard,
    fetchImpl = globalThis.fetch,
    preflightModule,
    signingKeyUrl,
    verifyManifest: shouldVerifyManifest = Boolean(signingKeyUrl),
  } = options;
  const card = agentCard || await fetchAgentCard(agentCardUrl, { fetchImpl });
  const extension = getPortAuthExtension(card);
  if (!extension) {
    return {
      compatible: false,
      agentCard: card,
      extension: null,
      incompatibilities: [
        {
          rule: "a2aExtension",
          severity: "error",
          detail: `receiver does not advertise ${EXTENSION_URI}`,
        },
      ],
    };
  }
  if (extension.required && (typeof vc !== "string" || vc.length === 0)) {
    return {
      compatible: false,
      agentCard: card,
      extension,
      incompatibilities: [
        {
          rule: "credentialRequired",
          severity: "error",
          detail: "receiver requires the PortAuth A2A extension but no credential was supplied",
        },
      ],
    };
  }

  const manifestUrl = extension.params?.governanceManifestUrl;
  if (!manifestUrl) {
    return {
      compatible: false,
      agentCard: card,
      extension,
      incompatibilities: [
        {
          rule: "governanceManifest",
          severity: "error",
          detail: "PortAuth Agent Card extension is missing params.governanceManifestUrl",
        },
      ],
    };
  }

  const module = preflightModule || await import("../../../../sdks/preflight/src/index.js");
  const requestContext = intendedAction.requestContext || intendedAction;
  const result = await module.preflightCheck({
    manifestUrl,
    credential: vc,
    requestContext,
    fetchImpl,
    signingKeyUrl,
    verify: shouldVerifyManifest,
  });
  return {
    ...result,
    agentCard: card,
    extension,
    manifestUrl,
  };
}

export function buildGoogleRpcStatus({
  httpStatus = 400,
  reason = "PORTAUTH_INVALID_REQUEST",
  message = "Request rejected",
  engineError,
  auditRecordId,
  metadata = {},
} = {}) {
  const code = grpcCodeByHttpStatus.get(httpStatus) || "UNKNOWN";
  return {
    error: {
      code,
      message,
      details: [
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          reason,
          domain: "aiagent-portable-authorization",
          metadata: {
            ...(engineError ? { engineError } : {}),
            ...(auditRecordId ? { auditRecordId } : {}),
            ...metadata,
          },
        },
      ],
    },
  };
}

export function mapEngineDecisionToA2aError(engineBody = {}, fallbackStatus = 403) {
  const engineError = engineBody.error || "authorization_denied";
  const mapped = engineErrorMap.get(engineError) || {
    httpStatus: fallbackStatus,
    reason: "PORTAUTH_AUTHORIZATION_DENIED",
  };
  return {
    httpStatus: mapped.httpStatus,
    body: buildGoogleRpcStatus({
      httpStatus: mapped.httpStatus,
      reason: mapped.reason,
      message: engineBody.message || `PortAuth denied request: ${engineError}`,
      engineError,
      auditRecordId: engineBody.auditRecordId,
    }),
  };
}

export function buildCompletedTask({
  message,
  auditRecordId,
  decision = "allow",
  text = "PortAuth authorization succeeded.",
  metadata = {},
} = {}) {
  const taskId = message?.taskId || `task-${randomUUID()}`;
  const contextId = message?.contextId || `context-${randomUUID()}`;
  return {
    id: taskId,
    contextId,
    status: {
      state: "TASK_STATE_COMPLETED",
      message: {
        messageId: randomUUID(),
        contextId,
        taskId,
        role: "ROLE_AGENT",
        parts: [{ text }],
        extensions: [EXTENSION_URI],
        metadata: {
          portauthDecision: decision,
          ...(auditRecordId ? { auditRecordId } : {}),
        },
      },
    },
    metadata: {
      portauthDecision: decision,
      ...(auditRecordId ? { auditRecordId } : {}),
      ...metadata,
    },
  };
}

export function buildPortAuthAgentCard({
  name = "PortAuth A2A Reference Receiver",
  description = "A2A receiver that authorizes sensitive requests with PortAuth before task execution.",
  version = "0.1.0",
  url,
  provider = {
    organization: "aiagent-portable-authorization contributors",
    url: "https://github.com/kyndryl-open-source/aiagent-portable-authorization",
  },
  governanceManifestUrl,
  acceptedProfiles = VC_FORMATS,
  acceptedAudiences = [],
  required = true,
  skills,
} = {}) {
  if (!url) throw new Error("Agent Card interface url is required");
  return {
    name,
    description,
    provider,
    version,
    documentationUrl: "https://kyndryl-open-source.github.io/aiagent-portable-authorization/a2a/v1",
    supportedInterfaces: [
      {
        url,
        protocolBinding: "HTTP+JSON",
        protocolVersion: A2A_VERSION,
      },
    ],
    capabilities: {
      streaming: false,
      pushNotifications: false,
      extendedAgentCard: false,
      extensions: [
        {
          uri: EXTENSION_URI,
          description: "PortAuth authorization. Callers attach a signed authorization credential in message.metadata.",
          required,
          params: {
            governanceManifestUrl,
            acceptedProfiles,
            acceptedAudiences,
          },
        },
      ],
    },
    defaultInputModes: ["text/plain", "application/json"],
    defaultOutputModes: ["text/plain", "application/json"],
    skills: skills || [
      {
        id: "payments.billPay",
        name: "Authorized bill payment",
        description: "Accepts a bill-payment task only when a PortAuth credential authorizes the requested payment.",
        tags: ["payments", "authorization", "PortAuth"],
        examples: ["Pay my electric bill for 2400 USD."],
        inputModes: ["text/plain", "application/json"],
        outputModes: ["text/plain", "application/json"],
      },
    ],
  };
}

async function readJsonResponse(resp) {
  const text = await resp.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch (_) {
    return { raw: text };
  }
}

function ensureTrailingSlash(value) {
  const text = String(value);
  return text.endsWith("/") ? text : `${text}/`;
}
