/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

export const A2A_VERSION: string;
export const A2A_MEDIA_TYPE: string;
export const EXTENSION_URI: string;
export const VC_FORMATS: readonly string[];

export const metadataKeys: Readonly<{
  vc: string;
  vcFormat: string;
  presenterId: string;
  proofOfPossession: string;
  idempotencyKey: string;
  delegationChain: string;
}>;

export type FetchLike = typeof fetch;

export interface PortAuthMetadataInput {
  credential?: string;
  vc?: string;
  vcFormat?: "tier1-jwt" | "tier2-x509-jwt" | "tier3-vc-jose";
  presenterId: string;
  proofOfPossession?: string | { jws: string; [key: string]: unknown };
  idempotencyKey?: string;
  delegationChain?: string[];
}

export interface ExtractedPortAuthMetadata {
  credential: string;
  vcFormat: string;
  presenterId: string;
  proofOfPossession?: string | { jws: string; [key: string]: unknown };
  idempotencyKey?: string;
  delegationChain: string[];
}

export interface A2aMessagePart {
  text?: string;
  data?: unknown;
  raw?: unknown;
  url?: string;
  mediaType?: string;
}

export interface A2aMessage {
  messageId: string;
  role: "ROLE_USER" | "ROLE_AGENT";
  parts: A2aMessagePart[];
  extensions?: string[];
  metadata?: Record<string, unknown>;
  contextId?: string;
  taskId?: string;
}

export interface SendWithVcOptions extends PortAuthMetadataInput {
  agentCardUrl?: string;
  receiverUrl?: string;
  agentCard?: Record<string, unknown>;
  text?: string;
  requestContext?: Record<string, unknown>;
  authorization?: string;
  headers?: Record<string, string>;
  fetchImpl?: FetchLike;
}

export function metadataKey(name: keyof typeof metadataKeys): string;
export function parseExtensionHeader(value?: string): string[];
export function extensionHeaderIncludes(value?: string, uri?: string): boolean;
export function buildPortAuthMetadata(input: PortAuthMetadataInput): Record<string, unknown>;
export function validatePortAuthMetadata(metadata?: Record<string, unknown>): { ok: boolean; errors: Array<{ field: string; message: string }> };
export function extractPortAuthMetadata(message?: { metadata?: Record<string, unknown> }): ExtractedPortAuthMetadata;
export function validateA2aSendMessageRequest(body?: Record<string, unknown>): { ok: boolean; errors: Array<{ field: string; message: string }> };
export function buildA2aSendMessageRequest(input: {
  text?: string;
  data?: unknown;
  metadata?: Record<string, unknown>;
  messageId?: string;
  contextId?: string;
  taskId?: string;
  role?: "ROLE_USER" | "ROLE_AGENT";
  extensions?: string[];
  configuration?: Record<string, unknown>;
}): { message: A2aMessage; configuration: Record<string, unknown> };
export function getPortAuthExtension(agentCard?: Record<string, unknown>, uri?: string): Record<string, unknown> | null;
export function selectHttpJsonInterface(agentCard?: Record<string, unknown>): Record<string, unknown> | null;
export function fetchAgentCard(agentBaseUrl: string, options?: { fetchImpl?: FetchLike }): Promise<Record<string, unknown>>;
export interface PreflightIncompatibility {
  rule: string;
  severity: "error" | "warning";
  detail: string;
}
export interface PreflightOptions {
  /**
   * When true (default) the governance manifest MUST be cryptographically
   * verified; if it cannot be (no signingKeyUrl, unsupported alg, no WebCrypto)
   * preflight throws ManifestVerificationUnavailableError. Pass false to run an
   * explicit UNSIGNED, compatibility-only preflight.
   */
  verifyManifest?: boolean;
  /** JWKS URL of the manifest signer (required when verifyManifest is true). */
  signingKeyUrl?: string;
  fetchImpl?: FetchLike;
  /** Pre-fetched Agent Card (skips the fetch). */
  agentCard?: Record<string, unknown>;
  /** Pre-fetched governance manifest (skips the fetch). */
  manifest?: Record<string, unknown>;
}
export interface PreflightResult {
  compatible: boolean;
  /** True only when the manifest signature was actually checked and passed. */
  manifestVerified: boolean;
  incompatibilities: PreflightIncompatibility[];
  agentCard: Record<string, unknown>;
  extension: Record<string, unknown> | null;
  manifestUrl?: string;
}
/**
 * Thrown when manifest verification is requested but cannot be performed (no
 * signing key, an algorithm WebCrypto cannot check, or WebCrypto unavailable).
 */
export class ManifestVerificationUnavailableError extends Error {}
export function preflight(agentCardUrl: string, vc: string, intendedAction?: Record<string, unknown>, options?: PreflightOptions): Promise<PreflightResult>;
export function sendWithVc(options: SendWithVcOptions): Promise<{ ok: boolean; status: number; body: unknown; agentCard: Record<string, unknown> }>;
export function buildGoogleRpcStatus(input?: Record<string, unknown>): Record<string, unknown>;
export function mapEngineDecisionToA2aError(engineBody?: Record<string, unknown>, fallbackStatus?: number): { httpStatus: number; body: Record<string, unknown> };
export function buildCompletedTask(input?: Record<string, unknown>): Record<string, unknown>;
export function buildPortAuthAgentCard(input: Record<string, unknown>): Record<string, unknown>;
