// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import "dotenv/config";
import express from "express";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import evaluateRouter from "./routes/evaluate.js";
import auditRouter from "./routes/audit.js";
import adminRouter from "./routes/admin.js";
import wellknownRouter from "./routes/wellknown.js";
import { runMigrations } from "./db/pool.js";
import { resignUnsignedAuditRecords } from "./services/auditLogger.js";

const app = express();
app.use(express.json({ limit: "2mb" }));

// ── Health ──────────────────────────────────────────────────────────
app.get("/health", (_req, res) => res.json({ status: "ok", service: "portauth-engine" }));

// ── Routes ──────────────────────────────────────────────────────────
app.use("/evaluate", evaluateRouter);
app.use("/audit", auditRouter);
app.use("/admin", adminRouter);
app.use("/.well-known", wellknownRouter);

// ── Global error handler ────────────────────────────────────────────
app.use((err, _req, res, _next) => {
  console.error("Unhandled error:", err);
  res.status(500).json({ error: "internal_error", message: "Unexpected server error" });
});

const PORT = parseInt(process.env.PORT || "3200", 10);

// Run migrations and then start
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = process.env.MIGRATIONS_DIR || path.resolve(__dirname, "../../portauth-db/migrations");
if (fs.existsSync(migrationsDir)) {
  console.log("Checking for migrations...");
  const files = fs.readdirSync(migrationsDir).sort().map(f => fs.readFileSync(path.join(migrationsDir, f), "utf8"));
  try {
    await runMigrations(files);
    console.log("Migrations applied successfully");
  } catch (err) {
    console.error("Migration failure:", err);
  }
}

try {
  const { resigned } = await resignUnsignedAuditRecords();
  if (resigned > 0) {
    console.log(`Re-signed ${resigned} previously unsigned audit record(s)`);
  }
} catch (err) {
  console.error("Audit re-sign sweep failed:", err);
}

app.listen(PORT, () => console.log(`portauth-engine listening on :${PORT}`));

export default app;
