#!/usr/bin/env node
// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { readFileSync } from "node:fs";
import { preflightCheck } from "./index.js";

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--manifest") args.manifest = argv[++i];
    else if (a === "--credential") args.credential = argv[++i];
    else if (a === "--signing-key-url") args.signingKeyUrl = argv[++i];
    else if (a === "--request-context") args.requestContext = argv[++i];
    else if (a === "--json") args.json = true;
    else if (a === "-h" || a === "--help") args.help = true;
  }
  return args;
}

function usage() {
  console.log(`Usage: portauth-preflight --manifest <url> --credential <path|jwt> [--signing-key-url <url>] [--request-context <json>] [--json]

Exit codes:
  0  compatible
  2  incompatible
  1  operational failure`);
}

async function main() {
  const args = parseArgs(process.argv);
  if (args.help || !args.manifest || !args.credential) {
    usage();
    process.exit(args.help ? 0 : 1);
  }

  let credential = args.credential;
  if (!credential.includes(".") || credential.startsWith("./") || credential.startsWith("/")) {
    try {
      credential = readFileSync(credential, "utf8").trim();
    } catch (err) {
      console.error(`failed to read credential file: ${err.message}`);
      process.exit(1);
    }
  }

  let requestContext;
  if (args.requestContext) {
    try {
      requestContext = JSON.parse(args.requestContext);
    } catch (err) {
      console.error(`invalid --request-context JSON: ${err.message}`);
      process.exit(1);
    }
  }

  try {
    const result = await preflightCheck({
      manifestUrl: args.manifest,
      credential,
      requestContext,
      signingKeyUrl: args.signingKeyUrl,
      verify: Boolean(args.signingKeyUrl),
    });

    if (args.json) {
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log(`compatible: ${result.compatible}`);
      if (!result.compatible) {
        for (const inc of result.incompatibilities) {
          console.log(`  [${inc.severity}] ${inc.rule}: ${inc.detail}`);
        }
      }
    }
    process.exit(result.compatible ? 0 : 2);
  } catch (err) {
    console.error(`operational error: ${err.message}`);
    process.exit(1);
  }
}

main();
