// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import pg from "pg";
const { Pool } = pg;

let pool;

export function getPool() {
  if (!pool) {
    const connectionString = process.env.DATABASE_URL;
    const isLocalConnection = !connectionString || /localhost|127\.0\.0\.1/.test(connectionString);
    const sslEnabled = process.env.DB_SSL === "true" || (!isLocalConnection && process.env.DB_SSL !== "false");
    pool = new Pool({
      ...(connectionString ? { connectionString } : {}),
      ssl: sslEnabled ? { rejectUnauthorized: false } : false
    });
  }
  return pool;
}

export async function runMigrations(sqlFiles) {
  const p = getPool();
  for (const sql of sqlFiles) {
    await p.query(sql);
  }
}

export async function closePool() {
  if (pool) {
    await pool.end();
    pool = null;
  }
}
