#!/usr/bin/env sh
#
# Copyright contributors to the aiagent-portable-authorization project.
# SPDX-License-Identifier: MIT
# This code is generated by AI, edited by humans
#
# Generates a local-only self-signed TLS certificate for the nginx A2A
# reference proxy. Do not use this certificate for production.

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
CERT_FILE="$SCRIPT_DIR/localhost.crt"
KEY_FILE="$SCRIPT_DIR/localhost.key"
CONFIG_FILE="$SCRIPT_DIR/localhost-openssl.cnf"

cat > "$CONFIG_FILE" <<'EOF'
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req

[dn]
CN = localhost

[v3_req]
subjectAltName = @alt_names
basicConstraints = critical, CA:TRUE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
IP.2 = ::1
EOF

openssl req \
  -x509 \
  -newkey rsa:2048 \
  -sha256 \
  -days 30 \
  -nodes \
  -keyout "$KEY_FILE" \
  -out "$CERT_FILE" \
  -config "$CONFIG_FILE"

chmod 600 "$KEY_FILE"
chmod 644 "$CERT_FILE"

echo "Generated:"
echo "  $CERT_FILE"
echo "  $KEY_FILE"
echo
echo "This is a self-signed local development certificate."
echo "Use a CA-signed certificate or managed TLS termination for production."
