#!/usr/bin/env bash
#
# Copyright contributors to the aiagent-portable-authorization project.
# SPDX-License-Identifier: MIT
# This code is generated by AI, edited by humans
#
# End-to-end smoke test for the portable authorization system.
# Requires both portauth-issuer (port 3100) and portauth-engine (port 3200) running,
# plus PostgreSQL with migrations applied.
#
# Usage: ./test/e2e-smoke.sh
#

set -euo pipefail

ISSUER_URL="${ISSUER_URL:-http://localhost:3100}"
ENGINE_URL="${ENGINE_URL:-http://localhost:3200}"
ISSUER_ID_FOR_ENGINE="${ISSUER_ID_FOR_ENGINE:-$ISSUER_URL}"
ISSUER_JWKS_URI="${ISSUER_JWKS_URI:-$ISSUER_ID_FOR_ENGINE/.well-known/jwks.json}"
OPA_URL="${OPA_URL:-http://localhost:8181}"
ISSUER_KEY="${ISSUER_KEY:-dev-issuer-key-change-me}"
ENGINE_KEY="${ENGINE_KEY:-dev-engine-key-change-me}"

pass=0
fail=0

check() {
  local desc="$1" expected="$2" actual="$3"
  if [[ "$actual" == *"$expected"* ]]; then
    echo "  ✓ $desc"
    pass=$((pass + 1))
  else
    echo "  ✗ $desc (expected '$expected', got '$actual')"
    fail=$((fail + 1))
  fi
}

echo "═══ Portable Authorization E2E Smoke Tests ═══"
echo

# ── 1. Health checks ──────────────────────────────────────────────
echo "1. Health checks"
issuer_health=$(curl -sf "$ISSUER_URL/health" || echo '{"status":"down"}')
check "Issuer health" '"status":"ok"' "$issuer_health"

engine_health=$(curl -sf "$ENGINE_URL/health" || echo '{"status":"down"}')
check "Engine health" '"status":"ok"' "$engine_health"
echo

# ── 2. Register trusted issuer ────────────────────────────────────
echo "2. Register trusted issuer"
register_resp=$(curl -sf -X POST "$ENGINE_URL/admin/issuers" \
  -H "Authorization: Bearer $ENGINE_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "issuerId": "'"$ISSUER_ID_FOR_ENGINE"'",
    "trustTier": 1,
    "trustedForPermissions": ["damage_assessment:read", "fraud_detection:read"],
    "label": "Test Issuer",
    "jwksUri": "'"$ISSUER_JWKS_URI"'"
  }' || echo '{"error":"failed"}')
check "Register issuer" '"issuer_id"' "$register_resp"
echo

# ── 3. Issue a credential ────────────────────────────────────────
echo "3. Issue credential (damage assessment agent)"
issue_resp=$(curl -sf -X POST "$ISSUER_URL/credentials/issue" \
  -H "Authorization: Bearer $ISSUER_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "agentId": "agent:damage-assessor-1",
    "permissions": ["damage_assessment:read"],
    "constraints": [
      {"type": "NumericLimitConstraint", "field": "claimAmount", "operator": "lte", "value": 5000, "currency": "USD"},
      {"type": "EnumeratedListConstraint", "field": "claimType", "allowed": ["rear_end", "collision"]},
      {"type": "StringPatternConstraint", "field": "resource", "pattern": "/claims/CLM-2026-", "matchType": "prefix"}
    ]
  }')

CREDENTIAL=$(echo "$issue_resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['credential'])" 2>/dev/null || echo "")
CRED_ID=$(echo "$issue_resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['credentialId'])" 2>/dev/null || echo "")

check "Credential issued" '"format":"jwt"' "$issue_resp"
echo

# ── 4. Happy path — all constraints pass ──────────────────────────
echo "4. Evaluate: happy path (should ALLOW)"
eval_resp=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:damage-assessor-1",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2026-0042",
      "claimAmount": 3500,
      "claimType": "rear_end"
    }
  }')
check "Decision: allow" '"decision":"allow"' "$eval_resp"
echo

# ── 5. Numeric limit violation ────────────────────────────────────
echo "5. Evaluate: claim amount exceeds limit (should DENY)"
eval_deny=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:damage-assessor-1",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2026-0042",
      "claimAmount": 7500,
      "claimType": "rear_end"
    }
  }')
check "Decision: deny (constraint_failed)" '"decision":"deny"' "$eval_deny"
echo

# ── 6. Permission violation ───────────────────────────────────────
echo "6. Evaluate: wrong permission (should DENY)"
eval_perm=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:damage-assessor-1",
    "requestContext": {
      "action": "payment:execute",
      "resource": "/claims/CLM-2026-0042",
      "claimAmount": 3500,
      "claimType": "rear_end"
    }
  }')
check "Decision: deny (permission_denied)" '"permission_denied"' "$eval_perm"
echo

# ── 7. Enumerated list violation ──────────────────────────────────
echo "7. Evaluate: unsupported claim type (should DENY)"
eval_enum=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:damage-assessor-1",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2026-0042",
      "claimAmount": 3500,
      "claimType": "flood"
    }
  }')
check "Decision: deny (wrong claim type)" '"decision":"deny"' "$eval_enum"
echo

# ── 8. String pattern violation ───────────────────────────────────
echo "8. Evaluate: wrong resource prefix (should DENY)"
eval_pattern=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:damage-assessor-1",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2025-0042",
      "claimAmount": 3500,
      "claimType": "rear_end"
    }
  }')
check "Decision: deny (wrong resource)" '"decision":"deny"' "$eval_pattern"
echo

# ── 9. Subject binding mismatch ───────────────────────────────────
echo "9. Evaluate: wrong presenter (should DENY 422)"
eval_binding=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:impersonator",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2026-0042",
      "claimAmount": 3500,
      "claimType": "rear_end"
    }
  }')
check "HTTP 422 (subject binding)" "422" "$eval_binding"
echo

# ── 10. Audit trail ──────────────────────────────────────────────
echo "10. Audit record retrieval"
AUDIT_ID=$(echo "$eval_resp" | python3 -c "import sys,json; print(json.load(sys.stdin).get('auditRecordId',''))" 2>/dev/null || echo "")
if [ -n "$AUDIT_ID" ]; then
  audit_resp=$(curl -sf "$ENGINE_URL/audit/records/$AUDIT_ID")
  check "Audit record found" '"decision":"allow"' "$audit_resp"
else
  echo "  ⚠ Could not extract auditRecordId"
  fail=$((fail + 1))
fi
echo

# ── 11. Revocation ───────────────────────────────────────────────
echo "11. Revoke credential and re-evaluate"
revoke_resp=$(curl -sf -X POST "$ISSUER_URL/credentials/revoke" \
  -H "Authorization: Bearer $ISSUER_KEY" \
  -H "Content-Type: application/json" \
  -d '{"credentialId": "'"$CRED_ID"'", "reason": "test revocation"}')
check "Credential revoked" '"revoked":true' "$revoke_resp"

# Introspection should show active=false
introspect_resp=$(curl -sf -X POST "$ISSUER_URL/credentials/introspect" \
  -H "Content-Type: application/json" \
  -d '{"credentialId": "'"$CRED_ID"'"}')
check "Introspect: not active" '"active":false' "$introspect_resp"

# Engine should now deny the revoked credential via default issuer introspection
# Note: engine returns HTTP 422 for revoked credentials, so -s (not -sf) here.
recheck_revoked=$(curl -s -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$CREDENTIAL"'",
    "presenterId": "agent:damage-assessor-1",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2026-0042",
      "claimAmount": 3500,
      "claimType": "rear_end"
    }
  }')
check "Revoked credential denied on re-evaluation" '"credential_revoked"' "$recheck_revoked"
echo

# ── 12. Local policy ────────────────────────────────────────────
echo "12. Add local policy and test most-restrictive-wins"
# Add a local policy that lowers the claim limit to 4500
local_policy=$(curl -sf -X POST "$ENGINE_URL/admin/local-policy" \
  -H "Authorization: Bearer $ENGINE_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "same-day-lowered-limit",
    "constraints": [{"type": "NumericLimitConstraint", "field": "claimAmount", "operator": "lte", "value": 4500}]
  }')
check "Local policy created" '"name":"same-day-lowered-limit"' "$local_policy"

# Issue a fresh (non-revoked) credential for this test
fresh_resp=$(curl -sf -X POST "$ISSUER_URL/credentials/issue" \
  -H "Authorization: Bearer $ISSUER_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "agentId": "agent:damage-assessor-2",
    "permissions": ["damage_assessment:read"],
    "constraints": [
      {"type": "NumericLimitConstraint", "field": "claimAmount", "operator": "lte", "value": 5000}
    ]
  }')
FRESH_CRED=$(echo "$fresh_resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['credential'])" 2>/dev/null || echo "")

# Request with claimAmount=4800 — credential allows (<=5000) but local policy denies (<=4500)
eval_local=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -d '{
    "credential": "'"$FRESH_CRED"'",
    "presenterId": "agent:damage-assessor-2",
    "requestContext": {
      "action": "damage_assessment:read",
      "resource": "/claims/CLM-2026-0099",
      "claimAmount": 4800
    }
  }')
check "Local policy denied (most-restrictive-wins)" '"local_policy_denied"' "$eval_local"

# Clean up the local policy so it does not leak into subsequent test steps.
LOCAL_POLICY_ID=$(echo "$local_policy" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
if [ -n "$LOCAL_POLICY_ID" ]; then
  curl -sf -X DELETE "$ENGINE_URL/admin/local-policy/$LOCAL_POLICY_ID" \
    -H "Authorization: Bearer $ENGINE_KEY" >/dev/null || true
fi
echo

# ── 13. Stateful usage limit ─────────────────────────────────────
echo "13. Stateful usage limit"
stateful_resp=$(curl -sf -X POST "$ISSUER_URL/credentials/issue" \
  -H "Authorization: Bearer $ISSUER_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "agentId": "agent:fraud-reviewer-1",
    "permissions": ["fraud_detection:read"],
    "constraints": [
      {"id": "single-use-review", "type": "UsageLimitConstraint", "maxUses": 1, "period": "forever", "scope": "credential"}
    ]
  }')
STATEFUL_CRED=$(echo "$stateful_resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['credential'])" 2>/dev/null || echo "")

stateful_allow=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -H "Idempotency-Key: stateful-smoke-1" \
  -d '{
    "credential": "'"$STATEFUL_CRED"'",
    "presenterId": "agent:fraud-reviewer-1",
    "requestContext": {
      "action": "fraud_detection:read",
      "resource": "/claims/CLM-2026-0099"
    }
  }')
check "Stateful first use allowed" '"decision":"allow"' "$stateful_allow"

stateful_deny=$(curl -sf -X POST "$ENGINE_URL/evaluate" \
  -H "Content-Type: application/json" \
  -H "Idempotency-Key: stateful-smoke-2" \
  -d '{
    "credential": "'"$STATEFUL_CRED"'",
    "presenterId": "agent:fraud-reviewer-1",
    "requestContext": {
      "action": "fraud_detection:read",
      "resource": "/claims/CLM-2026-0099"
    }
  }')
check "Stateful second use denied" '"stateful_limit_exceeded"' "$stateful_deny"
echo

# ── 14. Governance manifest ──────────────────────────────────────
echo "14. Governance manifest"
gov_resp=$(curl -sf "$ENGINE_URL/.well-known/agent-governance")
check "Governance manifest served" '"portable-authorization-reference"' "$gov_resp"
echo

# ── 15. OPA advisory compatibility policy ────────────────────────
echo "15. OPA advisory compatibility policy"
if curl -sf "$OPA_URL/health" >/dev/null 2>&1; then
  opa_resp=$(curl -sf -X POST "$OPA_URL/v1/data/portauth/reference/allow" \
    -H "Content-Type: application/json" \
    -d '{"input":{"decision":"allow","verification":{"valid":true},"permissionMatch":{"matched":true}}}')
  check "OPA advisory allow policy" '"result":true' "$opa_resp"
else
  echo "  - OPA not running; advisory policy check skipped"
fi
echo

# ── Summary ──────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════"
echo "Results: $pass passed, $fail failed"
if [[ $fail -gt 0 ]]; then
  exit 1
fi
