// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import {
  verifyAttenuation,
  isRestrictedGlobRefinement,
} from "../src/services/delegationVerifier.js";

describe("restricted_glob attenuation (Plan 5)", () => {
  describe("isRestrictedGlobRefinement", () => {
    it("identical patterns refine each other", () => {
      assert.equal(isRestrictedGlobRefinement("claims/*", "claims/*"), true);
    });

    it("delegate replaces wildcard with literal segment (refines)", () => {
      assert.equal(isRestrictedGlobRefinement("claims/*", "claims/auto"), true);
    });

    it("delegate adds segment under wildcard (refines under prefix model)", () => {
      // claims/* matches single-segment tails only; claims/auto/* matches two
      // segments. So claims/auto/* is NOT a refinement of claims/*.
      assert.equal(isRestrictedGlobRefinement("claims/*", "claims/auto/*"), false);
    });

    it("delegate refines under recursive parent (** absorbs)", () => {
      assert.equal(isRestrictedGlobRefinement("claims/**", "claims/auto/x"), true);
    });

    it("delegate preserves wildcard position", () => {
      assert.equal(isRestrictedGlobRefinement("claims/*/x", "claims/auto/x"), true);
    });

    it("delegate widens by moving wildcard to a different segment", () => {
      assert.equal(isRestrictedGlobRefinement("claims/auto/*", "claims/*/x"), false);
    });

    it("rejects delegate widening from * to **", () => {
      assert.equal(isRestrictedGlobRefinement("claims/*", "claims/**"), false);
    });

    it("delegate adds literal within a wildcard segment (refines)", () => {
      assert.equal(isRestrictedGlobRefinement("claims/*", "claims/auto-2026"), true);
    });

    it("rejects delegate when literal does not match parent literal", () => {
      assert.equal(isRestrictedGlobRefinement("claims/auto/*", "payments/auto/x"), false);
    });

    it("rejects delegate that introduces wildcards parent does not have", () => {
      assert.equal(isRestrictedGlobRefinement("claims/auto", "claims/*"), false);
    });

    it("rejects extra delegate wildcards within a segment", () => {
      assert.equal(isRestrictedGlobRefinement("claims/v*", "claims/v*-*"), false);
    });

    it("delegate narrows intra-segment wildcard", () => {
      assert.equal(isRestrictedGlobRefinement("claims/v*", "claims/v2-final"), true);
    });
  });

  describe("verifyAttenuation StringPatternConstraint", () => {
    it("accepts a sound restricted_glob refinement", () => {
      const parent = {
        permissions: ["claims:read"],
        constraints: [
          { type: "StringPatternConstraint", field: "resource", pattern: "claims/*", matchType: "restricted_glob" },
        ],
      };
      const delegate = {
        permissions: ["claims:read"],
        constraints: [
          { type: "StringPatternConstraint", field: "resource", pattern: "claims/auto", matchType: "restricted_glob" },
        ],
      };
      const result = verifyAttenuation(parent, delegate);
      assert.equal(result.valid, true);
    });

    it("rejects a widening that the old literal-prefix check accepted", () => {
      const parent = {
        permissions: ["claims:read"],
        constraints: [
          { type: "StringPatternConstraint", field: "resource", pattern: "claims/auto/*", matchType: "restricted_glob" },
        ],
      };
      const delegate = {
        permissions: ["claims:read"],
        constraints: [
          // Same literal prefix `claims/auto/`, but actually widens because
          // the wildcard position differs.
          { type: "StringPatternConstraint", field: "resource", pattern: "claims/*/x", matchType: "restricted_glob" },
        ],
      };
      const result = verifyAttenuation(parent, delegate);
      assert.equal(result.valid, false);
    });

    it("rejects ** widening of *", () => {
      const parent = {
        permissions: ["claims:read"],
        constraints: [
          { type: "StringPatternConstraint", field: "resource", pattern: "claims/*", matchType: "restricted_glob" },
        ],
      };
      const delegate = {
        permissions: ["claims:read"],
        constraints: [
          { type: "StringPatternConstraint", field: "resource", pattern: "claims/**", matchType: "restricted_glob" },
        ],
      };
      const result = verifyAttenuation(parent, delegate);
      assert.equal(result.valid, false);
    });
  });
});
