/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import {
  canonicalJson,
  governanceManifestSigningPayload,
  stripProof,
} from "../src/routes/wellknown.js";

describe("governance manifest signing payload", () => {
  it("canonicalizes nested objects independent of key insertion order", () => {
    const left = {
      z: 1,
      a: {
        d: "four",
        b: "two",
        c: ["x", { beta: 2, alpha: 1 }],
      },
    };
    const right = {
      a: {
        c: ["x", { alpha: 1, beta: 2 }],
        b: "two",
        d: "four",
      },
      z: 1,
    };

    assert.equal(canonicalJson(left), canonicalJson(right));
  });

  it("strips proof before computing the signed payload", () => {
    const manifest = {
      version: "0.1.0",
      credentialProfiles: [{ id: "tier1-jwt" }],
      proof: {
        created: "2026-06-28T00:00:00.000Z",
        verificationMethod: "key-1",
        jws: "a.b.c",
      },
    };

    assert.deepEqual(stripProof(manifest), {
      version: "0.1.0",
      credentialProfiles: [{ id: "tier1-jwt" }],
    });
    assert.equal(
      governanceManifestSigningPayload(manifest),
      '{"credentialProfiles":[{"id":"tier1-jwt"}],"version":"0.1.0"}',
    );
  });

  it("does not change when only proof metadata changes", () => {
    const base = {
      version: "0.1.0",
      requiredContextFields: ["action"],
      proof: { created: "one", verificationMethod: "key-1", jws: "a.b.c" },
    };
    const changedProof = {
      ...base,
      proof: { created: "two", verificationMethod: "key-2", jws: "x.y.z" },
    };

    assert.equal(governanceManifestSigningPayload(base), governanceManifestSigningPayload(changedProof));
  });

  it("changes when nested manifest content changes", () => {
    const base = {
      version: "0.1.0",
      credentialProfiles: [{ id: "tier1-jwt" }],
      requiredContextFields: ["action"],
    };
    const nestedTamper = {
      ...base,
      credentialProfiles: [{ id: "tier3-vc-jose" }],
    };
    const arrayTamper = {
      ...base,
      requiredContextFields: ["action", "resource"],
    };

    assert.notEqual(governanceManifestSigningPayload(base), governanceManifestSigningPayload(nestedTamper));
    assert.notEqual(governanceManifestSigningPayload(base), governanceManifestSigningPayload(arrayTamper));
  });
});
