// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import {
  loadTrustedIssuerSummary,
  loadMappingProfileSummary,
  currentGovernanceRevision,
  bumpGovernanceRevision,
} from "../src/services/governanceState.js";

describe("Plan 3: governance state derivation", () => {
  it("falls back to empty per-tier issuer groups when DB is unavailable", async () => {
    const byTier = await loadTrustedIssuerSummary();
    assert.deepEqual(Object.keys(byTier).sort(), ["1", "2", "3"]);
    for (const tier of [1, 2, 3]) {
      assert.ok(Array.isArray(byTier[tier]));
    }
  });

  it("returns empty mapping profile list when DB is unavailable", async () => {
    const profiles = await loadMappingProfileSummary();
    assert.ok(Array.isArray(profiles));
  });

  it("bumpGovernanceRevision increments the counter", () => {
    const before = currentGovernanceRevision();
    bumpGovernanceRevision();
    assert.equal(currentGovernanceRevision(), before + 1);
    bumpGovernanceRevision();
    assert.equal(currentGovernanceRevision(), before + 2);
  });
});
