// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { describe, it, beforeEach } from "node:test";
import assert from "node:assert/strict";

import { enrichRequestContext } from "../src/services/contextEnricher.js";
import { clearMappingCache, resolveSemanticField } from "../src/services/semanticResolver.js";

describe("Plan 4: MVV coverage", () => {
  beforeEach(() => clearMappingCache());

  describe("enrichRequestContext", () => {
    it("populates __credential namespace from payload", () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "claims:read", resource: "/x" },
        payload: {
          issuerId: "did:web:issuer.example",
          agentId: "did:web:agent.example",
          audience: "did:web:engine.example",
          issuedAt: "2026-01-01T00:00:00Z",
          expiresAt: "2026-12-31T23:59:59Z",
          delegatedFrom: { agentId: "did:web:parent.example" },
          credentialId: "urn:vc:1",
          trustTier: 2,
        },
        presenterId: "did:web:presenter.example",
        req: { headers: {} },
      });

      assert.equal(enriched.__credential.issuerId, "did:web:issuer.example");
      assert.equal(enriched.__credential.subjectId, "did:web:agent.example");
      assert.equal(enriched.__credential.presenterId, "did:web:presenter.example");
      assert.equal(enriched.__credential.audience, "did:web:engine.example");
      assert.equal(enriched.__credential.validFrom, "2026-01-01T00:00:00Z");
      assert.equal(enriched.__credential.validUntil, "2026-12-31T23:59:59Z");
      assert.equal(enriched.__credential.delegatorId, "did:web:parent.example");
      assert.equal(enriched.__credential.permission, "claims:read");
    });

    it("uses provided requestId from headers", () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: {},
        presenterId: "p",
        req: { headers: { "x-request-id": "req-abc" } },
      });
      assert.equal(enriched.__request.requestId, "req-abc");
    });

    it("generates a uuid when no requestId is provided", () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: {},
        presenterId: "p",
        req: { headers: {} },
      });
      assert.match(
        enriched.__request.requestId,
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
      );
    });

    it("extracts the first ip from x-forwarded-for", () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: {},
        presenterId: "p",
        req: { headers: { "x-forwarded-for": "203.0.113.7, 198.51.100.4" } },
      });
      assert.equal(enriched.__request.ipAddress, "203.0.113.7");
    });

    it("prefers caller-supplied requestContext fields", () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x", requestId: "caller-id", ipAddress: "10.0.0.1" },
        payload: {},
        presenterId: "p",
        req: { headers: { "x-request-id": "header-id" } },
      });
      assert.equal(enriched.__request.requestId, "caller-id");
      assert.equal(enriched.__request.ipAddress, "10.0.0.1");
    });
  });

  describe("resolveSemanticField with MVV identifiers", () => {
    it("resolves core.issuer_id from enriched context", async () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: { issuerId: "did:web:issuer" },
        presenterId: "p",
        req: { headers: {} },
      });
      const result = await resolveSemanticField("core.issuer_id", enriched);
      assert.equal(result.resolved, true);
      assert.equal(result.value, "did:web:issuer");
    });

    it("resolves core.audience_id from enriched context", async () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: { audience: "did:web:engine" },
        presenterId: "p",
        req: { headers: {} },
      });
      const result = await resolveSemanticField("core.audience_id", enriched);
      assert.equal(result.resolved, true);
      assert.equal(result.value, "did:web:engine");
    });

    it("resolves core.delegator_id when delegatedFrom is present", async () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: { delegatedFrom: { agentId: "did:web:parent" } },
        presenterId: "p",
        req: { headers: {} },
      });
      const result = await resolveSemanticField("core.delegator_id", enriched);
      assert.equal(result.resolved, true);
      assert.equal(result.value, "did:web:parent");
    });

    it("resolves core.workflow_role from request context", async () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x", workflowRole: "approver" },
        payload: {},
        presenterId: "p",
        req: { headers: {} },
      });
      const result = await resolveSemanticField("core.workflow_role", enriched);
      assert.equal(result.resolved, true);
      assert.equal(result.value, "approver");
    });

    it("resolves core.request_id from generated uuid", async () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: {},
        presenterId: "p",
        req: { headers: {} },
      });
      const result = await resolveSemanticField("core.request_id", enriched);
      assert.equal(result.resolved, true);
      assert.match(result.value, /^[0-9a-f]{8}-/);
    });

    it("fails closed when core.delegator_id is requested but no delegation exists", async () => {
      const enriched = enrichRequestContext({
        requestContext: { action: "x", resource: "/x" },
        payload: { issuerId: "did:web:issuer" },
        presenterId: "p",
        req: { headers: {} },
      });
      const result = await resolveSemanticField("core.delegator_id", enriched);
      // delegator path resolves to null which the resolver treats as a present value
      // but a type-checked StringPatternConstraint would catch it. Here we assert
      // the resolver itself does not crash and returns null.
      assert.equal(result.resolved, false);
      assert.equal(result.errorCode, "semantic_type_mismatch");
    });
  });
});
