// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";

import {
  resolveRevocationConfig,
  checkTier1Revocation,
} from "../src/services/revocationClient.js";

describe("Plan 1: revocation client", () => {
  const ENV_KEYS = [
    "PORTAUTH_TIER1_REVOCATION_TIMEOUT_MS",
    "PORTAUTH_TIER1_REVOCATION_RETRIES",
    "PORTAUTH_TIER1_REVOCATION_FAILURE_MODE",
  ];
  let originalEnv = {};

  beforeEach(() => {
    originalEnv = {};
    for (const k of ENV_KEYS) {
      originalEnv[k] = process.env[k];
      delete process.env[k];
    }
  });

  afterEach(() => {
    for (const k of ENV_KEYS) {
      if (originalEnv[k] === undefined) delete process.env[k];
      else process.env[k] = originalEnv[k];
    }
  });

  describe("resolveRevocationConfig", () => {
    it("returns defaults when nothing is set", () => {
      const cfg = resolveRevocationConfig();
      assert.equal(cfg.timeoutMs, 20);
      assert.equal(cfg.retries, 0);
      assert.equal(cfg.failureMode, "open");
    });

    it("reads env-var overrides", () => {
      process.env.PORTAUTH_TIER1_REVOCATION_TIMEOUT_MS = "150";
      process.env.PORTAUTH_TIER1_REVOCATION_RETRIES = "2";
      process.env.PORTAUTH_TIER1_REVOCATION_FAILURE_MODE = "closed";
      const cfg = resolveRevocationConfig();
      assert.equal(cfg.timeoutMs, 150);
      assert.equal(cfg.retries, 2);
      assert.equal(cfg.failureMode, "closed");
    });

    it("issuer overrides beat env vars", () => {
      process.env.PORTAUTH_TIER1_REVOCATION_TIMEOUT_MS = "150";
      const cfg = resolveRevocationConfig({
        issuerOverrides: { revocation_timeout_ms: 50, revocation_failure_mode: "closed" },
      });
      assert.equal(cfg.timeoutMs, 50);
      assert.equal(cfg.failureMode, "closed");
    });

    it("caller options beat issuer overrides", () => {
      const cfg = resolveRevocationConfig({
        issuerOverrides: { revocation_timeout_ms: 50 },
        callerOptions: { revocationTimeoutMs: 5 },
      });
      assert.equal(cfg.timeoutMs, 5);
    });
  });

  describe("checkTier1Revocation", () => {
    function fakeFetch(handler) {
      let calls = 0;
      const fn = async (url, init) => {
        calls += 1;
        return handler(url, init, calls);
      };
      fn.calls = () => calls;
      return fn;
    }

    it("returns skipped when no introspection url", async () => {
      const r = await checkTier1Revocation({
        introspectionUrl: null,
        credentialId: "x",
        config: { timeoutMs: 20, retries: 0, failureMode: "open" },
      });
      assert.equal(r.outcome, "skipped");
    });

    it("returns revoked when response indicates revoked", async () => {
      const fetchImpl = fakeFetch(async () => ({
        ok: true,
        json: async () => ({ active: false }),
      }));
      const r = await checkTier1Revocation({
        introspectionUrl: "https://issuer/introspect",
        credentialId: "x",
        config: { timeoutMs: 20, retries: 0, failureMode: "open" },
        fetchImpl,
      });
      assert.equal(r.outcome, "revoked");
    });

    it("returns active when response indicates active", async () => {
      const fetchImpl = fakeFetch(async () => ({
        ok: true,
        json: async () => ({ active: true }),
      }));
      const r = await checkTier1Revocation({
        introspectionUrl: "https://issuer/introspect",
        credentialId: "x",
        config: { timeoutMs: 20, retries: 0, failureMode: "open" },
        fetchImpl,
      });
      assert.equal(r.outcome, "active");
    });

    it("retries on failure and surfaces unavailable when all attempts fail", async () => {
      const fetchImpl = fakeFetch(async () => {
        throw new Error("network down");
      });
      const r = await checkTier1Revocation({
        introspectionUrl: "https://issuer/introspect",
        credentialId: "x",
        config: { timeoutMs: 20, retries: 2, failureMode: "closed" },
        fetchImpl,
      });
      assert.equal(r.outcome, "unavailable");
      assert.equal(fetchImpl.calls(), 3);
    });

    it("succeeds after a transient failure", async () => {
      const fetchImpl = fakeFetch(async (_url, _init, calls) => {
        if (calls === 1) throw new Error("transient");
        return { ok: true, json: async () => ({ active: true }) };
      });
      const r = await checkTier1Revocation({
        introspectionUrl: "https://issuer/introspect",
        credentialId: "x",
        config: { timeoutMs: 20, retries: 2, failureMode: "open" },
        fetchImpl,
      });
      assert.equal(r.outcome, "active");
      assert.equal(fetchImpl.calls(), 2);
    });

    it("treats non-OK HTTP as unavailable", async () => {
      const fetchImpl = fakeFetch(async () => ({ ok: false, status: 503 }));
      const r = await checkTier1Revocation({
        introspectionUrl: "https://issuer/introspect",
        credentialId: "x",
        config: { timeoutMs: 20, retries: 0, failureMode: "closed" },
        fetchImpl,
      });
      assert.equal(r.outcome, "unavailable");
    });
  });
});
