// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  evaluateStatefulConstraints,
  MemoryStatefulStore,
} from "../src/services/statefulAuthorizer.js";

const payload = {
  credentialId: "credential:stateful-test",
  agentId: "agent:stateful",
  issuerId: "https://issuer.example.test",
};

describe("Stateful authorization profiles", () => {
  it("tracks cumulative limits transactionally in the injected store", async () => {
    const store = new MemoryStatefulStore();
    const constraints = [
      {
        id: "daily-claim-total",
        type: "CumulativeLimitConstraint",
        field: "claimAmount",
        maxAmount: 5000,
        period: "day",
        scope: "credential",
      },
    ];

    const first = await evaluateStatefulConstraints(
      constraints,
      { action: "damage_assessment:read", resource: "/claims/1", claimAmount: 3000 },
      payload,
      { store, now: new Date("2026-06-05T12:00:00Z") }
    );
    assert.equal(first.pass, true);

    const second = await evaluateStatefulConstraints(
      constraints,
      { action: "damage_assessment:read", resource: "/claims/2", claimAmount: 2500 },
      payload,
      { store, now: new Date("2026-06-05T13:00:00Z") }
    );
    assert.equal(second.pass, false);
    assert.equal(second.error, "stateful_limit_exceeded");
  });

  it("does not increment twice for the same idempotency key", async () => {
    const store = new MemoryStatefulStore();
    const constraints = [
      {
        id: "two-uses",
        type: "UsageLimitConstraint",
        maxUses: 1,
        period: "forever",
        scope: "credential",
      },
    ];
    const context = { action: "claim.settle", resource: "/claims/1" };

    const first = await evaluateStatefulConstraints(constraints, context, payload, {
      store,
      idempotencyKey: "request-1",
      now: new Date("2026-06-05T12:00:00Z"),
    });
    assert.equal(first.pass, true);

    const replay = await evaluateStatefulConstraints(constraints, context, payload, {
      store,
      idempotencyKey: "request-1",
      now: new Date("2026-06-05T12:00:01Z"),
    });
    assert.equal(replay.pass, true);
    assert.equal(replay.results[0].detail.includes("Idempotent replay"), true);

    const nextRequest = await evaluateStatefulConstraints(constraints, context, payload, {
      store,
      idempotencyKey: "request-2",
      now: new Date("2026-06-05T12:00:02Z"),
    });
    assert.equal(nextRequest.pass, false);
    assert.equal(nextRequest.error, "stateful_limit_exceeded");
  });
});
