// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import { validateRoleCoverage, combineSubDecisions } from "../src/services/workflowEvaluator.js";

describe("Plan 7: workflow evaluator", () => {
  describe("validateRoleCoverage", () => {
    const policy = {
      required_roles: [
        { role: "adjuster", permission: "claims:read" },
        { role: "fraud", permission: "fraud:approve" },
      ],
    };

    it("accepts the exact set of required roles", () => {
      const r = validateRoleCoverage(policy, ["adjuster", "fraud"]);
      assert.equal(r.ok, true);
    });

    it("rejects when a required role is missing", () => {
      const r = validateRoleCoverage(policy, ["adjuster"]);
      assert.equal(r.ok, false);
      assert.equal(r.errorCode, "workflow_role_mismatch");
    });

    it("rejects when an extra role is presented", () => {
      const r = validateRoleCoverage(policy, ["adjuster", "fraud", "auditor"]);
      assert.equal(r.ok, false);
      assert.equal(r.errorCode, "workflow_role_mismatch");
    });
  });

  describe("combineSubDecisions", () => {
    it("requireAll denies when one is deny", () => {
      const r = combineSubDecisions(
        { combinator: "requireAll" },
        [{ decision: "allow" }, { decision: "deny" }],
      );
      assert.equal(r.decision, "deny");
    });

    it("requireAll allows when all are allow", () => {
      const r = combineSubDecisions(
        { combinator: "requireAll" },
        [{ decision: "allow" }, { decision: "allow" }],
      );
      assert.equal(r.decision, "allow");
    });

    it("requireAny allows when one is allow", () => {
      const r = combineSubDecisions(
        { combinator: "requireAny" },
        [{ decision: "deny" }, { decision: "allow" }],
      );
      assert.equal(r.decision, "allow");
    });

    it("requireAny denies when all are deny", () => {
      const r = combineSubDecisions(
        { combinator: "requireAny" },
        [{ decision: "deny" }, { decision: "deny" }],
      );
      assert.equal(r.decision, "deny");
    });

    it("threshold requires N allows", () => {
      const r1 = combineSubDecisions(
        { combinator: "threshold", threshold_n: 2 },
        [{ decision: "allow" }, { decision: "allow" }, { decision: "deny" }],
      );
      assert.equal(r1.decision, "allow");

      const r2 = combineSubDecisions(
        { combinator: "threshold", threshold_n: 3 },
        [{ decision: "allow" }, { decision: "allow" }, { decision: "deny" }],
      );
      assert.equal(r2.decision, "deny");
    });

    it("unknown combinator denies", () => {
      const r = combineSubDecisions(
        { combinator: "weighted" },
        [{ decision: "allow" }],
      );
      assert.equal(r.decision, "deny");
    });
  });
});
