/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

import { randomUUID } from "node:crypto";

import {
  A2A_MEDIA_TYPE,
  EXTENSION_URI,
  VC_FORMATS,
  buildCompletedTask,
  buildGoogleRpcStatus,
  extensionHeaderIncludes,
  extractPortAuthMetadata,
  mapEngineDecisionToA2aError,
  validateA2aSendMessageRequest,
} from "portauth-a2a";

import { runTaskStoreMigrations, TASK_STORE_MIGRATIONS } from "./migrations.js";
import { createOtelObserver } from "./otel.js";

export { runTaskStoreMigrations, TASK_STORE_MIGRATIONS, createOtelObserver };

export function createPostgresTaskStoreSchemaSql({ tableName = "portauth_a2a_tasks" } = {}) {
  const table = quoteIdentifier(tableName);
  return `
CREATE TABLE IF NOT EXISTS ${table} (
  id TEXT PRIMARY KEY,
  task_id TEXT,
  idempotency_key TEXT NOT NULL UNIQUE,
  lifecycle_state TEXT NOT NULL,
  task JSONB,
  response JSONB,
  request_context JSONB,
  presenter_id TEXT,
  vc_format TEXT,
  audit_record_id TEXT,
  error_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE ${table}
  ADD COLUMN IF NOT EXISTS task_id TEXT;
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${tableName}_audit_record_id_idx`)}
  ON ${table} (audit_record_id);
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${tableName}_task_id_idx`)}
  ON ${table} (task_id);
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${tableName}_updated_at_idx`)}
  ON ${table} (updated_at DESC);
`.trim();
}

// Bring the schema up to date. Backed by the versioned migrator
// (`runTaskStoreMigrations`): idempotent, records applied versions, and applies
// only pending migrations. Retained as the convenience entry point.
export async function ensurePostgresTaskStoreSchema(queryable, options = {}) {
  return runTaskStoreMigrations(queryable, options);
}

export function createPostgresTaskStore({ queryable, tableName = "portauth_a2a_tasks" } = {}) {
  assertQueryable(queryable);
  const table = quoteIdentifier(tableName);

  return {
    async createPending(record) {
      const existing = await selectExistingRecord(queryable, table, record);
      if (existing) return { created: false, record: existing };

      try {
        const inserted = await queryable.query(
          `INSERT INTO ${table} (
             id, task_id, idempotency_key, lifecycle_state, task, response,
             request_context, presenter_id, vc_format, audit_record_id, error_reason
           ) VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, $7::jsonb, $8, $9, $10, $11)
           RETURNING *`,
          [
            record.id,
            record.taskId || null,
            record.idempotencyKey,
            record.lifecycleState,
            jsonParam(record.task),
            jsonParam(record.response),
            jsonParam(record.requestContext),
            record.presenterId || null,
            record.vcFormat || null,
            record.auditRecordId || null,
            record.errorReason || null,
          ],
        );
        return { created: true, record: rowToTaskRecord(inserted.rows[0]) };
      } catch (err) {
        if (err.code !== "23505") throw err;
        const raced = await selectExistingRecord(queryable, table, record);
        if (raced) return { created: false, record: raced };
        throw err;
      }
    },
    async update(id, patch = {}) {
      // Single atomic statement: build the SET clause from the patch and let the
      // database apply it in one round-trip. This avoids a read-then-write
      // (SELECT then UPDATE) race where two concurrent updates to the same record
      // could clobber each other. id/idempotencyKey/createdAt are immutable and
      // never written. Only fields present in the patch are touched.
      const values = [id];
      const sets = [];
      const assign = (column, value, cast = "") => {
        values.push(value);
        sets.push(`${column} = $${values.length}${cast}`);
      };
      const patchColumns = [
        ["lifecycle_state", "lifecycleState"],
        ["task", "task", "::jsonb", true],
        ["response", "response", "::jsonb", true],
        ["request_context", "requestContext", "::jsonb", true],
        ["task_id", "taskId"],
        ["presenter_id", "presenterId"],
        ["vc_format", "vcFormat"],
        ["audit_record_id", "auditRecordId"],
        ["error_reason", "errorReason"],
      ];
      for (const [column, key, cast = "", isJson = false] of patchColumns) {
        if (!(key in patch)) continue;
        assign(column, isJson ? jsonParam(patch[key]) : (patch[key] ?? null), cast);
      }
      sets.push("updated_at = now()");

      const updated = await queryable.query(
        `UPDATE ${table} SET ${sets.join(", ")} WHERE id = $1 RETURNING *`,
        values,
      );
      if (!updated.rows[0]) throw new Error(`task record not found: ${id}`);
      return rowToTaskRecord(updated.rows[0]);
    },
    async get(id) {
      const result = await queryable.query(`SELECT * FROM ${table} WHERE id = $1`, [id]);
      return result.rows[0] ? rowToTaskRecord(result.rows[0]) : null;
    },
    async getByIdempotencyKey(idempotencyKey) {
      const result = await queryable.query(`SELECT * FROM ${table} WHERE idempotency_key = $1`, [idempotencyKey]);
      return result.rows[0] ? rowToTaskRecord(result.rows[0]) : null;
    },
    async getByTaskId(taskId) {
      const result = await queryable.query(`SELECT * FROM ${table} WHERE task_id = $1 ORDER BY updated_at DESC LIMIT 1`, [taskId]);
      return result.rows[0] ? rowToTaskRecord(result.rows[0]) : null;
    },
    async list({ limit = 100 } = {}) {
      const boundedLimit = Math.max(1, Math.min(Number(limit) || 100, 1000));
      const result = await queryable.query(`SELECT * FROM ${table} ORDER BY updated_at DESC LIMIT $1`, [boundedLimit]);
      return result.rows.map(rowToTaskRecord);
    },
    async clear() {
      await queryable.query(`DELETE FROM ${table}`);
    },
  };
}

export function createMemoryTaskStore() {
  const recordsById = new Map();
  const idsByIdempotencyKey = new Map();
  return {
    async createPending(record) {
      const existing = findExistingMemoryRecord(recordsById, idsByIdempotencyKey, record);
      if (existing) return { created: false, record: existing };
      const now = new Date().toISOString();
      const persisted = {
        ...record,
        createdAt: record.createdAt || now,
        updatedAt: record.updatedAt || now,
      };
      recordsById.set(persisted.id, persisted);
      idsByIdempotencyKey.set(persisted.idempotencyKey, persisted.id);
      return { created: true, record: persisted };
    },
    async update(id, patch = {}) {
      const existing = recordsById.get(id);
      if (!existing) throw new Error(`task record not found: ${id}`);
      const updated = stripUndefined({
        ...existing,
        ...patch,
        id: existing.id,
        idempotencyKey: existing.idempotencyKey,
        createdAt: existing.createdAt,
        updatedAt: patch.updatedAt || new Date().toISOString(),
      });
      recordsById.set(id, updated);
      idsByIdempotencyKey.set(updated.idempotencyKey, id);
      return updated;
    },
    async get(id) {
      return recordsById.get(id) || null;
    },
    async getByIdempotencyKey(idempotencyKey) {
      const id = idsByIdempotencyKey.get(idempotencyKey);
      return id ? recordsById.get(id) || null : null;
    },
    async getByTaskId(taskId) {
      return [...recordsById.values()]
        .filter((record) => record.taskId === taskId)
        .sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)))[0] || null;
    },
    async list({ limit = 100 } = {}) {
      const boundedLimit = Math.max(1, Math.min(Number(limit) || 100, 1000));
      return [...recordsById.values()]
        .sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)))
        .slice(0, boundedLimit);
    },
    async clear() {
      recordsById.clear();
      idsByIdempotencyKey.clear();
    },
  };
}

export function isStuckPendingTaskRecord(record, {
  olderThanMs = 15 * 60 * 1000,
  now = Date.now(),
} = {}) {
  if (record?.lifecycleState !== "pending") return false;
  const updatedAt = Date.parse(record.updatedAt || record.createdAt || "");
  if (!Number.isFinite(updatedAt)) return false;
  return Number(now) - updatedAt >= Number(olderThanMs);
}

export function buildStuckPendingFailurePatch(record, {
  message = "Pending PortAuth A2A task requires reconciliation before retry.",
  errorReason = "stuck_pending_reconciliation_required",
} = {}) {
  return {
    lifecycleState: "failed",
    errorReason,
    response: {
      status: 503,
      headers: { "Content-Type": A2A_MEDIA_TYPE },
      body: buildGoogleRpcStatus({
        httpStatus: 503,
        reason: "PORTAUTH_TASK_RECONCILIATION_REQUIRED",
        message,
        auditRecordId: record?.auditRecordId,
        metadata: {
          taskRecordId: record?.id,
          idempotencyKey: record?.idempotencyKey,
        },
      }),
    },
  };
}

export async function reconcilePendingTaskRecords({
  taskStore,
  olderThanMs = 15 * 60 * 1000,
  limit = 1000,
  now = Date.now(),
  resolveRecord,
} = {}) {
  if (!taskStore || typeof taskStore.list !== "function" || typeof taskStore.update !== "function") {
    throw new Error("taskStore with async list() and update() is required");
  }
  if (typeof resolveRecord !== "function") {
    throw new Error("resolveRecord(record) is required");
  }
  const records = await taskStore.list({ limit });
  const stuckRecords = records.filter((record) => isStuckPendingTaskRecord(record, { olderThanMs, now }));
  const resolved = [];
  const skipped = [];
  const failed = [];

  for (const record of stuckRecords) {
    try {
      const patch = await resolveRecord(record);
      if (!patch) {
        skipped.push(record);
        continue;
      }
      resolved.push(await taskStore.update(record.id, patch));
    } catch (err) {
      failed.push({ record, error: err.message });
    }
  }

  return {
    inspected: records.length,
    stuck: stuckRecords.length,
    resolved,
    skipped,
    failed,
  };
}

export function defaultRequestContextMapper({ message }) {
  const data = firstDataPart(message) || {};
  return {
    ...data,
    requestId: message.taskId || message.messageId,
  };
}

export function firstDataPart(message = {}) {
  return (message.parts || []).find((part) => part && typeof part === "object" && part.data !== undefined)?.data || null;
}

export function createPortAuthReceiver({
  engineUrl,
  required = true,
  acceptedProfiles = VC_FORMATS,
  mapRequestContext = defaultRequestContextMapper,
  requireProofOfPossession = false,
  taskStore = createMemoryTaskStore(),
  engineAuthToken = null,
  onEvent = null,
  fetchImpl = globalThis.fetch,
  logger = console,
} = {}) {
  if (!engineUrl) throw new Error("engineUrl is required");

  async function handleSendMessage({ headers = {}, body } = {}) {
    const startedAt = Date.now();
    const requestId = getHeader(headers, "x-request-id") || randomUUID();
    const emit = (event) => emitEvent(onEvent, logger, { requestId, ...event });
    const withRequestId = (response) => ({
      ...response,
      headers: { ...response.headers, "X-Request-Id": requestId },
    });
    const reject = (response) => {
      emit({
        type: "rejected",
        status: response.status,
        reason: response.body?.error?.details?.[0]?.reason || "PORTAUTH_REJECTED",
        durationMs: Date.now() - startedAt,
      });
      return withRequestId(response);
    };

    const requestValidation = validateA2aSendMessageRequest(body);
    if (!requestValidation.ok) {
      return reject(a2aError(400, "PORTAUTH_A2A_INVALID_MESSAGE", "Invalid A2A SendMessageRequest", {
        violations: JSON.stringify(requestValidation.errors),
      }));
    }

    const message = body.message;
    const activationHeader = getHeader(headers, "a2a-extensions");
    const activated = extensionHeaderIncludes(activationHeader);
    const carriesMetadata = Object.keys(message.metadata || {}).some((key) => key.startsWith(`${EXTENSION_URI}/`));

    if (required && !activated) {
      return reject(a2aError(412, "PORTAUTH_EXTENSION_REQUIRED", "A2A-Extensions header must activate the PortAuth extension", {
        extensionUri: EXTENSION_URI,
      }));
    }
    if (!activated && !carriesMetadata) {
      return reject(a2aError(400, "PORTAUTH_EXTENSION_NOT_ACTIVATED", "Request does not activate or carry the PortAuth extension", {
        extensionUri: EXTENSION_URI,
      }));
    }
    if (Array.isArray(message.extensions) && !message.extensions.includes(EXTENSION_URI)) {
      return reject(a2aError(400, "PORTAUTH_MESSAGE_EXTENSION_MISSING", "message.extensions must include the PortAuth extension URI", {
        extensionUri: EXTENSION_URI,
      }));
    }

    let portauth;
    try {
      portauth = extractPortAuthMetadata(message);
    } catch (err) {
      return reject(a2aError(400, "PORTAUTH_METADATA_INVALID", err.message, {
        extensionUri: EXTENSION_URI,
      }));
    }

    if (!acceptedProfiles.includes(portauth.vcFormat)) {
      return reject(a2aError(400, "PORTAUTH_UNSUPPORTED_VC_FORMAT", `Unsupported vcFormat: ${portauth.vcFormat}`, {
        vcFormat: portauth.vcFormat,
      }));
    }

    let requestContext;
    try {
      requestContext = await mapRequestContext({ message, body, portauth });
    } catch (err) {
      return reject(a2aError(400, "PORTAUTH_REQUEST_CONTEXT_INVALID", err.message || "Failed to map A2A message to PortAuth requestContext"));
    }
    const contextValidation = validateRequestContext(requestContext);
    if (!contextValidation.ok) {
      return reject(a2aError(400, "PORTAUTH_REQUEST_CONTEXT_INVALID", contextValidation.message));
    }

    // Mandatory proof-of-possession policy. When the receiver is configured to
    // require PoP for this request, a credential presented without a signed
    // <URI>/proofOfPossession is rejected before the engine is ever called, so a
    // stolen bearer-equivalent VC cannot be replayed against a sensitive action.
    // The engine still performs the cryptographic verification of the proof; this
    // policy makes its presence non-optional. Fails closed if the policy throws.
    if (isProofOfPossessionRequired(requireProofOfPossession, { requestContext, portauth, message }, logger)
        && !portauth.proofOfPossession) {
      return reject(a2aError(401, "PORTAUTH_POP_REQUIRED", "Proof of possession is required for this request", {
        action: requestContext.action,
      }));
    }

    const idempotencyKey = resolveReceiverIdempotencyKey({ message, portauth });
    const taskId = message.taskId || `task-${randomUUID()}`;
    let recordId = `task-record-${randomUUID()}`;
    const contextId = message.contextId || `context-${randomUUID()}`;
    const pendingTask = buildLifecycleTask({
      taskId,
      contextId,
      state: "TASK_STATE_SUBMITTED",
      decision: "pending",
      idempotencyKey,
      text: "PortAuth authorization is pending.",
    });
    let pendingRecord;
    try {
      const pendingResult = await taskStore.createPending({
        id: recordId,
        taskId,
        idempotencyKey,
        lifecycleState: "pending",
        task: pendingTask,
        response: null,
        requestContext,
        presenterId: portauth.presenterId,
        vcFormat: portauth.vcFormat,
        auditRecordId: null,
        errorReason: null,
      });
      pendingRecord = pendingResult.record;
      recordId = pendingRecord.id;
      if (!pendingResult.created) {
        const replay = replayResponseFromTaskRecord(pendingRecord);
        if (replay) {
          emit({
            type: "replay",
            taskId,
            idempotencyKey,
            lifecycleState: pendingRecord.lifecycleState,
            auditRecordId: pendingRecord.auditRecordId,
            status: replay.status,
            durationMs: Date.now() - startedAt,
          });
          return withRequestId(replay);
        }
        if (pendingRecord.lifecycleState !== "failed") {
          emit({ type: "in_progress", taskId, idempotencyKey, durationMs: Date.now() - startedAt });
          return withRequestId(pendingResponseFromTaskRecord(pendingRecord));
        }
        pendingRecord = await taskStore.update(recordId, {
          taskId,
          lifecycleState: "pending",
          task: pendingTask,
          response: null,
          requestContext,
          presenterId: portauth.presenterId,
          vcFormat: portauth.vcFormat,
          auditRecordId: null,
          errorReason: null,
        });
      }
    } catch (err) {
      logger.error?.({ msg: "A2A task persistence failed before engine evaluation", requestId, error: err.message });
      emit({ type: "persistence_failed", phase: "pending", taskId, durationMs: Date.now() - startedAt });
      return withRequestId(a2aError(500, "PORTAUTH_TASK_PERSISTENCE_FAILED", "Failed to persist task before PortAuth evaluation"));
    }

    const engineBody = buildEngineRequest(portauth, requestContext, { idempotencyKey });
    const endpoint = portauth.delegationChain.length > 0 ? "/evaluate/batch" : "/evaluate";
    const engineStartedAt = Date.now();
    const engineResult = await postJson(
      new URL(endpoint.replace(/^\//, ""), ensureTrailingSlash(engineUrl)),
      engineBody,
      fetchImpl,
      { authToken: engineAuthToken, requestId },
    );
    const engineDurationMs = Date.now() - engineStartedAt;

    if (!engineResult.ok && !engineResult.body?.decision) {
      const failedTask = buildLifecycleTask({
        taskId,
        contextId,
        state: "TASK_STATE_FAILED",
        decision: "error",
        idempotencyKey,
        text: "PortAuth engine request failed before task acceptance.",
      });
      const failedResponse = a2aError(engineResult.status >= 500 ? 503 : 400, "PORTAUTH_ENGINE_UNAVAILABLE", "PortAuth engine request failed", {
        engineStatus: String(engineResult.status),
      });
      const failedResult = await persistFinalResponse({
        taskStore,
        recordId,
        patch: {
          taskId,
          lifecycleState: "failed",
          task: failedTask,
          response: failedResponse,
          errorReason: "PORTAUTH_ENGINE_UNAVAILABLE",
        },
        response: failedResponse,
        logger,
        requestId,
        emit,
      });
      emit({
        type: "decision",
        decision: "error",
        lifecycleState: "failed",
        taskId,
        idempotencyKey,
        engineError: "PORTAUTH_ENGINE_UNAVAILABLE",
        status: failedResult.status,
        engineDurationMs,
        durationMs: Date.now() - startedAt,
      });
      return withRequestId(failedResult);
    }

    if (engineResult.body?.decision !== "allow") {
      const mapped = mapEngineDecisionToA2aError(engineResult.body || {}, engineResult.status === 422 ? 401 : 403);
      const deniedResponse = {
        status: mapped.httpStatus,
        headers: responseHeaders(),
        body: mapped.body,
      };
      const deniedTask = buildLifecycleTask({
        taskId,
        contextId,
        state: "TASK_STATE_REJECTED",
        decision: "deny",
        idempotencyKey,
        auditRecordId: engineResult.body?.auditRecordId,
        engineError: engineResult.body?.error || "authorization_denied",
        text: "PortAuth authorization denied the task.",
      });
      const deniedResult = await persistFinalResponse({
        taskStore,
        recordId,
        patch: {
          taskId,
          lifecycleState: "denied",
          task: deniedTask,
          response: deniedResponse,
          auditRecordId: engineResult.body?.auditRecordId,
          errorReason: engineResult.body?.error || "authorization_denied",
        },
        response: deniedResponse,
        logger,
        requestId,
        emit,
      });
      emit({
        type: "decision",
        decision: "deny",
        lifecycleState: "denied",
        taskId,
        idempotencyKey,
        engineError: engineResult.body?.error || "authorization_denied",
        auditRecordId: engineResult.body?.auditRecordId,
        status: deniedResult.status,
        engineDurationMs,
        durationMs: Date.now() - startedAt,
      });
      return withRequestId(deniedResult);
    }

    const task = buildCompletedTask({
      message: { ...message, taskId, contextId },
      auditRecordId: engineResult.body.auditRecordId,
      text: "PortAuth authorization succeeded; reference receiver accepted the task.",
      metadata: { idempotencyKey },
    });
    const successResponse = {
      status: 200,
      headers: responseHeaders(),
      body: { task },
    };
    const finalResponse = await persistFinalResponse({
      taskStore,
      recordId,
      patch: {
        taskId,
        lifecycleState: "completed",
        task,
        response: successResponse,
        auditRecordId: engineResult.body.auditRecordId,
      },
      response: successResponse,
      logger,
      requestId,
      emit,
    });
    emit({
      type: "decision",
      decision: finalResponse.status === 200 ? "allow" : "error",
      lifecycleState: finalResponse.status === 200 ? "completed" : "failed",
      taskId,
      idempotencyKey,
      auditRecordId: engineResult.body.auditRecordId,
      status: finalResponse.status,
      engineDurationMs,
      durationMs: Date.now() - startedAt,
    });
    logger.info?.({
      msg: "A2A request authorized by PortAuth",
      requestId,
      taskId: task.id,
      auditRecordId: engineResult.body.auditRecordId,
    });

    return withRequestId(finalResponse);
  }

  return {
    handleSendMessage,
    taskStore,
  };
}

export function buildEngineRequest(portauth, requestContext, { idempotencyKey } = {}) {
  const effectiveIdempotencyKey = portauth.idempotencyKey || idempotencyKey || requestContext.idempotencyKey;
  if (portauth.delegationChain.length > 0) {
    return {
      credentials: [...portauth.delegationChain, portauth.credential],
      presenterId: portauth.presenterId,
      requestContext,
      ...(portauth.proofOfPossession ? { proofOfPossession: portauth.proofOfPossession } : {}),
      ...(effectiveIdempotencyKey ? { idempotencyKey: effectiveIdempotencyKey } : {}),
    };
  }
  return {
    credential: portauth.credential,
    presenterId: portauth.presenterId,
    requestContext,
    ...(portauth.proofOfPossession ? { proofOfPossession: portauth.proofOfPossession } : {}),
    ...(effectiveIdempotencyKey ? { idempotencyKey: effectiveIdempotencyKey } : {}),
  };
}

export function validateRequestContext(requestContext) {
  if (!requestContext || typeof requestContext !== "object") {
    return { ok: false, message: "Mapped requestContext must be an object" };
  }
  if (typeof requestContext.action !== "string" || requestContext.action.length === 0) {
    return { ok: false, message: "Mapped requestContext must include action" };
  }
  if (typeof requestContext.resource !== "string" || requestContext.resource.length === 0) {
    return { ok: false, message: "Mapped requestContext must include resource" };
  }
  for (const [key, value] of Object.entries(requestContext)) {
    if (typeof value === "number" && !Number.isFinite(value)) {
      return { ok: false, message: `Mapped requestContext field '${key}' must be a finite number` };
    }
  }
  return { ok: true };
}

function a2aError(status, reason, message, metadata = {}) {
  return {
    status,
    headers: responseHeaders(),
    body: buildGoogleRpcStatus({
      httpStatus: status,
      reason,
      message,
      metadata,
    }),
  };
}

function responseHeaders() {
  return {
    "Content-Type": A2A_MEDIA_TYPE,
    "A2A-Version": "1.0",
    "A2A-Extensions": EXTENSION_URI,
  };
}

function resolveReceiverIdempotencyKey({ message, portauth }) {
  return portauth.idempotencyKey || message.messageId;
}

// Decide whether proof-of-possession is mandatory for this request. Accepts a
// boolean (require always / never) or a predicate that inspects the mapped
// requestContext and PortAuth metadata. A throwing predicate fails closed
// (treated as "required") so a policy bug cannot silently disable PoP.
export function isProofOfPossessionRequired(policy, input, logger = console) {
  if (typeof policy === "function") {
    try {
      return Boolean(policy(input));
    } catch (err) {
      logger?.error?.({ msg: "A2A requireProofOfPossession policy threw; failing closed", error: err.message });
      return true;
    }
  }
  return Boolean(policy);
}

function buildLifecycleTask({
  taskId,
  contextId,
  state,
  decision,
  idempotencyKey,
  auditRecordId,
  engineError,
  text,
}) {
  const metadata = {
    portauthDecision: decision,
    idempotencyKey,
    ...(auditRecordId ? { auditRecordId } : {}),
    ...(engineError ? { engineError } : {}),
  };
  return {
    id: taskId,
    contextId,
    status: {
      state,
      message: {
        messageId: randomUUID(),
        contextId,
        taskId,
        role: "ROLE_AGENT",
        parts: [{ text }],
        extensions: [EXTENSION_URI],
        metadata,
      },
    },
    metadata,
  };
}

async function persistFinalResponse({ taskStore, recordId, patch, response, logger, requestId, emit }) {
  try {
    await taskStore.update(recordId, patch);
    return response;
  } catch (err) {
    logger.error?.({ msg: "A2A task persistence failed after PortAuth evaluation", requestId, recordId, error: err.message });
    emit?.({ type: "persistence_failed", phase: "final", taskId: patch.taskId });
    return a2aError(500, "PORTAUTH_TASK_PERSISTENCE_FAILED", "Failed to persist final task state after PortAuth evaluation");
  }
}

// Emit a structured lifecycle event to an optional observer. Monitoring must
// never break request handling, so observer errors are swallowed and logged.
function emitEvent(onEvent, logger, event) {
  if (typeof onEvent !== "function") return;
  try {
    onEvent(event);
  } catch (err) {
    logger?.error?.({ msg: "A2A onEvent observer threw", type: event?.type, error: err.message });
  }
}

function replayResponseFromTaskRecord(record) {
  if ((record.lifecycleState === "completed" || record.lifecycleState === "denied") && record.response) {
    return record.response;
  }
  return null;
}

function pendingResponseFromTaskRecord(record) {
  return {
    status: 202,
    headers: responseHeaders(),
    body: { task: record.task },
  };
}

function getHeader(headers, name) {
  if (!headers) return "";
  if (typeof headers.get === "function") return headers.get(name) || headers.get(name.toLowerCase()) || "";
  const lower = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === lower) return Array.isArray(value) ? value.join(",") : value;
  }
  return "";
}

async function postJson(url, body, fetchImpl, { authToken = null, requestId = null } = {}) {
  const resp = await fetchImpl(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
      ...(requestId ? { "X-Request-Id": requestId } : {}),
    },
    body: JSON.stringify(body),
  });
  const text = await resp.text();
  let parsed = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch (_) {
    parsed = { raw: text };
  }
  return { ok: resp.ok, status: resp.status, body: parsed };
}

function ensureTrailingSlash(value) {
  const text = String(value);
  return text.endsWith("/") ? text : `${text}/`;
}

async function selectExistingRecord(queryable, table, record) {
  const result = await queryable.query(
    `SELECT * FROM ${table} WHERE id = $1 OR idempotency_key = $2 ORDER BY updated_at DESC LIMIT 1`,
    [record.id, record.idempotencyKey],
  );
  return result.rows[0] ? rowToTaskRecord(result.rows[0]) : null;
}

function findExistingMemoryRecord(recordsById, idsByIdempotencyKey, record) {
  if (recordsById.has(record.id)) return recordsById.get(record.id);
  const id = idsByIdempotencyKey.get(record.idempotencyKey);
  return id ? recordsById.get(id) || null : null;
}

function rowToTaskRecord(row) {
  return {
    id: row.id,
    taskId: row.task_id,
    idempotencyKey: row.idempotency_key,
    lifecycleState: row.lifecycle_state,
    task: row.task,
    response: row.response,
    requestContext: row.request_context,
    presenterId: row.presenter_id,
    vcFormat: row.vc_format,
    auditRecordId: row.audit_record_id,
    errorReason: row.error_reason,
    createdAt: toIsoString(row.created_at),
    updatedAt: toIsoString(row.updated_at),
  };
}

function toIsoString(value) {
  if (!value) return value;
  return value instanceof Date ? value.toISOString() : String(value);
}

function jsonParam(value) {
  return value === undefined ? null : JSON.stringify(value);
}

function stripUndefined(input) {
  return Object.fromEntries(Object.entries(input).filter(([, value]) => value !== undefined));
}

function assertQueryable(queryable) {
  if (!queryable || typeof queryable.query !== "function") {
    throw new Error("queryable with query(sql, params) is required");
  }
}

function quoteIdentifier(value) {
  const text = String(value);
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(text)) {
    throw new Error(`invalid PostgreSQL identifier: ${text}`);
  }
  return `"${text.replaceAll("\"", "\"\"")}"`;
}
