/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

// Versioned migrations for the Postgres task store. Unlike a "run every .sql on
// boot" approach, this records applied versions in a ledger table and applies
// only the pending ones, each inside its own transaction. The set of migrations
// is the source of truth for the schema; `createPostgresTaskStoreSchemaSql`
// remains for callers that want the flattened current DDL.

// Each migration is { version, name, up(table) -> sql }. `table` and the ledger
// table name are already quoted identifiers. Keep migrations append-only and
// immutable once released: add a new version, never edit a shipped one.
export const TASK_STORE_MIGRATIONS = [
  {
    version: 1,
    name: "create_task_store",
    up: (table) => `
CREATE TABLE IF NOT EXISTS ${table} (
  id TEXT PRIMARY KEY,
  idempotency_key TEXT NOT NULL UNIQUE,
  lifecycle_state TEXT NOT NULL,
  task JSONB,
  response JSONB,
  request_context JSONB,
  presenter_id TEXT,
  vc_format TEXT,
  audit_record_id TEXT,
  error_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
`,
  },
  {
    version: 2,
    name: "add_task_id_and_indexes",
    up: (table, { tableName }) => `
ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS task_id TEXT;
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${tableName}_audit_record_id_idx`)} ON ${table} (audit_record_id);
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${tableName}_task_id_idx`)} ON ${table} (task_id);
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${tableName}_updated_at_idx`)} ON ${table} (updated_at DESC);
`,
  },
];

// Apply all pending task-store migrations. Returns the list of versions applied
// during this call. Idempotent: re-running applies nothing new. Uses a dedicated
// connection (pg Pool.connect) for real per-migration transactions when the
// queryable supports it; otherwise falls back to plain statements.
export async function runTaskStoreMigrations(queryable, { tableName = "portauth_a2a_tasks", migrations = TASK_STORE_MIGRATIONS } = {}) {
  assertQueryable(queryable);
  const table = quoteIdentifier(tableName);
  const ledger = quoteIdentifier(`${tableName}_migrations`);

  await queryable.query(`
CREATE TABLE IF NOT EXISTS ${ledger} (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);`);

  const appliedRows = await queryable.query(`SELECT version FROM ${ledger}`);
  const applied = new Set(appliedRows.rows.map((row) => Number(row.version)));

  const pending = [...migrations]
    .sort((a, b) => a.version - b.version)
    .filter((migration) => !applied.has(migration.version));

  const transactional = typeof queryable.connect === "function";
  const appliedNow = [];

  for (const migration of pending) {
    const ddl = migration.up(table, { tableName });
    const recordSql = `INSERT INTO ${ledger} (version, name) VALUES ($1, $2)`;

    if (transactional) {
      const client = await queryable.connect();
      try {
        await client.query("BEGIN");
        await client.query(ddl);
        await client.query(recordSql, [migration.version, migration.name]);
        await client.query("COMMIT");
      } catch (err) {
        await client.query("ROLLBACK").catch(() => {});
        throw err;
      } finally {
        client.release();
      }
    } else {
      await queryable.query(ddl);
      await queryable.query(recordSql, [migration.version, migration.name]);
    }
    appliedNow.push(migration.version);
  }

  return { applied: appliedNow, total: migrations.length };
}

function assertQueryable(queryable) {
  if (!queryable || typeof queryable.query !== "function") {
    throw new Error("queryable with query(sql, params) is required");
  }
}

export function quoteIdentifier(value) {
  const text = String(value);
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(text)) {
    throw new Error(`invalid PostgreSQL identifier: ${text}`);
  }
  return `"${text.replaceAll("\"", "\"\"")}"`;
}
