// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import crypto from "node:crypto";

/**
 * Timing-safe API key authentication middleware.
 * Checks the Authorization header for "Bearer <ADMIN_API_KEY>".
 */
export function requireAdminAuth(req, res, next) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "unauthorized", message: "Missing or invalid Authorization header" });
  }
  const token = authHeader.slice(7);
  const expected = process.env.ADMIN_API_KEY || "";

  if (token.length !== expected.length) {
    return res.status(401).json({ error: "unauthorized", message: "Invalid API key" });
  }
  if (!crypto.timingSafeEqual(Buffer.from(token), Buffer.from(expected))) {
    return res.status(401).json({ error: "unauthorized", message: "Invalid API key" });
  }
  next();
}
