// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import * as jose from "jose";
import { v4 as uuidv4 } from "uuid";
import { getActiveSigningKey } from "./keyManager.js";
import { getPool } from "../db/pool.js";
import logger from "./logger.js";

/**
 * Issue a JWS/JWT authorization credential.
 *
 * @param {object} params
 * @param {string} params.agentId     - sub claim
 * @param {string} [params.audience]  - aud claim
 * @param {string[]} params.permissions
 * @param {object[]} params.constraints - typed constraint objects
 * @param {string} [params.validFrom]  - ISO 8601, defaults to now
 * @param {string} [params.validUntil] - ISO 8601, defaults to now + DEFAULT_TTL_HOURS
 * @param {string} [params.delegatedFrom] - parent credential ID (for delegation)
 * @param {object} [params.proofKeyJwk] - public JWK used for request-level proof of possession
 * @returns {object} { credentialId, credential (compact JWT), format, issuerId, validFrom, validUntil }
 */
export async function issueCredential({
  agentId,
  audience,
  permissions,
  constraints,
  validFrom,
  validUntil,
  delegatedFrom,
  proofKeyJwk,
}) {
  const { kid, algorithm, privateKey } = await getActiveSigningKey();
  const issuerId = process.env.ISSUER_ID || "https://portauth-issuer.local";
  const credentialId = `urn:uuid:${uuidv4()}`;

  const now = new Date();
  const vf = validFrom ? new Date(validFrom) : now;
  const defaultTtlHours = parseInt(process.env.DEFAULT_TTL_HOURS || "24", 10);
  const vu = validUntil ? new Date(validUntil) : new Date(vf.getTime() + defaultTtlHours * 3600_000);

  // Enforce max TTL
  const maxTtlHours = parseInt(process.env.MAX_TTL_HOURS || "720", 10);
  const maxMs = maxTtlHours * 3600_000;
  if (vu.getTime() - vf.getTime() > maxMs) {
    throw Object.assign(new Error(`TTL exceeds maximum of ${maxTtlHours} hours`), { code: "ttl_exceeded" });
  }

  const payload = {
    iss: issuerId,
    sub: agentId,
    jti: credentialId,
    permissions,
    constraints,
  };

  logger.info({ 
    msg: "📜 STORY STEP 1: Creating the Normative Core (Layer 2)", 
    credentialId,
    agentId,
    permissions,
    constraints 
  });

  if (audience) payload.aud = audience;
  if (delegatedFrom) payload.delegatedFrom = delegatedFrom;
  if (proofKeyJwk) payload.cnf = { jwk: proofKeyJwk };

  const jwt = await new jose.SignJWT(payload)
    .setProtectedHeader({ typ: "JWT", alg: algorithm, kid })
    .setIssuedAt()
    .setNotBefore(vf)
    .setExpirationTime(vu)
    .sign(privateKey);

  // Persist
  const pool = getPool();
  await pool.query(
    `INSERT INTO portauth_issued_credentials
       (credential_id, issuer_id, agent_id, audience, permissions, constraints, valid_from, valid_until, kid)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
    [credentialId, issuerId, agentId, audience, JSON.stringify(permissions), JSON.stringify(constraints), vf, vu, kid]
  );

  return {
    credentialId,
    credential: jwt,
    format: "jwt",
    issuerId,
    validFrom: vf.toISOString(),
    validUntil: vu.toISOString(),
  };
}

/**
 * Revoke a credential by ID.
 */
export async function revokeCredential(credentialId, reason) {
  const pool = getPool();
  const { rowCount } = await pool.query(
    `UPDATE portauth_issued_credentials
     SET revoked = TRUE, revoked_at = NOW(), revoke_reason = $2
     WHERE credential_id = $1 AND revoked = FALSE`,
    [credentialId, reason || null]
  );
  if (rowCount === 0) {
    throw Object.assign(new Error("Credential not found or already revoked"), { code: "not_found" });
  }
}

/**
 * Check whether a credential is revoked.
 */
export async function isRevoked(credentialId) {
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT revoked FROM portauth_issued_credentials WHERE credential_id = $1`,
    [credentialId]
  );
  if (rows.length === 0) return null; // unknown credential
  return rows[0].revoked;
}

/**
 * Lookup credential metadata by ID (for introspection).
 */
export async function introspectCredential(credentialId) {
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT credential_id, issuer_id, agent_id, permissions, constraints,
            valid_from, valid_until, revoked, revoked_at, issued_at
     FROM portauth_issued_credentials WHERE credential_id = $1`,
    [credentialId]
  );
  if (rows.length === 0) return null;
  const row = rows[0];
  return {
    active: !row.revoked && new Date() >= new Date(row.valid_from) && new Date() <= new Date(row.valid_until),
    credentialId: row.credential_id,
    issuerId: row.issuer_id,
    agentId: row.agent_id,
    permissions: row.permissions,
    constraints: row.constraints,
    validFrom: row.valid_from,
    validUntil: row.valid_until,
    revoked: row.revoked,
    revokedAt: row.revoked_at,
    issuedAt: row.issued_at,
  };
}
