// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import { gzipSync } from "node:zlib";
import { getPool } from "../db/pool.js";

function normalizePurpose(purpose) {
  return purpose === "suspension" ? "suspension" : "revocation";
}

export function deriveStatusListUrl(purpose = "revocation") {
  const normalizedPurpose = normalizePurpose(purpose);
  if (process.env.VC_STATUS_LIST_URL && normalizedPurpose === "revocation") {
    return process.env.VC_STATUS_LIST_URL;
  }

  const publicBaseUrl = process.env.ISSUER_PUBLIC_URL
    || (process.env.ISSUER_ID && process.env.ISSUER_ID.startsWith("http") ? process.env.ISSUER_ID : null);

  if (!publicBaseUrl) {
    return null;
  }

  return `${publicBaseUrl.replace(/\/$/, "")}/.well-known/status-list/${normalizedPurpose}`;
}

function setBit(buffer, index) {
  const byteIndex = Math.floor(index / 8);
  const bitIndex = 7 - (index % 8);
  buffer[byteIndex] |= 1 << bitIndex;
}

export function buildEncodedStatusListFromEntries(entries) {
  const maxIndex = entries.reduce((currentMax, entry) => {
    if (!Number.isInteger(entry.status_list_index) || entry.status_list_index < 0) {
      return currentMax;
    }
    return Math.max(currentMax, entry.status_list_index);
  }, -1);

  const byteLength = Math.max(1, Math.ceil((maxIndex + 1) / 8));
  const bitstring = Buffer.alloc(byteLength);

  for (const entry of entries) {
    if (entry.revoked === true || entry.suspended === true) {
      setBit(bitstring, entry.status_list_index);
    }
  }

  return gzipSync(bitstring).toString("base64url");
}

export async function buildStatusListCredential(purpose = "revocation") {
  const normalizedPurpose = normalizePurpose(purpose);
  const statusListUrl = deriveStatusListUrl(normalizedPurpose);
  if (!statusListUrl) {
    throw Object.assign(
      new Error("Unable to derive status list URL. Set VC_STATUS_LIST_URL, ISSUER_PUBLIC_URL, or an HTTP ISSUER_ID."),
      { code: "configuration_error" }
    );
  }

  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT cs.status_list_index, cs.status_purpose, ic.revoked
     FROM portauth_credential_status cs
     JOIN portauth_issued_credentials ic ON ic.credential_id = cs.credential_id
     WHERE cs.status_purpose = $1
     ORDER BY cs.status_list_index ASC`,
    [normalizedPurpose]
  );

  const encodedList = buildEncodedStatusListFromEntries(
    rows.map((row) => ({
      status_list_index: row.status_list_index,
      revoked: normalizedPurpose === "revocation" ? row.revoked === true : false,
      suspended: false,
    }))
  );

  return {
    "@context": ["https://www.w3.org/ns/credentials/v2"],
    id: statusListUrl,
    type: ["VerifiableCredential", "BitstringStatusListCredential"],
    issuer: process.env.VC_ISSUER_DID || process.env.ISSUER_ID || "did:web:portauth-issuer.local",
    validFrom: new Date().toISOString(),
    credentialSubject: {
      id: `${statusListUrl}#list`,
      type: "BitstringStatusList",
      statusPurpose: normalizedPurpose,
      encodedList,
    },
  };
}
