// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

/**
 * VC-JOSE Credential Issuer
 *
 * Issues W3C Verifiable Credentials secured with JOSE/JWS (vc+jwt format).
 * Same Layer 2 authorization payload as the plain JWT issuer — no new semantics.
 *
 * The VC wraps the authorization payload in the W3C VC Data Model:
 *   - JWT header: { typ: "vc+jwt", alg, kid }
 *   - JWT payload: { iss (DID), sub, jti, nbf, exp, vc: { ... } }
 *   - vc claim: { @context, type, credentialSubject, termsOfUse, credentialStatus? }
 *
 * Supports Bitstring Status List for revocation.
 */

import * as jose from "jose";
import { v4 as uuidv4 } from "uuid";
import { getActiveSigningKey } from "./keyManager.js";
import { getPool } from "../db/pool.js";
import { deriveStatusListUrl } from "./statusListPublisher.js";

/**
 * Issue a VC-JOSE authorization credential.
 *
 * @param {object} params
 * @param {string} params.agentId       - credentialSubject.id / sub claim
 * @param {string} [params.audience]    - aud claim
 * @param {string[]} params.permissions - declared action identifiers
 * @param {object[]} params.constraints - typed constraint objects
 * @param {string} [params.validFrom]   - ISO 8601
 * @param {string} [params.validUntil]  - ISO 8601
 * @param {string} [params.delegatedFrom] - parent credential ID
 * @param {object} [params.proofKeyJwk] - public JWK used for request-level proof of possession
 * @returns {object} { credentialId, credential (compact JWT), format, issuerId, validFrom, validUntil }
 */
export async function issueVcCredential({
  agentId,
  audience,
  permissions,
  constraints,
  validFrom,
  validUntil,
  delegatedFrom,
  proofKeyJwk,
}) {
  const { kid, algorithm, privateKey } = await getActiveSigningKey();

  // VC issuer identity — must be a DID for Tier 3
  const issuerId = process.env.VC_ISSUER_DID || process.env.ISSUER_ID || "did:web:portauth-issuer.local";
  if (!issuerId.startsWith("did:")) {
    throw Object.assign(
      new Error("VC_ISSUER_DID must be a DID (e.g., did:web:example.com)"),
      { code: "configuration_error" }
    );
  }

  const credentialId = `urn:uuid:${uuidv4()}`;

  const now = new Date();
  const vf = validFrom ? new Date(validFrom) : now;
  const defaultTtlHours = parseInt(process.env.DEFAULT_TTL_HOURS || "24", 10);
  const vu = validUntil ? new Date(validUntil) : new Date(vf.getTime() + defaultTtlHours * 3600_000);

  // Enforce max TTL
  const maxTtlHours = parseInt(process.env.MAX_TTL_HOURS || "720", 10);
  const maxMs = maxTtlHours * 3600_000;
  if (vu.getTime() - vf.getTime() > maxMs) {
    throw Object.assign(new Error(`TTL exceeds maximum of ${maxTtlHours} hours`), { code: "ttl_exceeded" });
  }

  // Build the W3C VC Data Model payload
  const credentialSubject = {
    id: agentId,
    permissions,
    constraints,
  };
  if (delegatedFrom) {
    credentialSubject.delegatedFrom = delegatedFrom;
  }
  if (proofKeyJwk) {
    credentialSubject.cnf = { jwk: proofKeyJwk };
  }

  const vc = {
    "@context": [
      "https://www.w3.org/ns/credentials/v2",
    ],
    type: ["VerifiableCredential", "AgentAuthorizationCredential"],
    issuer: issuerId,
    validFrom: vf.toISOString(),
    validUntil: vu.toISOString(),
    credentialSubject,
  };

  // Optionally add Bitstring Status List entry
  const statusListUrl = deriveStatusListUrl("revocation");
  let statusListIndex = null;
  if (statusListUrl) {
    statusListIndex = await allocateStatusListIndex();
    vc.credentialStatus = {
      type: "BitstringStatusListEntry",
      statusPurpose: "revocation",
      statusListIndex: String(statusListIndex),
      statusListCredential: statusListUrl,
    };
  }

  // Build JWT payload — VC JOSE/COSE format puts the VC in a `vc` claim
  const jwtPayload = {
    iss: issuerId,
    sub: agentId,
    jti: credentialId,
    vc,
  };
  if (audience) jwtPayload.aud = audience;
  if (proofKeyJwk) jwtPayload.cnf = { jwk: proofKeyJwk };

  // Sign as vc+jwt
  const jwt = await new jose.SignJWT(jwtPayload)
    .setProtectedHeader({ typ: "vc+jwt", alg: algorithm, kid })
    .setIssuedAt()
    .setNotBefore(vf)
    .setExpirationTime(vu)
    .sign(privateKey);

  // Persist
  const pool = getPool();
  await pool.query(
    `INSERT INTO portauth_issued_credentials
       (credential_id, issuer_id, agent_id, audience, permissions, constraints,
        valid_from, valid_until, kid, format, status_list_index, did_issuer_id)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
    [
      credentialId, issuerId, agentId, audience,
      JSON.stringify(permissions), JSON.stringify(constraints),
      vf, vu, kid, "vc-jose", statusListIndex, issuerId,
    ]
  );

  // If status list is used, persist status entry
  if (statusListUrl && statusListIndex !== null) {
    await pool.query(
      `INSERT INTO portauth_credential_status
         (credential_id, status_list_url, status_list_index, status_purpose)
       VALUES ($1, $2, $3, $4)`,
      [credentialId, statusListUrl, statusListIndex, "revocation"]
    );
  }

  return {
    credentialId,
    credential: jwt,
    format: "vc-jose",
    issuerId,
    validFrom: vf.toISOString(),
    validUntil: vu.toISOString(),
  };
}

/**
 * Allocate the next available status list index.
 * Simple monotonic counter stored in the delegation_config table.
 */
async function allocateStatusListIndex() {
  const pool = getPool();

  // Atomic increment using INSERT ON CONFLICT
  const { rows } = await pool.query(
    `INSERT INTO portauth_delegation_config (key, value) VALUES ('status_list_next_index', '1')
     ON CONFLICT (key) DO UPDATE SET value = (portauth_delegation_config.value::integer + 1)::text
     RETURNING value`
  );

  return parseInt(rows[0].value, 10) - 1; // Return the index we just allocated (before increment)
}
