// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans

import crypto from "node:crypto";
import { X509Certificate } from "node:crypto";
import * as jose from "jose";
import { v4 as uuidv4 } from "uuid";
import { getPool } from "../db/pool.js";
import logger from "./logger.js";

function normalizePemText(value) {
  return String(value || "").replace(/\\n/g, "\n").trim();
}

function pemCertificatesToX5c(pemText) {
  const matches = normalizePemText(pemText).match(/-----BEGIN CERTIFICATE-----[\s\S]+?-----END CERTIFICATE-----/g) || [];
  return matches.map((pem) => pem
    .replace(/-----BEGIN CERTIFICATE-----/g, "")
    .replace(/-----END CERTIFICATE-----/g, "")
    .replace(/\s+/g, ""));
}

function leafFingerprintBase64url(x5cEntry) {
  return crypto.createHash("sha256")
    .update(Buffer.from(x5cEntry, "base64"))
    .digest("base64url");
}

async function getX509SigningMaterial() {
  const privateKeyPem = normalizePemText(process.env.X509_PRIVATE_KEY_PEM);
  const certChainPem = normalizePemText(process.env.X509_CERT_CHAIN_PEM);

  if (!privateKeyPem || !certChainPem) {
    throw Object.assign(
      new Error("X509_PRIVATE_KEY_PEM and X509_CERT_CHAIN_PEM must be configured for Tier 2 issuance"),
      { code: "configuration_error" }
    );
  }

  const x5c = pemCertificatesToX5c(certChainPem);
  if (x5c.length === 0) {
    throw Object.assign(new Error("X509_CERT_CHAIN_PEM does not contain a certificate"), { code: "configuration_error" });
  }

  const algorithm = process.env.X509_SIGNING_ALGORITHM || process.env.SIGNING_ALGORITHM || "ES256";
  const privateKey = await jose.importPKCS8(privateKeyPem, algorithm);
  const leafCertificate = new X509Certificate(`-----BEGIN CERTIFICATE-----\n${x5c[0].match(/.{1,64}/g).join("\n")}\n-----END CERTIFICATE-----`);
  const thumbprint = leafFingerprintBase64url(x5c[0]);

  return {
    algorithm,
    privateKey,
    x5c,
    leafCertificate,
    kid: process.env.X509_KEY_ID || thumbprint,
    thumbprint,
  };
}

/**
 * Issue a Tier 2 X.509-backed JWT authorization credential.
 */
export async function issueX509Credential({
  agentId,
  audience,
  permissions,
  constraints,
  validFrom,
  validUntil,
  delegatedFrom,
  proofKeyJwk,
}) {
  const { algorithm, privateKey, x5c, kid, thumbprint } = await getX509SigningMaterial();
  const issuerId = process.env.X509_ISSUER_ID || process.env.ISSUER_ID || "https://portauth-issuer.local";
  const credentialId = `urn:uuid:${uuidv4()}`;

  const now = new Date();
  const vf = validFrom ? new Date(validFrom) : now;
  const defaultTtlHours = parseInt(process.env.DEFAULT_TTL_HOURS || "24", 10);
  const vu = validUntil ? new Date(validUntil) : new Date(vf.getTime() + defaultTtlHours * 3600_000);

  const maxTtlHours = parseInt(process.env.MAX_TTL_HOURS || "720", 10);
  if (vu.getTime() - vf.getTime() > maxTtlHours * 3600_000) {
    throw Object.assign(new Error(`TTL exceeds maximum of ${maxTtlHours} hours`), { code: "ttl_exceeded" });
  }

  const payload = {
    iss: issuerId,
    sub: agentId,
    jti: credentialId,
    permissions,
    constraints,
  };

  if (audience) payload.aud = audience;
  if (delegatedFrom) payload.delegatedFrom = delegatedFrom;
  if (proofKeyJwk) payload.cnf = { jwk: proofKeyJwk };

  logger.info({
    msg: "STORY STEP 1: Creating the Normative Core (Layer 2, Tier 2 X.509)",
    credentialId,
    agentId,
    permissions,
    constraints,
  });

  const jwt = await new jose.SignJWT(payload)
    .setProtectedHeader({ typ: "JWT", alg: algorithm, kid, x5c, "x5t#S256": thumbprint })
    .setIssuedAt()
    .setNotBefore(vf)
    .setExpirationTime(vu)
    .sign(privateKey);

  const pool = getPool();
  await pool.query(
    `INSERT INTO portauth_issued_credentials
       (credential_id, issuer_id, agent_id, audience, permissions, constraints, valid_from, valid_until, kid, format)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'x509-jwt')`,
    [credentialId, issuerId, agentId, audience, JSON.stringify(permissions), JSON.stringify(constraints), vf, vu, kid]
  );

  return {
    credentialId,
    credential: jwt,
    format: "x509-jwt",
    issuerId,
    validFrom: vf.toISOString(),
    validUntil: vu.toISOString(),
  };
}
