#!/usr/bin/env node
/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

import {
  buildStuckPendingFailurePatch,
  createPostgresTaskStore,
  ensurePostgresTaskStoreSchema,
  reconcilePendingTaskRecords,
} from "portauth-a2a-receiver";

const DEFAULT_THRESHOLD_MS = 15 * 60 * 1000;

export async function runPendingReconciliation({
  databaseUrl = process.env.DATABASE_URL,
  tableName = process.env.A2A_TASK_STORE_TABLE || "portauth_a2a_tasks",
  thresholdMs = Number(process.env.A2A_PENDING_THRESHOLD_MS || DEFAULT_THRESHOLD_MS),
  limit = Number(process.env.A2A_PENDING_RECONCILE_LIMIT || 1000),
  mode = process.env.A2A_PENDING_RECONCILE_MODE || "report",
  logger = console,
} = {}) {
  if (!databaseUrl) throw new Error("DATABASE_URL is required");
  if (!Number.isFinite(thresholdMs) || thresholdMs <= 0) {
    throw new Error("A2A_PENDING_THRESHOLD_MS must be a positive number");
  }
  if (!["report", "mark-failed"].includes(mode)) {
    throw new Error("A2A_PENDING_RECONCILE_MODE must be report or mark-failed");
  }

  const { default: pg } = await import("pg");
  const pool = new pg.Pool({ connectionString: databaseUrl });
  try {
    await ensurePostgresTaskStoreSchema(pool, { tableName });
    const taskStore = createPostgresTaskStore({ queryable: pool, tableName });
    const summary = await reconcilePendingTaskRecords({
      taskStore,
      olderThanMs: thresholdMs,
      limit,
      resolveRecord: (record) => {
        if (mode === "report") return null;
        return buildStuckPendingFailurePatch(record, {
          message: "Reference receiver marked stale pending task failed so a retry can re-evaluate.",
        });
      },
    });
    logger.log(JSON.stringify({
      mode,
      thresholdMs,
      inspected: summary.inspected,
      stuck: summary.stuck,
      resolved: summary.resolved.map(summarizeRecord),
      skipped: summary.skipped.map(summarizeRecord),
      failed: summary.failed.map(({ record, error }) => ({ ...summarizeRecord(record), error })),
    }, null, 2));
    return summary;
  } finally {
    await pool.end();
  }
}

function summarizeRecord(record) {
  return {
    id: record.id,
    taskId: record.taskId,
    idempotencyKey: record.idempotencyKey,
    lifecycleState: record.lifecycleState,
    auditRecordId: record.auditRecordId,
    updatedAt: record.updatedAt,
  };
}

const isCli = process.argv[1] && process.argv[1].endsWith("/reconcile-pending.js");
if (isCli) {
  await runPendingReconciliation();
}

