/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import {
  A2A_MEDIA_TYPE,
  EXTENSION_URI,
  buildA2aSendMessageRequest,
  buildPortAuthAgentCard,
  buildPortAuthMetadata,
  extractPortAuthMetadata,
  preflight,
  sendWithVc,
  validatePortAuthMetadata,
} from "portauth-a2a";
import {
  buildEngineRequest,
  createMemoryTaskStore,
  createOtelObserver,
  createPortAuthReceiver,
  isProofOfPossessionRequired,
} from "portauth-a2a-receiver";
import {
  authorizeReceiverRequest,
  checkReadiness,
  createMetricsCollector,
  createReferenceReceiverServer,
  isAuthorizedBearer,
  isPlaceholderSecret,
  loadOpenApiDocument,
  normalizeReceiverAuthConfig,
  redact,
  resolveCliContextMapper,
  resolvePopPolicy,
  resolveReceiverSecrets,
} from "../reference-receiver/src/server.js";
import { billPaymentContextMapper } from "../reference-receiver/examples/bill-payment-mapper.js";

const credential = "eyJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJhZ2VudCJ9.signature";
const requestContext = {
  action: "payments:bill_pay",
  resource: "urn:bank:utilities/electric",
  claimAmount: 2400,
  currency: "USD",
  recipientId: "utilities",
  geoRegion: "US",
};

function response(status, body) {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => body,
    text: async () => JSON.stringify(body),
  };
}

function makeMessage(overrides = {}) {
  const metadata = buildPortAuthMetadata({
    credential,
    vcFormat: "tier1-jwt",
    presenterId: "agent:customer-finance-1",
    idempotencyKey: "bill-2026-06-electric",
    ...overrides.metadata,
  });
  const { metadata: _metadataOverride, ...messageOverrides } = overrides;
  return buildA2aSendMessageRequest({
    text: "Pay my electric bill for 2400 USD.",
    data: requestContext,
    metadata,
    ...messageOverrides,
  });
}

describe("PortAuth A2A SDK metadata helpers", () => {
  it("round-trips required metadata", () => {
    const metadata = buildPortAuthMetadata({
      credential,
      vcFormat: "tier1-jwt",
      presenterId: "agent:customer-finance-1",
    });
    assert.equal(validatePortAuthMetadata(metadata).ok, true);
    const extracted = extractPortAuthMetadata({ metadata });
    assert.equal(extracted.credential, credential);
    assert.equal(extracted.vcFormat, "tier1-jwt");
    assert.equal(extracted.presenterId, "agent:customer-finance-1");
  });

  it("rejects unsupported credential formats", () => {
    assert.throws(() => buildPortAuthMetadata({
      credential,
      vcFormat: "tier4-alien",
      presenterId: "agent:customer-finance-1",
    }), /vcFormat must be one of/);
    const metadata = {
      [`${EXTENSION_URI}/vc`]: credential,
      [`${EXTENSION_URI}/vcFormat`]: "tier4-alien",
      [`${EXTENSION_URI}/presenterId`]: "agent:customer-finance-1",
    };
    const validation = validatePortAuthMetadata(metadata);
    assert.equal(validation.ok, false);
    assert.ok(validation.errors.some((error) => error.field.endsWith("/vcFormat")));
  });

  it("rejects missing credentials at construction time", () => {
    assert.throws(() => buildPortAuthMetadata({
      vcFormat: "tier1-jwt",
      presenterId: "agent:customer-finance-1",
    }), /credential or vc must be/);
  });

  it("builds an Agent Card declaration that advertises the PortAuth extension", () => {
    const card = buildPortAuthAgentCard({
      url: "http://receiver.test",
      governanceManifestUrl: "http://engine.test/.well-known/agent-governance",
    });
    assert.equal(card.supportedInterfaces[0].protocolBinding, "HTTP+JSON");
    assert.equal(card.capabilities.extensions[0].uri, EXTENSION_URI);
    assert.equal(card.capabilities.extensions[0].required, true);
  });

  it("runs preflight through the governance manifest from the Agent Card", async () => {
    const card = buildPortAuthAgentCard({
      url: "http://receiver.test",
      governanceManifestUrl: "http://engine.test/.well-known/agent-governance",
    });
    const result = await preflight("http://receiver.test", credential, requestContext, {
      fetchImpl: async () => response(200, card),
      preflightModule: {
        preflightCheck: async (input) => ({
          compatible: true,
          incompatibilities: [],
          observedManifestUrl: input.manifestUrl,
          observedRequestContext: input.requestContext,
        }),
      },
    });
    assert.equal(result.compatible, true);
    assert.equal(result.manifestUrl, "http://engine.test/.well-known/agent-governance");
    assert.equal(result.observedManifestUrl, "http://engine.test/.well-known/agent-governance");
    assert.equal(result.observedRequestContext.action, "payments:bill_pay");
  });
});

describe("PortAuth A2A receiver guard", () => {
  it("validates bearer endpoint authorization headers", () => {
    assert.deepEqual(normalizeReceiverAuthConfig({
      authMode: "Bearer",
      bearerToken: "receiver-secret",
    }), {
      authMode: "bearer",
      bearerToken: "receiver-secret",
    });
    assert.equal(isAuthorizedBearer("Bearer receiver-secret", "receiver-secret"), true);
    assert.equal(isAuthorizedBearer("bearer receiver-secret", "receiver-secret"), true);
    assert.equal(isAuthorizedBearer("Bearer wrong-secret", "receiver-secret"), false);
    assert.equal(isAuthorizedBearer("", "receiver-secret"), false);
    assert.throws(() => normalizeReceiverAuthConfig({ authMode: "bearer" }), /A2A_RECEIVER_BEARER_TOKEN/);
  });

  it("returns a fail-closed endpoint auth response when bearer auth is missing", () => {
    const denied = authorizeReceiverRequest({
      headers: {},
    }, {
      authMode: "bearer",
      bearerToken: "receiver-secret",
    });
    assert.equal(denied.ok, false);
    assert.equal(denied.status, 401);
    assert.equal(denied.body.error.code, "UNAUTHENTICATED");
    assert.equal(denied.headers["Content-Type"], A2A_MEDIA_TYPE);
    assert.equal(denied.headers["WWW-Authenticate"], "Bearer realm=\"PortAuth A2A Reference Receiver\"");

    const allowed = authorizeReceiverRequest({
      headers: { authorization: "Bearer receiver-secret" },
    }, {
      authMode: "bearer",
      bearerToken: "receiver-secret",
    });
    assert.equal(allowed.ok, true);
  });

  it("returns a completed A2A task when the engine allows", async () => {
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      fetchImpl: async () => response(200, {
        decision: "allow",
        auditRecordId: "ar_allow_1",
      }),
    });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage(),
    });
    assert.equal(result.status, 200);
    assert.equal(result.body.task.status.state, "TASK_STATE_COMPLETED");
    assert.equal(result.body.task.metadata.auditRecordId, "ar_allow_1");
    const stored = await receiver.taskStore.getByIdempotencyKey("bill-2026-06-electric");
    assert.equal(stored.lifecycleState, "completed");
    assert.equal(stored.task.id, result.body.task.id);
    assert.equal(stored.auditRecordId, "ar_allow_1");
    assert.equal(stored.task.metadata.auditRecordId, "ar_allow_1");
    assert.equal(stored.response.status, 200);
  });

  it("persists a pending task before evaluating with the engine", async () => {
    const events = [];
    const records = new Map();
    const taskStore = {
      async createPending(record) {
        events.push("createPending");
        records.set(record.id, record);
        return { created: true, record };
      },
      async update(id, patch) {
        events.push(`update:${patch.lifecycleState}`);
        const updated = { ...records.get(id), ...patch };
        records.set(id, updated);
        return updated;
      },
      async get(id) {
        return records.get(id) || null;
      },
      async getByIdempotencyKey() {
        return null;
      },
      async list() {
        return [...records.values()];
      },
    };
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      taskStore,
      logger: silentLogger(),
      fetchImpl: async () => {
        events.push("engine");
        return response(200, {
          decision: "allow",
          auditRecordId: "ar_order_1",
        });
      },
    });

    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage(),
    });

    assert.equal(result.status, 200);
    assert.deepEqual(events, ["createPending", "engine", "update:completed"]);
  });

  it("does not treat taskId as an idempotency key for continuation messages", async () => {
    let engineCalls = 0;
    const engineBodies = [];
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      taskStore: createMemoryTaskStore(),
      logger: silentLogger(),
      fetchImpl: async (_url, options) => {
        engineCalls += 1;
        engineBodies.push(JSON.parse(options.body));
        return response(200, {
          decision: "allow",
          auditRecordId: `ar_continuation_${engineCalls}`,
        });
      },
    });
    const firstBody = makeMessage({
      taskId: "task-continuation-1",
      messageId: "message-continuation-1",
      metadata: { idempotencyKey: undefined },
    });
    const secondBody = makeMessage({
      taskId: "task-continuation-1",
      messageId: "message-continuation-2",
      metadata: { idempotencyKey: undefined },
    });

    const first = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: firstBody,
    });
    const second = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: secondBody,
    });

    assert.equal(first.status, 200);
    assert.equal(second.status, 200);
    assert.equal(first.body.task.id, "task-continuation-1");
    assert.equal(second.body.task.id, "task-continuation-1");
    assert.equal(engineCalls, 2);
    assert.equal(engineBodies[0].idempotencyKey, "message-continuation-1");
    assert.equal(engineBodies[1].idempotencyKey, "message-continuation-2");
  });

  it("replays the stored response for duplicate idempotency keys", async () => {
    let engineCalls = 0;
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      taskStore: createMemoryTaskStore(),
      logger: silentLogger(),
      fetchImpl: async () => {
        engineCalls += 1;
        return response(200, {
          decision: "allow",
          auditRecordId: "ar_idempotent_1",
        });
      },
    });
    const body = makeMessage();
    const first = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });
    const second = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });

    assert.equal(first.status, 200);
    assert.equal(second.status, 200);
    assert.equal(engineCalls, 1);
    assert.equal(second.body.task.id, first.body.task.id);
    assert.equal(second.body.task.metadata.auditRecordId, "ar_idempotent_1");
  });

  it("re-evaluates after transient engine failures instead of replaying failed responses", async () => {
    let engineCalls = 0;
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      taskStore: createMemoryTaskStore(),
      logger: silentLogger(),
      fetchImpl: async () => {
        engineCalls += 1;
        if (engineCalls === 1) {
          return response(503, { error: "temporary_unavailable" });
        }
        return response(200, {
          decision: "allow",
          auditRecordId: "ar_retry_1",
        });
      },
    });
    const body = makeMessage();

    const first = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });
    const second = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });

    assert.equal(first.status, 503);
    assert.equal(second.status, 200);
    assert.equal(engineCalls, 2);
    const stored = await receiver.taskStore.getByIdempotencyKey("bill-2026-06-electric");
    assert.equal(stored.lifecycleState, "completed");
    assert.equal(stored.auditRecordId, "ar_retry_1");
  });

  it("maps engine denies to A2A error status payloads", async () => {
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      fetchImpl: async () => response(200, {
        decision: "deny",
        error: "permission_denied",
        message: "permission missing",
        auditRecordId: "ar_deny_1",
      }),
    });
    const body = makeMessage({ taskId: "task-deny-1" });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });
    assert.equal(result.status, 403);
    assert.equal(result.body.error.code, "PERMISSION_DENIED");
    assert.equal(result.body.error.details[0].metadata.auditRecordId, "ar_deny_1");
    assert.equal(result.body.error.details[0].metadata.engineError, "permission_denied");
    const stored = await receiver.taskStore.getByIdempotencyKey("bill-2026-06-electric");
    assert.equal(stored.lifecycleState, "denied");
    assert.equal(stored.task.id, "task-deny-1");
    assert.equal(stored.auditRecordId, "ar_deny_1");
    assert.equal(stored.errorReason, "permission_denied");
    assert.equal(stored.response.status, 403);
  });

  it("rejects requests that omit the activation header", async () => {
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      fetchImpl: async () => response(200, { decision: "allow" }),
    });
    const result = await receiver.handleSendMessage({
      headers: {},
      body: makeMessage(),
    });
    assert.equal(result.status, 412);
    assert.equal(result.body.error.details[0].reason, "PORTAUTH_EXTENSION_REQUIRED");
  });

  it("rejects requests that omit required PortAuth metadata", async () => {
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      fetchImpl: async () => response(200, { decision: "allow" }),
    });
    const body = makeMessage();
    delete body.message.metadata[`${EXTENSION_URI}/vc`];
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });
    assert.equal(result.status, 400);
    assert.equal(result.body.error.details[0].reason, "PORTAUTH_METADATA_INVALID");
  });

  it("routes delegation chains to /evaluate/batch in root-to-leaf order", async () => {
    const calls = [];
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      fetchImpl: async (url, options) => {
        calls.push({ url: String(url), body: JSON.parse(options.body) });
        return response(200, { decision: "allow", auditRecordId: "ar_chain_1" });
      },
    });
    const body = makeMessage({
      metadata: {
        delegationChain: ["root.jwt", "middle.jwt"],
      },
    });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body,
    });
    assert.equal(result.status, 200);
    assert.equal(calls[0].url, "http://engine.test/evaluate/batch");
    assert.deepEqual(calls[0].body.credentials, ["root.jwt", "middle.jwt", credential]);
  });

  it("builds single-credential engine requests without delegation fields", () => {
    const engineRequest = buildEngineRequest({
      credential,
      presenterId: "agent:customer-finance-1",
      idempotencyKey: "idem-1",
      delegationChain: [],
    }, requestContext);
    assert.equal(engineRequest.credential, credential);
    assert.equal(engineRequest.presenterId, "agent:customer-finance-1");
    assert.equal(engineRequest.idempotencyKey, "idem-1");
    assert.equal(engineRequest.credentials, undefined);
  });
});

describe("PortAuth A2A presenter", () => {
  it("discovers Agent Card and sends an activated A2A message", async () => {
    const card = buildPortAuthAgentCard({
      url: "http://receiver.test",
      governanceManifestUrl: "http://engine.test/.well-known/agent-governance",
    });
    const calls = [];
    const result = await sendWithVc({
      receiverUrl: "http://receiver.test",
      credential,
      vcFormat: "tier1-jwt",
      presenterId: "agent:customer-finance-1",
      text: "Pay my electric bill for 2400 USD.",
      requestContext,
      authorization: "Bearer receiver-secret",
      fetchImpl: async (url, options = {}) => {
        calls.push({ url: String(url), options });
        if (String(url).endsWith("/.well-known/agent-card.json")) return response(200, card);
        if (String(url).endsWith("/message:send")) {
          assert.equal(options.headers.Authorization, "Bearer receiver-secret");
          assert.equal(options.headers["A2A-Extensions"], EXTENSION_URI);
          const body = JSON.parse(options.body);
          assert.equal(body.message.metadata[`${EXTENSION_URI}/vc`], credential);
          return response(200, { task: { id: "task-1", status: { state: "TASK_STATE_COMPLETED" } } });
        }
        return response(404, {});
      },
    });
    assert.equal(result.ok, true);
    assert.equal(calls[0].url, "http://receiver.test/.well-known/agent-card.json");
    assert.equal(calls[1].url, "http://receiver.test/message:send");
  });
});

describe("PortAuth A2A engine auth + monitoring", () => {
  it("attaches the engine bearer token and request id to /evaluate calls", async () => {
    let seen = null;
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      engineAuthToken: "engine-secret",
      logger: silentLogger(),
      fetchImpl: async (url, options) => {
        seen = { url: String(url), headers: options.headers };
        return response(200, { decision: "allow", auditRecordId: "ar_auth_1" });
      },
    });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI, "x-request-id": "req-123" },
      body: makeMessage(),
    });
    assert.equal(result.status, 200);
    assert.equal(seen.headers.Authorization, "Bearer engine-secret");
    assert.equal(seen.headers["X-Request-Id"], "req-123");
    assert.equal(result.headers["X-Request-Id"], "req-123");
  });

  it("emits a decision event with timing and audit id", async () => {
    const events = [];
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      onEvent: (event) => events.push(event),
      fetchImpl: async () => response(200, { decision: "allow", auditRecordId: "ar_evt_1" }),
    });
    await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage(),
    });
    const decision = events.find((event) => event.type === "decision");
    assert.ok(decision, "expected a decision event");
    assert.equal(decision.decision, "allow");
    assert.equal(decision.auditRecordId, "ar_evt_1");
    assert.equal(typeof decision.engineDurationMs, "number");
    assert.ok(decision.requestId);
  });

  it("emits a rejected event when activation is missing", async () => {
    const events = [];
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      onEvent: (event) => events.push(event),
      fetchImpl: async () => response(200, { decision: "allow" }),
    });
    await receiver.handleSendMessage({ headers: {}, body: makeMessage() });
    const rejected = events.find((event) => event.type === "rejected");
    assert.equal(rejected.reason, "PORTAUTH_EXTENSION_REQUIRED");
    assert.equal(rejected.status, 412);
  });

  it("never lets an onEvent observer break request handling", async () => {
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      onEvent: () => { throw new Error("observer boom"); },
      fetchImpl: async () => response(200, { decision: "allow", auditRecordId: "ar_safe_1" }),
    });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage(),
    });
    assert.equal(result.status, 200);
  });

  it("collects Prometheus metrics from events", () => {
    const metrics = createMetricsCollector();
    metrics.record({ type: "decision", decision: "allow", engineDurationMs: 5, durationMs: 9 });
    metrics.record({ type: "decision", decision: "deny", engineDurationMs: 3, durationMs: 7 });
    metrics.record({ type: "rejected", reason: "PORTAUTH_EXTENSION_REQUIRED" });
    metrics.record({ type: "replay" });
    metrics.record({ type: "persistence_failed", phase: "final" });
    const snapshot = metrics.snapshot();
    assert.equal(snapshot.decisions.allow, 1);
    assert.equal(snapshot.decisions.deny, 1);
    assert.equal(snapshot.replays, 1);
    assert.equal(snapshot.persistenceFailures.final, 1);
    assert.equal(snapshot.engineLatency.count, 2);
    const text = metrics.render();
    assert.match(text, /portauth_a2a_decisions_total\{decision="allow"\} 1/);
    assert.match(text, /portauth_a2a_replays_total 1/);
  });
});

describe("PortAuth A2A production secret handling", () => {
  it("flags development placeholders", () => {
    assert.equal(isPlaceholderSecret("dev-engine-key-change-me"), true);
    assert.equal(isPlaceholderSecret("changeme"), true);
    assert.equal(isPlaceholderSecret(""), true);
    assert.equal(isPlaceholderSecret(undefined), true);
    assert.equal(isPlaceholderSecret("Zk9x2Lp7Qv3w"), false);
  });

  it("fails closed on missing or placeholder secrets", () => {
    const result = resolveReceiverSecrets({
      A2A_RECEIVER_AUTH_MODE: "bearer",
      A2A_ENABLE_TASK_LOOKUP: "true",
      A2A_ENGINE_AUTH_TOKEN: "dev-engine-key-change-me",
    });
    assert.equal(result.ok, false);
    assert.ok(result.errors.some((e) => e.includes("A2A_RECEIVER_BEARER_TOKEN")));
    assert.ok(result.errors.some((e) => e.includes("A2A_TASK_READ_TOKEN")));
    assert.ok(result.errors.some((e) => e.includes("A2A_ENGINE_AUTH_TOKEN")));
  });

  it("passes with real secrets and warns about unauthenticated engine", () => {
    const result = resolveReceiverSecrets({
      A2A_RECEIVER_AUTH_MODE: "bearer",
      A2A_RECEIVER_BEARER_TOKEN: "Zk9x2Lp7Qv3w",
    });
    assert.equal(result.ok, true);
    assert.equal(result.errors.length, 0);
    assert.ok(result.warnings.some((w) => w.includes("A2A_ENGINE_AUTH_TOKEN")));
  });

  it("allows local runs under A2A_DEV_INSECURE", () => {
    const result = resolveReceiverSecrets({
      A2A_RECEIVER_AUTH_MODE: "bearer",
      A2A_DEV_INSECURE: "true",
    });
    assert.equal(result.ok, true);
    assert.equal(result.devInsecure, true);
  });

  it("redacts secret-bearing fields from log payloads", () => {
    const redacted = redact({
      msg: "a2a.event",
      auditRecordId: "ar_1",
      authorization: "Bearer abc",
      engineAuthToken: "secret-token",
      nested: { vc: "eyJ...", presenterId: "agent:1" },
    });
    assert.equal(redacted.authorization, "[redacted]");
    assert.equal(redacted.engineAuthToken, "[redacted]");
    assert.equal(redacted.nested.vc, "[redacted]");
    assert.equal(redacted.auditRecordId, "ar_1");
    assert.equal(redacted.nested.presenterId, "agent:1");
  });
});

describe("PortAuth A2A readiness", () => {
  it("is ready when engine and store both respond", async () => {
    const readiness = await checkReadiness({
      engineUrl: "http://engine.test",
      taskStore: createMemoryTaskStore(),
      fetchImpl: async () => response(200, { ok: true }),
    });
    assert.equal(readiness.ready, true);
    assert.equal(readiness.checks.engine.ok, true);
    assert.equal(readiness.checks.store.ok, true);
  });

  it("is not ready when the engine is unreachable", async () => {
    const readiness = await checkReadiness({
      engineUrl: "http://engine.test",
      taskStore: createMemoryTaskStore(),
      fetchImpl: async () => { throw new Error("connection refused"); },
    });
    assert.equal(readiness.ready, false);
    assert.equal(readiness.checks.engine.ok, false);
    assert.equal(readiness.checks.store.ok, true);
  });
});

describe("PortAuth A2A neutral receiver template", () => {
  function makeDomainMessage(data) {
    return buildA2aSendMessageRequest({
      text: "do a thing",
      data,
      metadata: buildPortAuthMetadata({
        credential,
        vcFormat: "tier1-jwt",
        presenterId: "agent:neutral-1",
      }),
    });
  }

  async function startTestServer(options) {
    const parts = createReferenceReceiverServer({ logger: silentLogger(), ...options });
    await new Promise((resolve) => parts.server.listen(0, "127.0.0.1", resolve));
    const { port } = parts.server.address();
    return { ...parts, baseUrl: `http://127.0.0.1:${port}` };
  }

  async function postMessage(baseUrl, body) {
    const resp = await fetch(`${baseUrl}/message:send`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "A2A-Extensions": EXTENSION_URI },
      body: JSON.stringify(body),
    });
    return { status: resp.status, body: await resp.json() };
  }

  it("forwards arbitrary domain context with the default mapper", async () => {
    let captured = null;
    const { server, baseUrl } = await startTestServer({
      engineUrl: "http://engine.test",
      fetchImpl: async (_url, options) => {
        captured = JSON.parse(options.body);
        return response(200, { decision: "allow", auditRecordId: "ar_neutral" });
      },
    });
    try {
      const result = await postMessage(baseUrl, makeDomainMessage({ action: "docs:read", resource: "urn:docs:42", scope: "team" }));
      assert.equal(result.status, 200);
      assert.equal(captured.requestContext.action, "docs:read");
      assert.equal(captured.requestContext.resource, "urn:docs:42");
      assert.equal(captured.requestContext.scope, "team");
    } finally {
      server.close();
    }
  });

  it("uses an injected domain mapper when provided", async () => {
    let captured = null;
    const { server, baseUrl } = await startTestServer({
      engineUrl: "http://engine.test",
      contextMapper: billPaymentContextMapper,
      fetchImpl: async (_url, options) => {
        captured = JSON.parse(options.body);
        return response(200, { decision: "allow", auditRecordId: "ar_bank" });
      },
    });
    try {
      // Only claimAmount supplied; the injected banking mapper fills the defaults.
      const result = await postMessage(baseUrl, makeDomainMessage({ claimAmount: 100 }));
      assert.equal(result.status, 200);
      assert.equal(captured.requestContext.action, "payments:bill_pay");
      assert.equal(captured.requestContext.claimAmount, 100);
    } finally {
      server.close();
    }
  });

  it("serves a domain-neutral Agent Card by default", () => {
    const { agentCard } = createReferenceReceiverServer({ engineUrl: "http://engine.test", logger: silentLogger() });
    assert.match(agentCard.name, /PortAuth A2A Receiver/);
    assert.doesNotMatch(agentCard.name, /Bill Payment/);
  });

  it("allows overriding the Agent Card identity", () => {
    const { agentCard } = createReferenceReceiverServer({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      agentCardName: "Acme Procurement Receiver",
    });
    assert.equal(agentCard.name, "Acme Procurement Receiver");
  });

  it("resolves the neutral mapper when A2A_CONTEXT_MAPPER is unset", async () => {
    assert.equal(await resolveCliContextMapper({}), undefined);
    assert.equal(await resolveCliContextMapper({ A2A_CONTEXT_MAPPER: "default" }), undefined);
  });

  it("resolves the bill-payment example mapper by name", async () => {
    const mapper = await resolveCliContextMapper({ A2A_CONTEXT_MAPPER: "bill-payment" });
    assert.equal(typeof mapper, "function");
  });

  it("throws on an unknown mapper name", async () => {
    await assert.rejects(() => resolveCliContextMapper({ A2A_CONTEXT_MAPPER: "nope" }), /Unknown A2A_CONTEXT_MAPPER/);
  });
});

describe("PortAuth A2A mandatory proof-of-possession", () => {
  const pop = { jws: "eyJhbGciOiJFUzI1NiJ9.eyJub25jZSI6Im4xIn0.sig" };

  it("rejects a request missing PoP before calling the engine when required", async () => {
    let engineCalled = false;
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      requireProofOfPossession: true,
      logger: silentLogger(),
      fetchImpl: async () => { engineCalled = true; return response(200, { decision: "allow" }); },
    });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage(),
    });
    assert.equal(result.status, 401);
    assert.equal(result.body.error.details[0].reason, "PORTAUTH_POP_REQUIRED");
    assert.equal(engineCalled, false, "engine must not be called for a PoP-rejected request");
  });

  it("allows a request that carries PoP and forwards it to the engine", async () => {
    let engineBody = null;
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      requireProofOfPossession: true,
      logger: silentLogger(),
      fetchImpl: async (_url, options) => {
        engineBody = JSON.parse(options.body);
        return response(200, { decision: "allow", auditRecordId: "ar_pop_1" });
      },
    });
    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage({ metadata: { proofOfPossession: pop } }),
    });
    assert.equal(result.status, 200);
    assert.deepEqual(engineBody.proofOfPossession, pop);
  });

  it("requires PoP only for matching actions with a predicate policy", async () => {
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      requireProofOfPossession: ({ requestContext }) => requestContext.action === "payments:bill_pay",
      logger: silentLogger(),
      fetchImpl: async () => response(200, { decision: "allow" }),
    });
    // Sensitive action without PoP -> rejected.
    const sensitive = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage(),
    });
    assert.equal(sensitive.status, 401);
    // Non-matching action without PoP -> allowed through.
    const benign = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: makeMessage({ data: { action: "docs:read", resource: "urn:docs:1" } }),
    });
    assert.equal(benign.status, 200);
  });

  it("emits a rejected event for a missing-PoP rejection", async () => {
    const events = [];
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      requireProofOfPossession: true,
      logger: silentLogger(),
      onEvent: (event) => events.push(event),
      fetchImpl: async () => response(200, { decision: "allow" }),
    });
    await receiver.handleSendMessage({ headers: { "a2a-extensions": EXTENSION_URI }, body: makeMessage() });
    const rejected = events.find((event) => event.type === "rejected");
    assert.equal(rejected.reason, "PORTAUTH_POP_REQUIRED");
    assert.equal(rejected.status, 401);
  });

  it("fails closed when a policy predicate throws", () => {
    const required = isProofOfPossessionRequired(() => { throw new Error("boom"); }, {}, silentLogger());
    assert.equal(required, true);
  });

  it("resolves a PoP policy from the environment", () => {
    assert.equal(resolvePopPolicy({}), false);
    assert.equal(resolvePopPolicy({ A2A_REQUIRE_POP: "true" }), true);
    const predicate = resolvePopPolicy({ A2A_POP_REQUIRED_ACTIONS: "payments:bill_pay, payouts:send" });
    assert.equal(typeof predicate, "function");
    assert.equal(predicate({ requestContext: { action: "payments:bill_pay" } }), true);
    assert.equal(predicate({ requestContext: { action: "docs:read" } }), false);
  });
});

describe("PortAuth A2A OpenTelemetry observer", () => {
  function fakeMeter() {
    const counters = {};
    const histograms = {};
    return {
      counters,
      histograms,
      createCounter(name) {
        counters[name] = [];
        return { add: (value, attributes) => counters[name].push({ value, attributes }) };
      },
      createHistogram(name) {
        histograms[name] = [];
        return { record: (value, attributes) => histograms[name].push({ value, attributes }) };
      },
    };
  }

  function fakeTracer() {
    const spans = [];
    return {
      spans,
      startSpan(name, options) {
        const span = { name, options, attributes: {}, status: null, ended: false };
        spans.push(span);
        return {
          setAttribute: (k, v) => { span.attributes[k] = v; },
          setStatus: (s) => { span.status = s; },
          end: () => { span.ended = true; },
        };
      },
    };
  }

  it("requires a Meter", () => {
    assert.throws(() => createOtelObserver({}), /requires an OpenTelemetry Meter/);
  });

  it("records decision counters, latency histograms, and a span", () => {
    const meter = fakeMeter();
    const tracer = fakeTracer();
    const observe = createOtelObserver({ meter, tracer });
    observe({ type: "decision", decision: "allow", requestId: "r1", auditRecordId: "ar1", engineDurationMs: 5, durationMs: 12, taskId: "t1" });

    assert.deepEqual(meter.counters["portauth.a2a.decisions"][0], { value: 1, attributes: { decision: "allow" } });
    assert.equal(meter.histograms["portauth.a2a.engine_call.duration"][0].value, 5);
    assert.equal(meter.histograms["portauth.a2a.request.duration"][0].value, 12);
    const span = tracer.spans[0];
    assert.equal(span.name, "portauth.a2a.decision");
    assert.equal(span.options.startTime <= Date.now(), true);
  });

  it("records rejections with reason and an error-status span", () => {
    const meter = fakeMeter();
    const tracer = fakeTracer();
    const observe = createOtelObserver({ meter, tracer });
    observe({ type: "rejected", reason: "PORTAUTH_POP_REQUIRED", status: 401, durationMs: 3, requestId: "r2" });

    assert.deepEqual(meter.counters["portauth.a2a.rejected"][0].attributes, { reason: "PORTAUTH_POP_REQUIRED" });
    assert.equal(tracer.spans[0].status.code, 2);
  });

  it("records replays and persistence failures", () => {
    const meter = fakeMeter();
    const observe = createOtelObserver({ meter });
    observe({ type: "replay" });
    observe({ type: "persistence_failed", phase: "final" });
    assert.equal(meter.counters["portauth.a2a.replays"].length, 1);
    assert.deepEqual(meter.counters["portauth.a2a.persistence_failures"][0].attributes, { phase: "final" });
  });

  it("works without a tracer and wires into the receiver onEvent seam", async () => {
    const meter = fakeMeter();
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      logger: silentLogger(),
      onEvent: createOtelObserver({ meter }),
      fetchImpl: async () => response(200, { decision: "allow", auditRecordId: "ar_otel" }),
    });
    const result = await receiver.handleSendMessage({ headers: { "a2a-extensions": EXTENSION_URI }, body: makeMessage() });
    assert.equal(result.status, 200);
    assert.equal(meter.counters["portauth.a2a.decisions"][0].attributes.decision, "allow");
  });
});

describe("PortAuth A2A OpenAPI contract", () => {
  const doc = loadOpenApiDocument();

  it("is a well-formed OpenAPI 3.1 document", () => {
    assert.ok(doc, "openapi.json should load");
    assert.equal(doc.openapi, "3.1.0");
    assert.ok(doc.info?.title);
    assert.ok(doc.paths && typeof doc.paths === "object");
  });

  it("documents the receiver's HTTP surface", () => {
    for (const route of ["/message:send", "/tasks", "/tasks/{taskId}", "/health", "/ready", "/metrics", "/.well-known/agent-card.json", "/openapi.json"]) {
      assert.ok(doc.paths[route], `missing path ${route}`);
    }
    assert.ok(doc.paths["/message:send"].post, "/message:send should define POST");
  });

  it("declares the error and request schemas referenced by operations", () => {
    const schemas = doc.components?.schemas || {};
    for (const name of ["SendMessageRequest", "Message", "Part", "GoogleRpcStatus", "Task", "Readiness"]) {
      assert.ok(schemas[name], `missing component schema ${name}`);
    }
  });

  it("has no dangling local $refs", () => {
    const refs = [];
    (function collect(node) {
      if (Array.isArray(node)) return node.forEach(collect);
      if (node && typeof node === "object") {
        for (const [key, value] of Object.entries(node)) {
          if (key === "$ref" && typeof value === "string") refs.push(value);
          else collect(value);
        }
      }
    })(doc);
    for (const ref of refs) {
      assert.ok(ref.startsWith("#/"), `unexpected non-local ref ${ref}`);
      const target = ref.slice(2).split("/").reduce((acc, part) => acc?.[part], doc);
      assert.ok(target, `dangling $ref ${ref}`);
    }
  });

  it("is served at GET /openapi.json", async () => {
    const { server } = createReferenceReceiverServer({ engineUrl: "http://engine.test", logger: silentLogger() });
    await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
    try {
      const { port } = server.address();
      const resp = await fetch(`http://127.0.0.1:${port}/openapi.json`);
      assert.equal(resp.status, 200);
      const body = await resp.json();
      assert.equal(body.openapi, "3.1.0");
    } finally {
      server.close();
    }
  });
});

function silentLogger() {
  return {
    info() {},
    warn() {},
    error() {},
  };
}
