/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

// preflight() must work from a published `portauth-a2a` tarball WITHOUT the
// monorepo present. It previously dynamically imported `sdks/preflight`, a path
// that only resolves inside the repo, so an installed package threw
// ERR_MODULE_NOT_FOUND. The compatibility rules and a WebCrypto manifest
// verifier are now inlined. These tests pin the contract that matters:
//
//   - a real ES256-signed manifest verifies end to end (manifestVerified:true);
//   - a wrong/absent/invalid signature does NOT silently pass;
//   - verifyManifest:true that cannot be performed is a HARD error, never an
//     unverified "compatible" result;
//   - verifyManifest:false is an explicit, clearly-labelled unsigned preflight;
//   - the shipped source contains no cross-package import.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import {
  EXTENSION_URI,
  ManifestVerificationUnavailableError,
  buildPortAuthAgentCard,
  preflight,
} from "portauth-a2a";

// The shared tier1-jwt credential: header {alg:ES256}, payload {sub:agent}.
const credential = "eyJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJhZ2VudCJ9.signature";
const requestContext = { action: "payments:bill_pay", claimAmount: 2400 };

const RECEIVER_URL = "http://receiver.test";
const MANIFEST_URL = "http://engine.test/.well-known/agent-governance";
const JWKS_URL = "http://engine.test/.well-known/jwks.json";

function b64u(bytes) {
  return Buffer.from(bytes).toString("base64url");
}
function jsonB64u(obj) {
  return Buffer.from(JSON.stringify(obj)).toString("base64url");
}

function response(status, body) {
  return { ok: status >= 200 && status < 300, status, json: async () => body, text: async () => JSON.stringify(body) };
}

// A manifest the shared tier1-jwt credential is compatible with.
function compatibleManifest() {
  return { credentialProfiles: [{ id: "tier1-jwt" }], constraintTypes: [], requiredContextFields: ["action"] };
}

// Sign a manifest's proof exactly the way the state authority does: ES256
// compact JWS over the proof payload, using WebCrypto (no jose).
async function signManifest(manifest, { privateKey, kid }) {
  const protectedHeader = jsonB64u({ alg: "ES256", kid });
  const payload = jsonB64u({ iss: "governance-authority", iat: 1700000000 });
  const signingInput = `${protectedHeader}.${payload}`;
  const sig = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    privateKey,
    new TextEncoder().encode(signingInput),
  );
  return { ...manifest, proof: { jws: `${signingInput}.${b64u(new Uint8Array(sig))}` } };
}

async function makeSigner(kid = "gov-key-1") {
  const pair = await crypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign", "verify"]);
  const publicJwk = await crypto.subtle.exportKey("jwk", pair.publicKey);
  return { privateKey: pair.privateKey, jwks: { keys: [{ ...publicJwk, kid, alg: "ES256", use: "sig" }] }, kid };
}

// Route agent-card / manifest / jwks fetches. `manifest` is the (possibly
// signed) manifest object; `jwks` is what the signingKeyUrl returns.
function makeFetch({ manifest, jwks }) {
  const card = buildPortAuthAgentCard({ url: RECEIVER_URL, governanceManifestUrl: MANIFEST_URL });
  return async (url) => {
    const u = String(url);
    if (u.endsWith("/.well-known/agent-card.json")) return response(200, card);
    if (u === MANIFEST_URL) return response(200, manifest);
    if (u === JWKS_URL) return response(200, jwks);
    throw new Error(`unexpected fetch: ${u}`);
  };
}

describe("preflight() manifest verification (inlined, WebCrypto)", () => {
  it("verifies a real ES256-signed manifest end to end (manifestVerified:true)", async () => {
    const signer = await makeSigner();
    const manifest = await signManifest(compatibleManifest(), signer);
    const fetchImpl = makeFetch({ manifest, jwks: signer.jwks });

    const result = await preflight(RECEIVER_URL, credential, requestContext, {
      fetchImpl,
      verifyManifest: true,
      signingKeyUrl: JWKS_URL,
    });

    assert.equal(result.manifestVerified, true);
    assert.equal(result.compatible, true);
    assert.deepEqual(result.incompatibilities, []);
  });

  it("does NOT pass when the signature was made by a different key (no silent pass)", async () => {
    const signer = await makeSigner("gov-key-1");
    const attacker = await makeSigner("gov-key-1"); // same kid, different key
    const manifest = await signManifest(compatibleManifest(), signer);
    // Publish the attacker's JWKS instead of the real signer's.
    const fetchImpl = makeFetch({ manifest, jwks: attacker.jwks });

    const result = await preflight(RECEIVER_URL, credential, requestContext, {
      fetchImpl,
      verifyManifest: true,
      signingKeyUrl: JWKS_URL,
    });

    assert.equal(result.manifestVerified, false);
    assert.equal(result.compatible, false);
    assert.equal(result.incompatibilities[0].rule, "manifestSignature");
  });

  it("fails (does not throw) when the manifest carries no proof.jws", async () => {
    const signer = await makeSigner();
    const manifest = compatibleManifest(); // unsigned
    const fetchImpl = makeFetch({ manifest, jwks: signer.jwks });

    const result = await preflight(RECEIVER_URL, credential, requestContext, {
      fetchImpl,
      verifyManifest: true,
      signingKeyUrl: JWKS_URL,
    });
    assert.equal(result.compatible, false);
    assert.equal(result.manifestVerified, false);
    assert.equal(result.incompatibilities[0].rule, "manifestSignature");
  });

  it("HARD-errors when verifyManifest:true but no signingKeyUrl is given", async () => {
    const signer = await makeSigner();
    const manifest = await signManifest(compatibleManifest(), signer);
    const fetchImpl = makeFetch({ manifest, jwks: signer.jwks });

    await assert.rejects(
      preflight(RECEIVER_URL, credential, requestContext, { fetchImpl, verifyManifest: true }),
      ManifestVerificationUnavailableError,
    );
  });

  it("defaults to verifyManifest:true (zero-config hard-errors rather than doing unsigned checks)", async () => {
    const signer = await makeSigner();
    const manifest = await signManifest(compatibleManifest(), signer);
    const fetchImpl = makeFetch({ manifest, jwks: signer.jwks });

    // No verifyManifest, no signingKeyUrl -> must NOT silently run unsigned.
    await assert.rejects(
      preflight(RECEIVER_URL, credential, requestContext, { fetchImpl }),
      ManifestVerificationUnavailableError,
    );
  });

  it("HARD-errors on an algorithm WebCrypto cannot check (e.g. ES256K), never a silent pass", async () => {
    const signer = await makeSigner();
    // Hand-craft a proof whose header alg is ES256K (secp256k1), which WebCrypto
    // cannot verify. The signature bytes are irrelevant: the alg is rejected
    // before any key is tried.
    const jws = `${jsonB64u({ alg: "ES256K", kid: "x" })}.${jsonB64u({ iss: "x" })}.${b64u(new Uint8Array([1, 2, 3]))}`;
    const manifest = { ...compatibleManifest(), proof: { jws } };
    const fetchImpl = makeFetch({ manifest, jwks: signer.jwks });

    await assert.rejects(
      preflight(RECEIVER_URL, credential, requestContext, { fetchImpl, verifyManifest: true, signingKeyUrl: JWKS_URL }),
      ManifestVerificationUnavailableError,
    );
  });

  it("keeps verification and compatibility independent (verified manifest, incompatible credential)", async () => {
    const signer = await makeSigner();
    // Manifest is authentic but does not accept tier1-jwt credentials.
    const manifest = await signManifest(
      { credentialProfiles: [{ id: "tier3-vc-jose" }], constraintTypes: [] },
      signer,
    );
    const fetchImpl = makeFetch({ manifest, jwks: signer.jwks });

    const result = await preflight(RECEIVER_URL, credential, requestContext, {
      fetchImpl,
      verifyManifest: true,
      signingKeyUrl: JWKS_URL,
    });
    assert.equal(result.manifestVerified, true); // signature checked out
    assert.equal(result.compatible, false); // but profile is unsupported
    assert.ok(result.incompatibilities.some((i) => i.rule === "profileMatch"));
  });
});

describe("preflight() unsigned mode is explicit", () => {
  it("verifyManifest:false runs a compatibility-only check and labels it unverified", async () => {
    const manifest = compatibleManifest(); // no proof needed
    const fetchImpl = makeFetch({ manifest, jwks: { keys: [] } });

    const result = await preflight(RECEIVER_URL, credential, requestContext, {
      fetchImpl,
      verifyManifest: false,
    });
    assert.equal(result.compatible, true);
    assert.equal(result.manifestVerified, false);
  });
});

describe("portauth-a2a ships self-contained (no cross-package import)", () => {
  it("the published SDK source contains no relative import that escapes the package", async () => {
    const here = dirname(fileURLToPath(import.meta.url));
    const src = await readFile(resolve(here, "../sdk/src/index.js"), "utf8");
    // The exact regression: a dynamic import reaching out to the monorepo's
    // sibling sdks/preflight package, which is absent from a published tarball.
    assert.equal(
      /import\(\s*["'`][^"'`]*sdks\/preflight/.test(src),
      false,
      "SDK must not dynamic-import the monorepo sdks/preflight package",
    );
    assert.equal(
      /import\(\s*["'`]\.\.\/\.\.\//.test(src),
      false,
      "SDK must not dynamic-import a path that escapes the package",
    );
  });
});
