/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

// The producer side of N-hop delegation (SPEC §4.2-4.3, §7.4) as a runnable
// test rather than prose. An intermediate authorizes an inbound request, mints
// an attenuated delegated credential, and forwards downstream. The downstream
// engine re-verifies the chain with the *real* attenuation rules, so:
//
//   - a delegate that NARROWS authority is accepted (allow), and
//   - a delegate that WIDENS authority is rejected with `delegation_widened`.
//
// That side-by-side is the differentiation argument: enforcement is end-to-end,
// not a fixed two-role pattern.

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import {
  EXTENSION_URI,
  buildA2aSendMessageRequest,
  buildPortAuthMetadata,
} from "portauth-a2a";
import { createPortAuthReceiver } from "portauth-a2a-receiver";

import { buildAttenuatedClaims, createIntermediateAgent } from "../reference-intermediate/src/intermediate.js";

// The harness imports the engine's pure attenuation rules. If the engine
// package is not present (extension consumed standalone), skip rather than fail.
let harness = null;
try {
  harness = await import("../reference-intermediate/src/in-memory-delegation.js");
} catch {
  // engine package unavailable in this context
}

const requestContext = {
  action: "payments:bill_pay",
  resource: "urn:bank:utilities/electric",
  claimAmount: 2400,
  currency: "USD",
  recipientId: "utilities",
  geoRegion: "US",
};

// A well-behaved intermediate: tighten the cap (2500 -> 2400) and the recipient
// set ([utilities, telco, mortgage] -> [utilities]); keep the rest.
const narrowing = () => ({
  permissions: ["payments:bill_pay"],
  constraints: [
    { type: "NumericLimitConstraint", field: "core.amount", operator: "lte", value: 2400, currency: "USD" },
    { type: "EnumeratedListConstraint", field: "core.recipient_id", allowed: ["utilities"] },
    { type: "EnumeratedListConstraint", field: "core.geo_region", allowed: ["US"] },
  ],
});

// A hostile/buggy intermediate: raise the cap (2500 -> 3000). Everything else
// is identical, so the only difference between the two scenarios is widening.
const widening = () => ({
  permissions: ["payments:bill_pay"],
  constraints: [
    { type: "NumericLimitConstraint", field: "core.amount", operator: "lte", value: 3000, currency: "USD" },
    { type: "EnumeratedListConstraint", field: "core.recipient_id", allowed: ["utilities"] },
    { type: "EnumeratedListConstraint", field: "core.geo_region", allowed: ["US"] },
  ],
});

function silentLogger() {
  return { info() {}, warn() {}, error() {} };
}

function inboundMessage() {
  const { token } = harness.customerRootCredential();
  return buildA2aSendMessageRequest({
    text: "Please pay my electric bill $2,400.",
    data: requestContext,
    metadata: buildPortAuthMetadata({
      credential: token,
      vcFormat: "tier1-jwt",
      presenterId: "agent:customer-finance-1",
      idempotencyKey: `bill-${Date.now()}-${Math.random()}`,
    }),
  });
}

// Wire customer -> intermediate -> downstream payments receiver. The two engine
// hops share the same real-rule oracle; only the outbound fetch is routed to
// the downstream receiver.
function buildTwoHop({ narrow }) {
  const oracle = harness.createAttenuationEngineOracle();
  let lastBatch = null;
  const recordingOracle = async (url, options) => {
    if (String(url).endsWith("/evaluate/batch")) lastBatch = JSON.parse(options.body);
    return oracle(url, options);
  };

  const downstream = createPortAuthReceiver({
    engineUrl: "http://payments-engine.test",
    fetchImpl: recordingOracle,
    logger: silentLogger(),
  });

  const router = async (url, options) => {
    if (String(url).endsWith("/message:send")) {
      const result = await downstream.handleSendMessage({
        headers: options.headers,
        body: JSON.parse(options.body),
      });
      return {
        ok: result.status >= 200 && result.status < 300,
        status: result.status,
        json: async () => result.body,
        text: async () => JSON.stringify(result.body),
      };
    }
    return { ok: false, status: 404, json: async () => ({}), text: async () => "{}" };
  };

  const inboundReceiver = createPortAuthReceiver({
    engineUrl: "http://intake-engine.test",
    fetchImpl: harness.createAttenuationEngineOracle(),
    logger: silentLogger(),
  });

  const intermediate = createIntermediateAgent({
    receiver: inboundReceiver,
    fetchImpl: router,
    downstreamAgentCard: harness.downstreamAgentCard(),
    intermediatePresenterId: "agent:bank-intake",
    issueDelegatedCredential: harness.createInMemoryDelegatedIssuer({ narrow }),
  });

  return { intermediate, getLastBatch: () => lastBatch };
}

describe("Two-hop delegation: producer side", () => {
  it("buildAttenuatedClaims links the child to the parent for chain continuity", (t) => {
    if (!harness) return t.skip("engine delegation rules not available in this context");
    const { claims } = harness.customerRootCredential();
    const child = buildAttenuatedClaims(claims, { issuerId: claims.agentId, audience: "agent:bank-payments" });
    // The engine checks child.issuerId === parent.agentId and
    // child.delegatedFrom === parent.credentialId.
    assert.equal(child.issuerId, claims.agentId);
    assert.equal(child.delegatedFrom, claims.credentialId);
    assert.equal(child.agentId, "agent:bank-payments");
  });

  it("accepts a narrowing delegate end to end and forwards a 2-link chain", async (t) => {
    if (!harness) return t.skip("engine delegation rules not available in this context");
    const { intermediate, getLastBatch } = buildTwoHop({ narrow: narrowing });

    const result = await intermediate.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: inboundMessage(),
    });

    assert.equal(result.status, 200);
    assert.equal(result.body.task.status.state, "TASK_STATE_COMPLETED");

    // The downstream engine saw a root-first chain [customer, intermediate-child].
    const batch = getLastBatch();
    assert.ok(batch, "downstream /evaluate/batch should have been called");
    assert.equal(batch.credentials.length, 2);
  });

  it("rejects a widening delegate with delegation_widened", async (t) => {
    if (!harness) return t.skip("engine delegation rules not available in this context");
    const { intermediate } = buildTwoHop({ narrow: widening });

    const result = await intermediate.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: inboundMessage(),
    });

    // The downstream receiver maps the engine deny to an A2A error; the engine
    // error code is surfaced in the error metadata.
    assert.equal(result.status, 403);
    assert.equal(result.body.error.details[0].metadata.engineError, "delegation_widened");
  });

  it("does not mint or forward when the inbound request is denied (authorize first)", async (t) => {
    if (!harness) return t.skip("engine delegation rules not available in this context");

    let downstreamCalled = false;
    // Inbound receiver whose engine denies the first hop outright.
    const denyingReceiver = createPortAuthReceiver({
      engineUrl: "http://intake-engine.test",
      logger: silentLogger(),
      fetchImpl: async () => ({
        ok: true,
        status: 200,
        json: async () => ({ decision: "deny", error: "permission_denied", auditRecordId: "ar_inbound_deny" }),
        text: async () => JSON.stringify({ decision: "deny", error: "permission_denied", auditRecordId: "ar_inbound_deny" }),
      }),
    });

    const intermediate = createIntermediateAgent({
      receiver: denyingReceiver,
      fetchImpl: async () => { downstreamCalled = true; return { ok: false, status: 500, json: async () => ({}), text: async () => "{}" }; },
      downstreamAgentCard: harness.downstreamAgentCard(),
      intermediatePresenterId: "agent:bank-intake",
      issueDelegatedCredential: harness.createInMemoryDelegatedIssuer({ narrow: narrowing }),
    });

    const result = await intermediate.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: inboundMessage(),
    });

    assert.equal(result.status, 403);
    assert.equal(downstreamCalled, false, "intermediate must not forward when inbound authorization fails");
  });
});
