/*
 * Copyright contributors to the aiagent-portable-authorization project.
 * SPDX-License-Identifier: MIT
 * This code is generated by AI, edited by humans
 */

// Regression guard for SPEC.md §7 (the UC-03 bill-payment worked example).
//
// The credential constrains *semantic identifiers* (`core.amount`,
// `core.recipient_id`, `core.geo_region`) while the receiver's requestContext
// carries *receiver-local fields* (`claimAmount`, `recipientId`, `geoRegion`).
// The engine's semantic-resolution layer maps one to the other before
// evaluating. If those vocabularies drift apart, resolution returns
// `context_field_missing` and the flagship "allow" example silently denies.
//
// These tests pin the three vocabularies together:
//   1. the bill-payment mapper emits the local field names the MVV profile
//      expects, so the §7 example resolves and would evaluate `allow`;
//   2. the receiver's A2A allow-path runs end to end with that mapper.

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import { EXTENSION_URI, buildA2aSendMessageRequest, buildPortAuthMetadata } from "portauth-a2a";
import { createPortAuthReceiver } from "portauth-a2a-receiver";
import { billPaymentContextMapper } from "../reference-receiver/examples/bill-payment-mapper.js";

// The engine lives in a sibling package. Import its real MVV mapping table so
// the test proves the actual `core.* -> local` mapping, not a restatement of
// it. `defaultMappings()` is pure data (no DB), which keeps this a hermetic
// unit test. If the engine source is not present (e.g. the extension is
// consumed standalone), the resolution assertions are skipped rather than
// failed.
let defaultMappings = null;
try {
  ({ defaultMappings } = await import("../../../portauth-engine/src/services/semanticResolver.js"));
} catch {
  // engine package unavailable in this context; resolution tests self-skip
}

// The VC issued by the customer in SPEC §7.1 (semantic identifiers).
const credentialConstraints = [
  { type: "EnumeratedListConstraint", field: "core.recipient_id", allowed: ["utilities", "telco", "mortgage"] },
  { type: "CumulativeLimitConstraint", field: "core.amount", maxAmount: 2500, period: "month", scope: "agent" },
  { type: "EnumeratedListConstraint", field: "core.geo_region", allowed: ["US"] },
];

const credential = "eyJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJhZ2VudCJ9.signature";

// The domain payload a bill-pay presenter sends on the A2A data part.
const domainData = {
  action: "payments:bill_pay",
  resource: "urn:bank:utilities/electric",
  claimAmount: 2400,
  currency: "USD",
  recipientId: "utilities",
  geoRegion: "US",
};

function billPaymentMessage() {
  return buildA2aSendMessageRequest({
    text: "Please pay my electric bill $2,400.",
    data: domainData,
    metadata: buildPortAuthMetadata({
      credential,
      vcFormat: "tier3-vc-jose",
      presenterId: "did:key:zPersonalFinanceAgent",
      idempotencyKey: "bill-2026-06-electric",
    }),
  });
}

function silentLogger() {
  return { info() {}, warn() {}, error() {} };
}

describe("SPEC §7 worked example stays internally consistent", () => {
  it("the bill-payment mapper emits the local fields the credential's core.* constraints resolve to", () => {
    const requestContext = billPaymentContextMapper({ message: billPaymentMessage().message });

    // The exact bug this guards: a credential field of `core.recipient_id`
    // must find a `recipientId` key (not `recipient`) in the mapped context.
    assert.equal(requestContext.recipientId, "utilities");
    assert.equal(requestContext.geoRegion, "US");
    assert.equal(requestContext.claimAmount, 2400);
    assert.equal(typeof requestContext.claimAmount, "number");
    // `recipient` (the SPEC §7.3 typo) must not be how the value is carried.
    assert.equal("recipient" in requestContext, false);
  });

  it("every core.* constraint field maps to a local field that is present and would pass", (t) => {
    if (!defaultMappings) {
      t.skip("engine MVV mapping table not available in this context");
      return;
    }
    const mappings = defaultMappings();
    const requestContext = billPaymentContextMapper({ message: billPaymentMessage().message });

    for (const constraint of credentialConstraints) {
      const mapping = mappings.get(constraint.field);
      assert.ok(mapping, `MVV has no mapping for ${constraint.field}`);

      // The resolution the engine performs: core.* identifier -> local field,
      // which must be present in the mapped requestContext (else the engine
      // returns context_field_missing and the example silently denies).
      const value = requestContext[mapping.localField];
      assert.notEqual(
        value,
        undefined,
        `${constraint.field} -> ${mapping.localField} is missing from the mapped context`,
      );
      assert.equal(typeof value, mapping.type, `${mapping.localField} should be ${mapping.type}`);

      // Lightweight "would-allow" check: the resolved value satisfies the
      // constraint as written in §7.1 (the stateful cumulative cap itself is
      // exercised by the live-Postgres suite).
      if (constraint.type === "EnumeratedListConstraint") {
        assert.ok(constraint.allowed.includes(value), `${value} not in allowed set for ${constraint.field}`);
      }
      if (constraint.type === "CumulativeLimitConstraint") {
        assert.ok(value <= constraint.maxAmount, `${value} exceeds cap`);
      }
    }
  });
});

describe("SPEC §7 worked example drives the receiver allow-path", () => {
  it("returns a completed A2A task and forwards the resolvable local fields to the engine", async () => {
    let engineBody = null;
    const receiver = createPortAuthReceiver({
      engineUrl: "http://engine.test",
      mapRequestContext: ({ message }) => billPaymentContextMapper({ message }),
      logger: silentLogger(),
      fetchImpl: async (_url, options) => {
        engineBody = JSON.parse(options.body);
        return {
          ok: true,
          status: 200,
          text: async () => JSON.stringify({ decision: "allow", auditRecordId: "ar_uc03_allow" }),
        };
      },
    });

    const result = await receiver.handleSendMessage({
      headers: { "a2a-extensions": EXTENSION_URI },
      body: billPaymentMessage(),
    });

    assert.equal(result.status, 200);
    assert.equal(result.body.task.status.state, "TASK_STATE_COMPLETED");
    assert.equal(result.body.task.metadata.auditRecordId, "ar_uc03_allow");
    // The body the engine receives carries the local field names its semantic
    // layer maps the credential's core.* identifiers onto.
    assert.equal(engineBody.requestContext.recipientId, "utilities");
    assert.equal(engineBody.requestContext.geoRegion, "US");
    assert.equal(engineBody.requestContext.claimAmount, 2400);
  });
});
