// Copyright contributors to the aiagent-portable-authorization project.
// SPDX-License-Identifier: MIT
// This code is generated by AI, edited by humans
//
// Plan 2 reference implementation: minimal State Authority server.
//
// Provides:
//   GET  /.well-known/jwks.json   - the authority's signing key (public)
//   GET  /proofs                  - returns a freshly-signed proof JWS
//   POST /increment               - applies a delta to a counter
//
// This is a reference for protocol shape; it is not production hardened.

import express from "express";
import * as jose from "jose";
import crypto from "node:crypto";

const PORT = Number(process.env.STATE_AUTHORITY_PORT || 3400);
const AUTHORITY_ID = process.env.STATE_AUTHORITY_ID || "state-authority-ref";

let signingKey;
let publicJwk;
let kid;

const counters = new Map();

function keyFor(authorityId, counterKey, windowStart) {
  return `${authorityId}::${counterKey}::${windowStart}`;
}

async function ensureKey() {
  if (signingKey) return;
  const { privateKey, publicKey } = await jose.generateKeyPair("ES256", { extractable: true });
  signingKey = privateKey;
  const jwk = await jose.exportJWK(publicKey);
  kid = crypto.createHash("sha256").update(JSON.stringify(jwk)).digest("hex").slice(0, 16);
  publicJwk = { ...jwk, kid, use: "sig", alg: "ES256" };
}

async function start() {
  await ensureKey();

  const app = express();
  app.use(express.json());

  app.get("/.well-known/jwks.json", (_req, res) => {
    res.json({ keys: [publicJwk] });
  });

  app.get("/proofs", async (req, res) => {
    const { authorityId, counterKey, windowStart } = req.query;
    if (!authorityId || !counterKey || !windowStart) {
      return res.status(400).json({ error: "missing query parameters" });
    }
    if (authorityId !== AUTHORITY_ID) {
      return res.status(404).json({ error: "unknown authority" });
    }
    const value = counters.get(keyFor(authorityId, counterKey, windowStart)) || 0;
    const proofPayload = {
      iss: AUTHORITY_ID,
      counterKey,
      metric: "amount",
      windowStart,
      value,
      iat: Math.floor(Date.now() / 1000),
    };
    const jws = await new jose.CompactSign(new TextEncoder().encode(JSON.stringify(proofPayload)))
      .setProtectedHeader({ alg: "ES256", kid })
      .sign(signingKey);
    res.type("application/jose").send(jws);
  });

  app.post("/increment", (req, res) => {
    const { authorityId, counterKey, windowStart, delta } = req.body || {};
    if (!authorityId || !counterKey || !windowStart || !Number.isFinite(delta)) {
      return res.status(400).json({ error: "validation_error" });
    }
    if (authorityId !== AUTHORITY_ID) {
      return res.status(404).json({ error: "unknown authority" });
    }
    const k = keyFor(authorityId, counterKey, windowStart);
    const next = (counters.get(k) || 0) + Number(delta);
    counters.set(k, next);
    res.json({ value: next });
  });

  app.listen(PORT, () => {
    // eslint-disable-next-line no-console
    console.log(`state-authority-ref listening on :${PORT} (authority=${AUTHORITY_ID})`);
  });
}

start().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("state-authority-ref failed to start:", err);
  process.exit(1);
});
