#
# Copyright contributors to the aiagent-portable-authorization project.
# SPDX-License-Identifier: MIT
# This code is generated by AI, edited by humans
#
package portauth.reference

import future.keywords.contains
import future.keywords.if

default allow := false

allow if {
  input.decision == "allow"
  input.verification.valid == true
  input.permissionMatch.matched == true
}

deny_reason contains "verification_failed" if {
  input.verification.valid == false
}

deny_reason contains "permission_denied" if {
  input.permissionMatch.matched == false
}
